### ISSUE TITLE
[Tree] [Windows 11 - Beta] Getting the selection is horrible slow

### ISSUE THREAD

**Issue by mheiss** [eclipse-platform/eclipse.platform.swt#10]
I am using the current [Windows 11 Insider Build from the Beta Channel (22H2 - 22581.100)](https://blogs.windows.com/windows-insider/2022/03/23/announcing-windows-11-insider-preview-build-22581/) that was released a few days before. 

Since this build using Eclipse (2022-03) is more or less not possible anymore. Clicking around the package explorer or debugging causes the entire IDE to freeze for up to a few minutes. 

I attached a profiler to Eclipse and found out that getting the selection from a tree is horrible slow. Seems that the _win32.OS.SendMessage_ call that is done by the tree is now magnitudes slower as before. See attachments

Can someone from the SWT team check and report back with some more details what is causing the issue. If caused by recent changes in Windows i can submit some feedback with more details so that they can have a look.

![callTree](https://user-images.githubusercontent.com/5145998/160762370-3b4c9608-8f79-49a3-a60d-0ebf5c7440b7.png)
![hotSpot](https://user-images.githubusercontent.com/5145998/160762371-2a98ccaf-ec3e-47b1-9531-2e749a81d9a1.png)

**Comment by iloveeclipse** [comment]
Why not report that directly to Microsoft, if the problem only appears in insider build?

**Comment by mheiss** [comment]
Yes is did that. But only with videos of a slow IDE they might have a hard time to find the root cause. So i though it might be a good idea to open this ticket to get some more details what SWT is doing and which OS call is now slower than before.

**Comment by niraj-modi** [comment]
@SyntevoAlex 
Hi Alexandr, Any idea here ?

**Comment by kthoms** [comment]
@mheiss Could you profile _how often_ SendMessage is called during this use case?

**Comment by mheiss** [comment]
```
public class SlowDebugger {
	public static void main(String[] args) {
		for (int i = 0; i < 200; i++) {
			Thread thread = new Thread(() -> {
				while (true) {
					try {
						Thread.sleep(50);
					} catch (InterruptedException e) {
					}
				}
			});
			thread.setName("T-" + i);
			thread.start();
		}
	}
}
```

When debugging this application the Debugging View is painful slow and scrolling causes the entire IDE to freeze multiple times. Once the view manages to display all 200 threads all is fine again. But that takes ~2 minutes to complete. Attached is the profiling output with invocation counts.

![debugView](https://user-images.githubusercontent.com/5145998/160824759-1a4462ec-f9f8-44a6-ad3f-abfdeb742b87.png)
![invocations](https://user-images.githubusercontent.com/5145998/160824428-d0cf3b21-3c95-4662-8aaa-e2e6f6561b0e.png)

**Comment by merks** [comment]
I tried this running on Windows 10 and Eclipse 4.23.  The debugger basically shows 200 threads pretty much instantly, and the UI is responsive although a busy cursor shows over the Debug view for about 5 second...

**Comment by laeubi** [comment]
> I tried this running on Windows 10 and Eclipse 4.23. The debugger basically shows 200 threads pretty much instantly, and the UI is responsive although a busy cursor shows over the Debug view for about 5 second...

The title suggests that this is a **Windows 11** issue so it does not help much to test it on **Windows 10** I guess :-)

**Comment by merks** [comment]
Of course.  I'm was merely pointing out that indeed this is a problem that is not reproducible on Windows 10.   My machine asked if I wanted to install Windows 11 the other week and I was to scared to do that.  Otherwise I could test if the problem is specific to this new beta version as opposed to the already-released Windows 11 version...

**Comment by mheiss** [comment]
The issue started to arise in the new build that has been released in the beta channel. Before all was fine on Windows 11.

**Comment by SyntevoAlex** [comment]
I'm currently installing 22581.200 (from Dev channel). I'll give it a try. If it doesn't reproduce here, I'll also try Beta channel.

**Comment by SyntevoAlex** [comment]
I can confirm this problem on Win11 Preview 22582.100.
`Tree.getSelection()` in Eclipse runs at ~30/sec.

I tried to reproduce it in SWT snippet, but didn't manage yet - there, `Tree.getSelection()` runs at ~3000/sec (100x faster).

I'll continue investigating.

**Comment by SyntevoAlex** [comment]
It's a windows bug. Reproducible in a trivial native snippet that has nothing to do with Eclipse.
I submitted a detailed report to Microsoft - https://aka.ms/AAgjsay
Unfortunately my previous experience is that they completely ignore all feedback, even very high quality one with repro programs etc.

**Comment by SyntevoAlex** [comment]
Here's the snippet
[0499_Win11_MenuSlowdown.cpp.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/8394926/0499_Win11_MenuSlowdown.cpp.txt)

**Comment by mheiss** [comment]
Thx for all your efforts! I try to get some attraction for this issue by directly pinging members  of the Windows Insider Team via Twitter. Lets hope that they fix that before broadly rolling out :)

**Comment by merks** [comment]
Please let us know if getting attention for your report is successful or not.  I'm not able to view your report in the Feeback Hub with my account, so I can't tell what's happening there.

It might help to chat with Microsoft's representative on Eclipse's board of directors if your more direct root doesn't work out:

https://www.eclipse.org/org/foundation/directors.php

**Comment by SyntevoAlex** [comment]
There are no updates with my bugreport as of now.

The last time I reported a bug to Microsoft, the experience was rather insulting.
See [Bug 543747](https://bugs.eclipse.org/bugs/show_bug.cgi?id=543747)

I spent many days of work to debug Windows to find how to reproduce, and then find where the bug is coming from.

* 2019-06-04 I finalized precise repro snippet and steps and sent bugreport to Microsoft.
* 2019-09-04 Another user contacted me; he had opened paid support ticket with Microsoft. Microsoft closed that ticket, claiming that user requested it. He sent me a copy of his communications with Microsoft and by no means he requested to close the ticket.
* 2019-09-11 I contacted Microsoft on behalf of user's paid support request and sent a lot of technical info about the bug.
* 2019-09-12 Microsoft promised to have a look soon.
* 2019-09-18 Microsoft said that they still didn't have a look.
* 2019-09-23 A second user said that they also opened paid support ticket, he mentioned our previous ticket to Microsoft.
* 2019-09-24 First user reported that his ticket was now "escalated".
* 2019-10-03 Microsoft said that "issue is still being analysed" (read: didn't look into, because I already analysed everything for them).
* 2019-10-14 Still no update from Microsoft.
* 2019-11-20 First user pinged Microsoft and got no reply.
* 2020-01-06 Still nothing, Eclipse tries another workaround for Microsoft bug.
* 2020-02-13 Microsoft replied that they plan to release patch "3rd or 4th Tuesday of April".
* 2020-04-14 Microsoft said that patch is postponed.
* 2020-05-18 Bug is finally fixed in next Windows Preview build.

Summary: after I gave very precise info about the bug (where and how it comes from and a repro snippet), it took 2 paid support tickets and a year to fix it. I hate how I spent a lot of time to provide very high quality bug report and how it ended.

**Comment by merks** [comment]
Okay, I'll look into whether anyone from Microsoft involved at Eclipse could help...

**Comment by mheiss** [comment]
Up to now I got no response. My plan was to wait for next week and then try to contact the Microsoft representive in the Eclipse board.  @merks appreciate your help!

**Comment by merks** [comment]
Yes, I've reached out to Stephen already today.  Of course having worked at a large company myself, I don't necessarily expect that he can have influence over an issue like this, but it doesn't hurt to ask.

**Comment by mheiss** [comment]
I contacted Bruno Borges - Principal Program Manager, Java Engineering Group at Microsoft - and he send the issue to the responsible team.

**Comment by crutkas** [comment]
hi all, Bruno has flagged a few internally and we're looking into it.

**Comment by rolfth** [comment]
Off topic - As you have some contacts at Microsoft, can somebody get more focus on this issue too:  https://bugs.eclipse.org/bugs/show_bug.cgi?id=548443 and https://github.com/microsoft/java-wdb/issues/9 which has a huge performance impact on any Java program.

**Comment by karianna** [comment]
> Off topic - As you have some contacts at Microsoft, can somebody get more focus on this issue too: https://bugs.eclipse.org/bugs/show_bug.cgi?id=548443 and [microsoft/java-wdb#9](https://github.com/microsoft/java-wdb/issues/9) which has a huge performance impact on any Java program.

Bruno will be discussing with the Defenders team over the coming week(s)

**Comment by crutkas** [comment]
From the sample code 

> Here's the snippet [0499_Win11_MenuSlowdown.cpp.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/8394926/0499_Win11_MenuSlowdown.cpp.txt)

Hi friends, with this sample code, what are you seeing?  We want to gut check

**Comment by blairmcg** [comment]
> From the sample code
> 
> > Here's the snippet [0499_Win11_MenuSlowdown.cpp.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/8394926/0499_Win11_MenuSlowdown.cpp.txt)
> 
> Hi friends, with this sample code, what are you seeing? We want to gut check

What I see is:
- when I first run up, the title bar shows a count > 3 million iterations / second
- After opening and dismissing one menu, it drops to ~15000 iterations /second (yes, more than 2 orders of magnitude)
- Open and dismiss a menu again, it drops to ~8000 iterations /second
- Open another, and it drops to ~6000 iterations/s, and so on.

I see similar behaviour in other Win32 native apps that I work on, and notice in profiling that all the time seemed to be going in SendMessage calls. I was researching the problem when I stumbled indirectly on this manifestation. Win32 apps become unusable fairly quickly. I get the sense that Win32 UIs are slower even initially, but it is difficult to do a SxS comparison without spare h/w so I haven't measured that yet.

There must be a rather significant test gap that a bug this severe could make it out into the beta channel.

**Comment by brunoborges** [comment]
Hey all,

Just wanted to share that the Microsoft Windows team has seen this and are actively working on the issue.

We thank the Eclipse contributors for the bug report, and the sample code to reproduce the issue.

When we have more info to share, rest assured we will provide info in this thread.

Thanks,
Bruno

**Comment by SyntevoAlex** [comment]
So that others can google up this thread, here are profiling results from XPerf. Here, I selected one of "interesting" paths:

```
user32.dll!SendMessageW                                 11046
 user32.dll!SendMessageWorker                           11007
  win32u.dll!NtUserMessageCall                          10986
   ntoskrnl.exe!<PDB not found>                         10811
    win32k.sys!NtUserMessageCall                        10683
     win32kfull.sys!NtUserMessageCall                   10667
      win32kfull.sys!xxxWrapSendMessage                  9826
       win32kfull.sys!xxxSendTransformableMessageTimeout 9801
       +win32kfull.sys!xxxCallHook                       6674
       |  win32kfull.sys!xxxCallHook2                    6345
       |   win32kfull.sys!xxxHkCallHook                  5502
       |    win32kfull.sys!SfnDWORD                      4893
       |     ntoskrnl.exe!<PDB not found>                3995
       |      ntdll.dll!KiUserCallbackDispatcherContinue 3614
       |       user32.dll!__fnDWORD                      3606
       |        user32.dll!fnHkINLPCWPSTRUCTW            3432
       |         user32.dll!CallNextHookEx               3362
       |          uxtheme.dll!CThemeMenu::MenuKeyboardMsgProc 17
       +win32kfull.sys!xxxSendMessageToClient            1990
         win32kfull.sys!SfnDWORD                         1927
          ntoskrnl.exe!<PDB not found>                   1085
           ntdll.dll!KiUserCallbackDispatcherContinue     735
            user32.dll!__fnDWORD                          728
             user32.dll!DispatchClientMessage             550
              user32.dll!UserCallWinProcCheckWow          523
               comctl32.dll!TV_WndProc                    265
                user32.dll!GetWindowLongPtrW               85
                comctl32.dll!TV_OnGetItem                  75
                comctl32.dll!TV_WndProc<itself>            55
                comctl32.dll!TV_GetNextItem                31
                comctl32.dll!TV_UnlockTree                 10
```

My conclusions:
* The majority of time is spent in `SendMessage()` internals
* From it, a lot of time is spent in dispatching hooks
* One of hooks is `uxtheme.dll!CThemeMenu::MenuKeyboardMsgProc` (hence menu in my snippet)
* The actual `SendMessage()` useful workload, such as `TV_OnGetItem`, is very small.

**Comment by crutkas** [comment]
Hi all, here with an update.  We validated a fix and eta would be around 2 weeks. So if it goes smoothly with between branches, we believe the fix would be released ~4/20 to ~4/27 to insiders.

We would really love to thank everyone for making us aware and providing a great repo and steps. It 100% helped track down both ownership as well as easy way to validate the fix.

**Comment by HannesWell** [comment]
Thank you for working on this issue.

> Off topic - As you have some contacts at Microsoft, can somebody get more focus on this issue too: https://bugs.eclipse.org/bugs/show_bug.cgi?id=548443 and [microsoft/java-wdb#9](https://github.com/microsoft/java-wdb/issues/9) which has a huge performance impact on any Java program.

Did you also consider that referenced issue?

**Comment by mheiss** [comment]
I can confirm that the new insider build (Windows 11 Insider Preview Build 22610) that was released today has fixed the issue. Thanks @crutkas for fixing the issue and thanks @brunoborges for routing the issue to the team :)

**Comment by crutkas** [comment]
![RonSwansonNickOffermanGIF](https://user-images.githubusercontent.com/1462282/166078748-43deaa95-dfd7-4405-a0f5-ff7e191bee50.gif)

**Comment by mheiss** [comment]
And of course a big thanks to @SyntevoAlex who took the time to dig into and to create a sample to reproduce the issue!
