### ISSUE TITLE
API errors not reported for PR's

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#1003]
See https://github.com/eclipse-platform/eclipse.platform.swt/pull/1002.

All PR validation checks are green, but the PR has API errors.

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/964108/c02e5f24-faf3-4ad2-97f3-c115a112952e)

It must be recent regression with the build validation, something like https://github.com/eclipse-platform/eclipse.platform.swt/pull/988 could be related, but I haven't checked when it started to fail.

We must fix that ASAP, otherwise we might blindly merge some broken API...

**Comment by iloveeclipse** [comment]
@HannesWell : could you please check?

**Comment by laeubi** [comment]
> It must be recent regression with the build validation, something like https://github.com/eclipse-platform/eclipse.platform.swt/pull/988 could be related, but I haven't checked when it started to fail.

As far as I know SWT was never API checked (@akurtakov might can confirm) if you look at the build scripts as the `-Papi-check` profile is not active on Jenkins pipeline. Even if I go back 2 years I can't find any sign for this profile to being active any time: https://github.com/eclipse-platform/eclipse.platform.swt/blob/4fc9d68c6f54aba4cb0899a10723e4d01bea70c5/Jenkinsfile

**Comment by HannesWell** [comment]
> API checks for swt are simply too hard to setup for console build . We have always relied on committers checking it in the workspace as there are even 3 different impl. for pretty much everything and one can break the API of only one of them.

With the recent build rework, i.e. that El all bundles are built together, I can try to simply API check each fragment individually.
