### ISSUE TITLE
[help wanted][win32] SWT Support for Windows on ARM

### ISSUE THREAD

**Issue by kwin** [eclipse-platform/eclipse.platform.swt#1019]
As there is now also Windows for ARM and the necessary tooling in place (https://learn.microsoft.com/en-us/windows/arm/overview) it would be nice to provide SWT for Windows ARM as well

**Comment by jukzi** [comment]
Please provide PR ,Hardware for running tests, people that for maintance ...

**Comment by merks** [comment]
Just asking isn’t going to make it happed as is the case for the installer

https://github.com/eclipse-oomph/oomph/issues/63

Note that an equinox launcher is needed too.

**Comment by kwin** [comment]
Usually in open source you also track interest in features via issues. That allows other users to vote and by that gain some insights on importance of features. Obviously raising a feature request does not mean it will ever be implemented. Still this kind of transparency doesn’t hurt IMHO.

**Comment by jukzi** [comment]
Closing as not planned.

**Comment by merks** [comment]
Note that I asked for more transparency here but did not get a response:

https://github.com/eclipse-oomph/oomph/issues/63#issuecomment-1919808597

Transparency normally goes both ways.  There was talking of linking issues, but I see no equinox issue and I know of no adoptium issue.

**Comment by kwin** [comment]
> but I see no equinox issue and I know of no adoptium issue.

This is not a prerequisite for this issue AFAIK, but for Adoptium there is https://github.com/adoptium/adoptium-support/issues/616 (also mentioned in https://github.com/eclipse-oomph/oomph/issues/63). Feel free to raise one for Equinox, I wasn't aware that this requires/embeds native parts.

**Comment by laeubi** [comment]
Here is the github issue:
- https://github.com/actions/runner-images/issues/768

**Comment by fipro78** [comment]
Just in case, there was already such a request at the platform: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/597

Only to add the reference, as there was already discussions on this.

**Comment by jukzi** [comment]
that issue was already closed as not planned too, so please stop spamming new issues without solving the resource issue.

**Comment by laeubi** [comment]
@jukzi I don't see that it hurts to have such issue instead of having this came up multiple times, an open issue does not cost us a thing but can help to get others aware that we need help here.

**Comment by merks** [comment]
> > but I see no equinox issue and I know of no adoptium issue.
> 
> This is not a prerequisite for this issue AFAIK, but for Adoptium there is [adoptium/adoptium-support#616](https://github.com/adoptium/adoptium-support/issues/616) (also mentioned in [eclipse-oomph/oomph#63](https://github.com/eclipse-oomph/oomph/issues/63)). Feel free to raise one for Equinox, I wasn't aware that this requires/embeds native parts.

Well, you seem to want an installer too, and there won't be one without a launcher.  Personally I'm just not convinced in the need nor value for such open wish list items mostly so you can personally track things from afar.   These lists are also our project issue lists (SWT has hundreds of issues) and when we don't plan something **and** you don't plan something, then there is no plan.  Furthermore, while we might be idealistic and think/home/believe/wish that a helpwanted will attract help, this is a seriously deep and challenging problem that will not be helped by only some well-intended users.  It will only be helped with also  some involvement from an organization with deeper pockets (hardware), and, once completed it will have a maintenance/testing burden across many projects.  Yes, one more issue doesn't turn overall, but when you say that 1000 times, it becomes less true.

**Comment by laeubi** [comment]
@jonahgraham can you please bring up this topic on the Eclipse IDE WG, it seems one can buy virtual ARM hardware on Azure: https://learn.microsoft.com/en-us/windows/arm/create-arm-vm
I think if we just have one machine this would be enough for initial work on this and users would probably love to use Eclipse natively without emulation....

**Comment by mickaelistria** [comment]
> Pointless to have a wish list as long as no big player offers the required funding.

Keeping such issues temporarily open is one way of fishing new contributors and demonstrate project openness. We must keep in mind that the resources of the project in the future are not the ones of the present (and it must be one of the goal of the community to constantly grow with new contributors and more resources). So while we cannot achieve it today, and while no-one in the *current* community plans to work on it, the report can still be welcome, hoping it can attract some more contributors to care about it in a near future.
If not activity takes place on this ticket for some time, then we can close it like we didi https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/597 when we have a need to cleanup the tracker. But in the meantime, keeping it open is slightly more likely to provide good outcome than closing it.

**Comment by hmartinez82** [comment]
I have a Windows Devkit where I can help if a VM to run CI  builds is required. I just need instructions on how to build SWT even locally on x64 first. (I'm not a Java dev :( )

**Comment by laeubi** [comment]
@hmartinez82 great to hear you want help out, to contribute a runner you need to open a ticket on the helpdesk here is an example:
- https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1110

there you should note that you want your runner be added to the SWT Jenkins:
- https://ci.eclipse.org/releng/job/eclipse.platform.swt/

the IT team will then ask you for additional details in my case it was

- server name
- server description (e.g. OS, arch, etc)
- server IP
- user name (e.g. jenkins)

Additionally it would be good to mention how many concurrent build should be allowed on this node, you maybe also want to take a look here to get some idea what needs to be setup:
https://www.jenkins.io/doc/book/managing/nodes/#installing-a-jenkins-agent-on-windows

> At least for a few months until you guys get a permanent one from ARM (they are donating hardware for projects trying to be ported).

If you have further information please share them here, or you can even mention them in the help-desk so the IT team probably can take the necessary actions!

**Comment by laeubi** [comment]
>  I just need instructions on how to build SWT even locally on x64 first. (I'm not a Java dev 😓)

@chirontt seems to have things already setup so he could probably help here.

@chirontt would you mind to open a PR with your changes to the SWT repository? Then @hmartinez82 could checkout your PR and additionally we can test if the provided build note actually works and it seems logically to start with SWT.

**Comment by chirontt** [comment]
PR submitted: eclipse-platform/eclipse.platform.swt/#1045

@SyntevoAlex @hmartinez82 please review it and provide comments, especially about the cross-compiling, thanks. Once the PR is accepted, please create and check in the `swt*.dll` files for WoA to the repo, and I'll submit the 2nd part for the `org.eclipse.swt.win32.win32.aarch64` binaries module.

As @merks mentioned, equinox launchers for Windows Arm64 need also be compiled, and I'll submit a PR for it soon (to the equinox project.)

**Comment by hmartinez82** [comment]
@laeubi Ok. I'm creating and issue like https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1110 , but what should I type in the Server Name. I thought that this is something you provide to me :)

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4276

**Comment by iloveeclipse** [comment]
Please rebase and check if any version updates are needed in build files first for 4.32.

**Comment by fedejeanne** [comment]
@laeubi should this issue be unpinned?
