### ISSUE TITLE
Some of the browser test fail on different platforms

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.swt#103]
I enabled the execution of tests on the[ three "latest" platforms of github](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources):

- **Windows:** windows-2022
- **Linux**: ubuntu-20.04
- **Mac**: macos-11

Unfortunately some of the browser tests fail on these

https://github.com/eclipse-platform/eclipse.platform.swt/runs/6346732956

**Comment by akurtakov** [comment]
I'm aware of 2 browser test failures on Linux which you can see at https://download.eclipse.org/eclipse/downloads/drops4/I20220508-1800/testResults.php "swt.tests". Unfortunately never managed to find what's behind them when I looked. Hopefully will have some more time for this for this release.

**Comment by laeubi** [comment]
> Unfortunately never managed to find what's behind them when I looked. Hopefully will have some more time for this for this release.

No problem, now they are more prominent there might be more interest in fixing them :-)

**Comment by laeubi** [comment]
by the way do I get the output from the page right that we currently do not execute tests on windows?

**Comment by akurtakov** [comment]
No, it means tests are still running for windows https://ci.eclipse.org/releng/job/ep424I-unit-win32-java11/ . I really can't tell you more but these are usually the slowest to run - quite likely as this is (shared?) VM with not enough power.

**Comment by laeubi** [comment]
I think it would be interesting what the VM uses as windows OS, github offers

- windows-2019
- windows-2022

I could also enable windows-2019 if it helps?

Beside that I could fix 3/4 failing windows tests the last one is failing due it seems the browser is adding some more content and returning the live dom here, the tests itself seem a bit prone to changes in the sense of equal as they assume to get 'the same' html as the user provided back but obviously the same could be represented in many different ways in html in terms of case and additional white-spaces or even style attribute formatting.

So from the code perspective I think one either don't need to assume that one gets the html back that was set or we simply store the last text (what might then be outdated) or one would probably need more sophisticated comparison like https://jsoup.org/

**Comment by laeubi** [comment]
It seem to only affect windows now for example here:
- https://github.com/eclipse-platform/eclipse.platform.swt/runs/12839370623

**Comment by vogella** [comment]
cc @HeikoKlare who,I think I saw such a comment today,  indicated that he is interested in improving tests in SWT.
