### ISSUE TITLE
test_setFocus (org.eclipse.swt.tests.junit.Test_org_eclipse_swt_custom_CCombo) is flapping

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.swt#105]
I recently see this test suceed/fail without any code changes. trigger a new build fixes the test-failure then.

**Comment by fedejeanne** [comment]
Do you have any stack trace to help finding the issue? I just ran the whole class 100x using [this trick](https://stackoverflow.com/a/1493121) and the test doesn't fail.

**Comment by akurtakov** [comment]
I haven't seen the failure in long time.
