### ISSUE TITLE
DirectoryDialog: Right click on the Desktop folder inside file selection dialog and close the file selection dialog with title bar 'X' button makes the swt application non responsive.

### ISSUE THREAD

**Issue by raghucssit** [eclipse-platform/eclipse.platform.swt#1062]
**Right click on the Desktop folder inside File selection dialog and close the File selection dialog with Title Bar 'X' icon makes the swt application non responsive**

**To Reproduce**
Import the attached project and launch the sample swt application.
[directory-dialog-issue.zip](https://github.com/eclipse-platform/eclipse.platform.swt/files/14384161/directory-dialog-issue.zip)
Click browse to launch directory selection dialog. Inside file choose dialog 'Right click' on Desktop folder which is shown on left panel.
Close the File selection dialog with TitleBar 'X' button.
Any further SWT events are useless and SWT application become non responsive. Killing is the only solution.

Event from Display is sent to `GTK3.gtk_main_do_event (event)` but it never calls back `Display#windowProc (long handle, long user_data);`

**Expected behavior**
SWT application should process further events.

**Screenshots**
Please see below videos:
Red Hat Enterprise Linux Workstation release 7.9

https://github.com/eclipse-platform/eclipse.platform.swt/assets/10301131/614d2a07-d809-4c99-b344-7ea4a03cb504
 
Red Hat Enterprise Linux release 9.2

https://github.com/eclipse-platform/eclipse.platform.swt/assets/10301131/5d7f6c73-1c8d-43c6-ac34-4babb0838960

**Environment:**
It is obsorved on Red Hat Enterprise Linux Workstation release 7.9 (Maipo) and Red Hat Enterprise Linux release 9.2 (Plow)
 
**Version since**
 Eclipse versions Version: 2024-03 (4.31)
Build id: I20240215-1800
and
Version: 2023-12 (4.30.0)
Build id: 20231201-2043

GTK versions:
GTK.Version: 3.22.30 and GTK.Version: 3.24.31

**Workaround (or) Additional context**
There is no workaround. Need to kill swt application.

More Detailed Steps:
1. In the Directory Selection Dialog. Select Desktop folder in the left panel.
2. Then right click on the same Desktop folder. A Context Menu should appear.
3. Move away the cursor. And then hover the cursor on same Desktop icon. A Tooltip must be shown.(All the time context menu must be there)
4. Now Close the Directory Selection Dialog with Close Icon of TitleBar. It closes successfully.
5. Now If you click any icon on SWT Application, It is unresponsive. Only option is to Kill it.

![dir-dlg-issue](https://github.com/eclipse-platform/eclipse.platform.swt/assets/10301131/9aca64f3-21d1-459c-883b-5fc0571066bf)

https://github.com/eclipse-platform/eclipse.platform.swt/assets/10301131/b367dec7-450c-46f2-be72-0baaafb063af

**Comment by raghucssit** [comment]
@iloveeclipse FYI.

**Comment by SyntevoAlex** [comment]
Yes, I think so. Hopefully within a couple weeks.

**Comment by SyntevoAlex** [comment]
My colleague wasn't able to reproduce and told me to skip this issue.

**Comment by deepika-u** [comment]
Does this mean this problem doesnt exist anymore now on the mentioned linux version? If yes can this be closed? Sorry if i didnt understand it proper.
@raghucssit : can you please confirm.

**Comment by raghucssit** [comment]
@SyntevoAlex @deepika-u 
I can still reproduce this on latest integration build
Version: 2024-06 (4.32)
Build id: I20240323-1800
I have added more detailed steps to reproduce and a video to reproduce.

**Comment by deepika-u** [comment]
> @SyntevoAlex @deepika-u I can still reproduce this on latest integration build Version: 2024-06 (4.32) Build id: I20240323-1800 I have added more detailed steps to reproduce and a video to reproduce.

Thanks alot, this confirms that this issue is still valid. Thanks for the info.

**Comment by raghucssit** [comment]
@SyntevoAlex Our users have found this issue again.
Please check the issue again with latest reproducible data. It will be very helpful for us.

**Comment by SyntevoAlex** [comment]
Sorry, I was instructed to not work on this.

**Comment by iloveeclipse** [comment]
OK, after poking around I believe I've found the problem.

We miss `OS.g_object_unref(handle);` call on the opened dialog as suggested in https://docs.gtk.org/gtk3/class.FileChooserNative.html

I will provide a patch in a moment. We have same issue with DirectoryDialog.

**Comment by iloveeclipse** [comment]
Verified works on I20240512-1800.
