### ISSUE TITLE
Regression in "Correct GC offset calculation #788"

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.swt#1067]
cc @HeikoKlare

[This commit](https://github.com/eclipse-platform/eclipse.platform.swt/commit/657fffb389fdb781db1d18331a31cd104858c4e5) causes a regression on Mac's [ColorSelector](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.jface/src/org/eclipse/jface/preference/ColorSelector.java) outline:

On Mac go to Eclipse Preferences, Run/Debug pane.

Before:

<img width="315" alt="Screenshot 2024-02-27 at 12 37 04" src="https://github.com/eclipse-platform/eclipse.platform.swt/assets/600504/66686c1c-8897-4b02-a4cd-958d90d9c94d">

After:

<img width="302" alt="Screenshot 2024-02-27 at 12 37 40" src="https://github.com/eclipse-platform/eclipse.platform.swt/assets/600504/bf7237c7-a874-462a-8608-67d58b51c167">

I don't know if there are regressions elsewhere, I only just found this now.

**Comment by Phillipus** [comment]
Snippet to reproduce:

```java
import org.eclipse.swt.SWT;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.graphics.GC;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.graphics.ImageData;
import org.eclipse.swt.graphics.ImageDataProvider;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class GCTest {

    public static void main(String[] args) {
        final Display display = new Display();

        final Shell shell = new Shell(display);
        shell.setText("GC");
        shell.setLayout(new FillLayout());
        
        Image image = new Image(display, new ImageDataProvider() {
            @Override
            public ImageData getImageData(int zoom) {
                Image image = new Image(display, 60, 60);
                
                GC gc = new GC(image);
                gc.setForeground(display.getSystemColor(SWT.COLOR_WIDGET_BORDER));
                gc.setBackground(new Color(255, 255, 255));
                gc.fillRectangle(image.getBounds());
                gc.setLineWidth(2);
                gc.drawRectangle(image.getBounds());
                gc.dispose();

                ImageData data = image.getImageData(zoom);
                image.dispose();
                
                return data;
            }
        });
        
        shell.addPaintListener(e -> {
            e.gc.drawImage(image, 10, 10);
        });

        shell.setSize(shell.computeSize(120, 120));
        shell.open();

        while(!shell.isDisposed()) {
            if(!display.readAndDispatch()) {
                display.sleep();
            }
        }

        display.dispose();
    }
}
```

**Comment by Phillipus** [comment]
Before https://github.com/eclipse-platform/eclipse.platform.swt/commit/657fffb389fdb781db1d18331a31cd104858c4e5:

<img width="232" alt="Screenshot 2024-02-27 at 13 02 57" src="https://github.com/eclipse-platform/eclipse.platform.swt/assets/600504/f2ef014a-ed40-43d2-8f43-c2ffcc75b261">

After https://github.com/eclipse-platform/eclipse.platform.swt/commit/657fffb389fdb781db1d18331a31cd104858c4e5

<img width="232" alt="Screenshot 2024-02-27 at 13 02 28" src="https://github.com/eclipse-platform/eclipse.platform.swt/assets/600504/957d21ff-30d2-40df-ac2d-ff14dc43663d">

**Comment by Phillipus** [comment]
Actually, this creates a big problem for our RCP app, Archi (which does a lot of diagram drawing using GEF/Draw2d). I was hoping to target 4.31 for our next version, but some rectangular figures are clipped on Mac. This might affect other apps and frameworks that draw figures on Mac.

**Comment by HeikoKlare** [comment]
Thanks for finding and sharing that regression, @Phillipus! The snippet looks good on Windows, which is why at least I did not face that issue yet:
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/755472/38e6f29f-427c-42a8-8103-69a2c974f730)

I will have a look at the problem on Mac tomorrow and see whether I find something to easily and safely fix it for the current release. Otherwise, I would propose to revert the change and I will work on a fix to be provided as soon as possible for 2024-06. So in any case, I will provide a PR to fix the issue tomorrow (or in case tomorrow is too late, feel free to already revert the commit before that).

**Comment by Phillipus** [comment]
Is it too late to revert this for 4.31? cc @iloveeclipse @merks

**Comment by HeikoKlare** [comment]
> Is it too late to revert this for 4.31?

Just as an additional information: the fix is for a bug that has been there for ~ 20 years, so the risk to break something by reverting the fix would be really low.

**Comment by merks** [comment]
I think the final build is scheduled for 6:00 pm est tomorrow.

**Comment by Phillipus** [comment]
PR for revert at #1068 - is it too late for 4.31?

**Comment by iloveeclipse** [comment]
I can confirm that I see regression on Linux (same as on Mac) with the snippet and thet revert PR fixes the problem.

**Comment by Phillipus** [comment]
I think there will be other places where https://github.com/eclipse-platform/eclipse.platform.swt/commit/657fffb389fdb781db1d18331a31cd104858c4e5 might manifest. I'm seeing different rectangle positions in our GEF/Draw2d based RCP application.

**Comment by Phillipus** [comment]
> I can confirm that I see regression on Linux (same as on Mac) with the snippet and thet revert PR fixes the problem.

Yes, here's the buttons in Preferences, Run/Debug on Linux:

![Screenshot from 2024-02-27 15-58-57](https://github.com/eclipse-platform/eclipse.platform.swt/assets/600504/ec228e13-59bc-417d-a75a-860f47f8be06)

**Comment by merks** [comment]
@HeikoKlare 

I saw you mentioned investigating a fix but also you mentioned that a revert if very low risk, so I wasn't sure which way you were leaning here...

**Comment by Phillipus** [comment]
@HeikoKlare There seems to be some underlying issues with drawing rectangles anyway. The snippet I provided above is based on the [ColorSelector](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.jface/src/org/eclipse/jface/preference/ColorSelector.java) class which actually isn't correct because it uses a line width of 2 but doesn't compensate for that when drawing the rectangle.

Here's a simpler snippet:

```java
import org.eclipse.swt.graphics.GC;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.graphics.ImageData;
import org.eclipse.swt.graphics.ImageDataProvider;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class GCTest {

    public static void main(String[] args) {
        final Display display = new Display();

        final Shell shell = new Shell(display);
        shell.setText("GC");
        shell.setLayout(new FillLayout());
        
        Image image = new Image(display, new ImageDataProvider() {
            @Override
            public ImageData getImageData(int zoom) {
                Image image = new Image(display, 60, 60);
                
                GC gc = new GC(image);
                gc.setLineWidth(2);
                gc.drawRectangle(1, 1, 58, 58);
                gc.dispose();
                
                ImageData data = image.getImageData(zoom);
                image.dispose();
                
                return data;
            }
        });
        
        shell.addPaintListener(e -> {
            e.gc.drawImage(image, 10, 10);
        });

        shell.setSize(shell.computeSize(120, 120));
        shell.open();

        while(!shell.isDisposed()) {
            if(!display.readAndDispatch()) {
                display.sleep();
            }
        }

        display.dispose();
    }
}
```

To compensate for line width of 2 we do this:

```java
gc.drawRectangle(1, 1, 58, 58);
```

Here's it should look prior to https://github.com/eclipse-platform/eclipse.platform.swt/commit/657fffb389fdb781db1d18331a31cd104858c4e5

<img width="232" alt="Screenshot 2024-02-27 at 16 10 35" src="https://github.com/eclipse-platform/eclipse.platform.swt/assets/600504/23b68bb0-a447-4880-8472-300682095255">

And here's how it looks after:

<img width="232" alt="Screenshot 2024-02-27 at 16 10 59" src="https://github.com/eclipse-platform/eclipse.platform.swt/assets/600504/7c57b1e3-0c49-4b1c-9e21-c7192f9ed66b">

https://github.com/eclipse-platform/eclipse.platform.swt/commit/657fffb389fdb781db1d18331a31cd104858c4e5 seems to shift things by a pixel.

**Comment by Phillipus** [comment]
This has been reverted and merged now.

@HeikoKlare Thanks for your initial work on this in https://github.com/eclipse-platform/eclipse.platform.swt/issues/788 It's a pity that it caused a regression. But I think there are underlying problems in SWT anyway. And fixing those can cause unexpected changes elsewhere. Perhaps [this](https://github.com/eclipse-platform/eclipse.platform.swt/issues/304) is related, too?

I'll close this issue.

**Comment by HeikoKlare** [comment]
I think reverting is the right thing to do now, so thanks for provinding the reverting PR and merging it. I will definitely work on fixing the behavior by re-proposing an improved PR.
And also thanks for the additional pointer to different behavior between Windows and Linux. I will consider that when working on it again.
