### ISSUE TITLE
SWT AllBrowserTests aren't executed on Linux anymore

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#108]
Since I20220507-1800 we execute only a subset of SWT tests on Linux Java 17 / 18 platform - `AllBrowserTests` aren't executed anymore.

Most likely caused by changes in https://github.com/eclipse-platform/eclipse.platform.swt/pull/100. 
That was the only commit in I20220507-1800.

- Java 11 / Linux: 3983 tests: https://download.eclipse.org/eclipse/downloads/drops4/I20220509-1800/testresults/html/org.eclipse.swt.tests_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html
- Java 17 / Linux: 3802 tests https://download.eclipse.org/eclipse/downloads/drops4/I20220509-1800/testresults/html/org.eclipse.swt.tests_ep424I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

**Comment by laeubi** [comment]
@iloveeclipse what make you think so? the referenced commit adds a new target to the build.xml but do not change existing ones...

**Comment by iloveeclipse** [comment]
> what make you think so?

See bug description: this was the only commit went into I20220507-1800

**Comment by laeubi** [comment]
> > what make you think so?
> 
> See bug description: this was the only commit went into I20220507-1800

Then I think we need some build expert here, I have no clue how this could cause anything regarding Java 11 versus Java 17, I could understand if it probably won't execute on *both* ...

**Comment by laeubi** [comment]
@iloveeclipse I have enhanced the github action to use Java 17 as well. The only thin I can think of is, that there is some kind of missing build item, as the change has fixed that the *last* artifact build was used it now uses the appropriate one for the native platform. Why this makes a difference in the java platform I have no idea... who could have better knowledge of how all these build scripts work?

**Comment by iloveeclipse** [comment]
What is interesting: 

- in https://download.eclipse.org/eclipse/downloads/drops4/I20220508-1800/testResults.php browser tests were executed **only on two builds running with Java 11** - Windows & Linux.
- in https://download.eclipse.org/eclipse/downloads/drops4/I20220507-1800/testResults.php browser tests were executed **only on Java 11 - Windows**, Linux Java 11 build had no browser tests executed but lot of DNF fails in other test suites.
- since **4.21** browser tests **are not executed on Mac**.
- but Mac browser tests are back since https://download.eclipse.org/eclipse/downloads/drops4/I20220509-1800/testresults/html/org.eclipse.swt.tests_ep424I-unit-mac64-java17_macosx.cocoa.x86_64_17.html  

This is insane.

@sravanlakkimsetti : are you aware if we changed anything in the test system environment since I20220507-1800? New OS images that misses webkit on Linux and some?

**Comment by mickaelistria** [comment]
Log is available at https://download.eclipse.org/eclipse/downloads/drops4/I20220509-1800/logs.php#console
Doing a search for AllBrowserTests shows

```
java-test:
     [echo] Running org.eclipse.swt.tests.junit.AllBrowserTests. Result file: /home/jenkins/agent/workspace/ep424I-unit-cen64-gtk3-java17/workarea/I20220509-1800/eclipse-testing/results/ep424I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17/org.eclipse.swt.tests.junit.AllBrowserTests.xml
     [echo] timout property: 900000
     [echo] frameworkvmargs:  -Xms256m -Xmx2048m  -Djava.io.tmpdir=/home/jenkins/agent/workspace/ep424I-unit-cen64-gtk3-java17/tmp
     [echo] vmargs:
     [echo] extraVMargs:
     [echo] frameworkperfargs:
     [echo] crash loglocationarg (if any): ${loglocationarg}
     [echo] crash loglocation (if not default):
     [java] INFO: timeoutScreenOutputDir: /home/jenkins/agent/workspace/ep424I-unit-cen64-gtk3-java17/workarea/I20220509-1800/eclipse-testing/results/ep424I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17/timeoutScreens
     [java] INFO: timeout: 900000
     [java] SWT SessionManagerDBus: Failed to connect to org.gnome.SessionManager: Error spawning command line “dbus-launch --autolaunch=f13500c1cc0b0674acbe12626276dd02 --binary-syntax --close-stderr”: Child process exited with code 1
     [java] SWT SessionManagerDBus: Failed to connect to org.xfce.SessionManager: Error spawning command line “dbus-launch --autolaunch=f13500c1cc0b0674acbe12626276dd02 --binary-syntax --close-stderr”: Child process exited with code 1
     [java] Could not determine the accessibility bus address
     [java]
     [java] (process:3695): dconf-CRITICAL **: 00:42:27.392: unable to create directory '/home/vnc/.cache/dconf': Permission denied.  dconf will not work properly.
     [java]
     [java] (process:3695): dconf-CRITICAL **: 00:42:27.392: unable to create directory '/home/vnc/.cache/dconf': Permission denied.  dconf will not work properly.
     [java]
     [java] (process:3695): dconf-CRITICAL **: 00:42:27.394: unable to create directory '/home/vnc/.cache/dconf': Permission denied.  dconf will not work properly.
     [java]
     [java] (process:3695): dconf-CRITICAL **: 00:42:27.394: unable to create directory '/home/vnc/.cache/dconf': Permission denied.  dconf will not work properly.
     [java]
     [java] (process:3695): dconf-CRITICAL **: 00:42:27.394: unable to create directory '/home/vnc/.cache/dconf': Permission denied.  dconf will not work properly.
     [java]
     [java] (process:3695): dconf-CRITICAL **: 00:42:27.401: unable to create directory '/home/vnc/.cache/dconf': Permission denied.  dconf will not work properly.
     [java]
     [java] (process:3695): dconf-CRITICAL **: 00:42:27.401: unable to create directory '/home/vnc/.cache/dconf': Permission denied.  dconf will not work properly.
     [java]
     [java] (process:3695): dconf-CRITICAL **: 00:42:27.401: unable to create directory '/home/vnc/.cache/dconf': Permission denied.  dconf will not work properly.
     [java]
     [java] (process:3695): dconf-CRITICAL **: 00:42:27.401: unable to create directory '/home/vnc/.cache/dconf': Permission denied.  dconf will not work properly.
     [java]
     [java] (process:3695): dconf-CRITICAL **: 00:42:27.401: unable to create directory '/home/vnc/.cache/dconf': Permission denied.  dconf will not work properly.
     [java]
     [java] ** (SWT:3653): WARNING **: 00:42:47.887: WebKitWebView returned by WebKitWebView::create signal was not created with the related WebKitWebView
     [java]
     [java] ** (SWT:3653): ERROR **: 00:43:48.776: Unable to spawn a new child process: Failed to fork (Resource temporarily unavailable)
     [java] Java Result: 133
```

Maybe something did change on the environment (eg docker images, webkit) between 20220506 and 20220507 that explains this error? Or maybe another change somewhere alters the environment in a breaking way for those tests?

**Comment by iloveeclipse** [comment]
I've reported https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1274

**Comment by laeubi** [comment]
I have now enhanced the GH action and it executes on all platforms for J11+J17:

https://github.com/eclipse-platform/eclipse.platform.swt/runs/6365780221

You can se this by the "2 out of 6" (three platforms x two java versions = 6 runs).

**Comment by iloveeclipse** [comment]
Thanks.

**Comment by sravanlakkimsetti** [comment]
> @sravanlakkimsetti : are you aware if we changed anything in the test system environment since I20220507-1800? New OS images that misses webkit on Linux?

I reviewed the logs there is a docker build on May 7 at 4:47 PM (log: https://ci.eclipse.org/releng/view/Miscellaneous/job/Build-Docker-images/363/artifact/eclipse.platform.releng.aggregator/cje-production/dockerfiles/centos8.log) after that the docker build ran only today
here is the previous log https://ci.eclipse.org/releng/view/Miscellaneous/job/Build-Docker-images/362/artifact/eclipse.platform.releng.aggregator/cje-production/dockerfiles/centos8.log

the docker file we use is https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/cje-production/dockerfiles/centos-gtk3-metacity/8-gtk3/Dockerfile

From the log provided by @mickaelistria I see that dconf is trying to create a cache file in $HOME. Which will fail because in our environment, the user name used will be completely random and they don't have write access to the folders on the docker image. All the write operations needs to be on the $WORKSPACE. 

One way to fix this add a docker instruction to create .cache with 777 permissions $HOME. 

I did a quick glance between the logs. and I see there is an update to webkit2gtk3 package. Would this cause any trouble like this?

**Comment by iloveeclipse** [comment]
> I see there is an update to webkit2gtk3 package. Would this cause any trouble like this?

For sure. Browser **is** the webkit on Linux

**Comment by sravanlakkimsetti** [comment]
Here are the docker build logs

[workingcentos8.log.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/8660612/workingcentos8.log.txt)
[notworkingcentos8.log.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/8660614/notworkingcentos8.log.txt)

One option is to create a .cache in /home/vnc with 777 permissions. But this should be last option.

**Comment by mickaelistria** [comment]
> One option is to create a .cache in /home/vnc with 777 permissions. But this should be last option.

The overall issue seems to be that testuser doesn't have permissions to modify its `.vnc` folder. Some alternative could to either create the .vnc folder *after* we switch to `USER 10001` (so the folder is used by `testuser`), or we can run a `chown -R testuser ${HOME}/,vnc` before switching user.

**Comment by laeubi** [comment]
The problem seem more that there is a  `vnc` and a `testuser` user and the first is not allowed to access its home directory (maybe it does not exits at all?)

> unable to create directory '**/home/vnc/**.cache/dconf': Permission denied.

but strange that this only happen on one java version and not for all tests...?

**Comment by iloveeclipse** [comment]
> but strange that this only happen on one java version and not for all tests...?

The only explanation I have is that Java 17+ is more sensible here? Or it's image used is configured differently compared to Java 11 image and has different webkit / other GTK libraries.

**Comment by sravanlakkimsetti** [comment]
> The overall issue seems to be that testuser doesn't have permissions to modify its `.vnc` folder.

Though we do have USER 10001 but in jenkins environment that is the not the user id used in the job run. I find 1002310000 as the user id during the job run

**Comment by sravanlakkimsetti** [comment]
> > but strange that this only happen on one java version and not for all tests...?
> 
> The only explanation I have is that Java 17+ is more sensible here? Or it's image used is configured differently compared to Java 11 image and has different webkit / other GTK libraries.

I see the same problem in all java variants. Also we use same docker image for this test

**Comment by iloveeclipse** [comment]
Just an observation: `Java Result: 133` is reported for Java 17+ tests, `Java Result: 1` for Java 11 tests.

**Comment by mickaelistria** [comment]
@sravanlakkimsetti according to https://docs.openshift.com/container-platform/3.9/creating_images/guidelines.html#use-uid , the openshift user is part of the root group and `RUN chgrp -R 0 ${HOME} && chmod -R g=u ${HOME}` should do the trick of allowing Jenkins user to touch the /home/vnc folder. Is it good enough?

**Comment by mickaelistria** [comment]
I opened https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/259 which might be a valid fix. However I'm a bit clueless about an efficient way to try it.

**Comment by sravanlakkimsetti** [comment]
I started a test run with new docker image:
Log: https://ci.eclipse.org/releng/view/Smoke%20Tests/job/ep-smoke-test-centos8/263/console

**Comment by sravanlakkimsetti** [comment]
Still a problem 
     [java] ** (SWT:575): WARNING **: 05:16:03.656: WebKitWebView returned by WebKitWebView::create signal was not created with the related WebKitWebView
     [java] 
     [java] ** (SWT:575): ERROR **: 05:16:59.020: Unable to spawn a new child process: Failed to fork (Resource temporarily unavailable)
     [java] Java Result: 133

**Comment by iloveeclipse** [comment]
Anyone knows difference between webkit2gtk3 2.34.6-1.el8 and 2.36.1-1.el8?
Is that new version compatible at all with our SWT?

**Comment by iloveeclipse** [comment]
This reminds me on https://bugs.eclipse.org/bugs/show_bug.cgi?id=569878
```** (SWT:575): ERROR **: 05:16:59.020: Unable to spawn a new child process: Failed to fork (Resource temporarily unavailable)```

Can we pin in docker file some older webkit version to see with which one the trouble begins?

**Comment by laeubi** [comment]
If one likes to play around a bit with ubuntu the Github action is configured here:

https://github.com/eclipse-platform/eclipse.platform.swt/blob/d366edafd0415a82df6c869bf79293e3dc6892b0/.github/workflows/maven.yml#L33-L35

you can issue more/other commands and install stuff there to get older/newer versions probably.

**Comment by akurtakov** [comment]
Pinning old version will not help users that have webkitgtk updated by their OS.

**Comment by iloveeclipse** [comment]
It would help to understand where the regression happened, so we can report it to webkit. Who knkws how long they will need for a fix (or to advice how applications are supposed to be changed to be compatible with whatever they changed).

**Comment by laeubi** [comment]
By the way I noticed that the CI is executing the tests with `forkCount=0` what means that tests execute inside the same VM as the build, this might produce some problems. For the GH action I used `forkCount=1` so the tests are running in a separate process. Maybe this is something to try out here as well.

**Comment by akurtakov** [comment]
> By the way I noticed that the CI is executing the tests with `forkCount=0` what means that tests execute inside the same VM as the build, this might produce some problems. For the GH action I used `forkCount=1` so the tests are running in a separate process. Maybe this is something to try out here as well.

Please do. I don't think it can create extra troubles.

**Comment by sravanlakkimsetti** [comment]
I am running the test on ubuntu 22.04 https://ci.eclipse.org/releng/view/Smoke%20Tests/job/ep-smoke-test-ubuntu22/69/ Lets see if this works

**Comment by laeubi** [comment]
> Please do. I don't think it can create extra troubles.

The test seems to be executed by some ant and shell magic, so I can't really help here :-\

**Comment by sravanlakkimsetti** [comment]
I added -DforkCount=1 and started a test run https://ci.eclipse.org/releng/view/Smoke%20Tests/job/ep-smoke-test-centos8/264/

**Comment by akurtakov** [comment]
> I am running the test on ubuntu 22.04 https://ci.eclipse.org/releng/view/Smoke%20Tests/job/ep-smoke-test-ubuntu22/69/ Lets see if this works

Ubuntu 22.04 seems to have bigger issue with webkit even epiphany crashing as per https://github.com/eclipse-platform/eclipse.platform.swt/issues/107 .

**Comment by laeubi** [comment]
I spinned a GH action build with Ubuntu 22.04 here: https://github.com/eclipse-platform/eclipse.platform.swt/pull/117

**Comment by sravanlakkimsetti** [comment]
Still same problem on centos added forkCount=1
```
     [echo] Running org.eclipse.swt.tests.junit.AllBrowserTests. Result file: /home/jenkins/agent/workspace/ep-smoke-test-centos8/workarea/I20220510-1800/eclipse-testing/results/ep-smoke-test-centos8_linux.gtk.x86_64_18/org.eclipse.swt.tests.junit.AllBrowserTests.xml
     [echo] timout property: 900000
     [echo] frameworkvmargs:  -Xms256m -Xmx2048m  -Djava.io.tmpdir=/home/jenkins/agent/workspace/ep-smoke-test-centos8/tmp -Djava.security.manager=allow -DforkCount=1
     [echo] vmargs: 
     [echo] extraVMargs: 
     [echo] frameworkperfargs: 
     [echo] crash loglocationarg (if any): ${loglocationarg}
     [echo] crash loglocation (if not default): 
     [java] INFO: timeoutScreenOutputDir: /home/jenkins/agent/workspace/ep-smoke-test-centos8/workarea/I20220510-1800/eclipse-testing/results/ep-smoke-test-centos8_linux.gtk.x86_64_18/timeoutScreens
     [java] INFO: timeout: 900000
     [java] SWT SessionManagerDBus: Failed to connect to org.gnome.SessionManager: Error spawning command line â€œdbus-launch --autolaunch=1c0f201e5eb62a590a281b55627b2f6b --binary-syntax --close-stderrâ€: Child process exited with code 1
     [java] SWT SessionManagerDBus: Failed to connect to org.xfce.SessionManager: Error spawning command line â€œdbus-launch --autolaunch=1c0f201e5eb62a590a281b55627b2f6b --binary-syntax --close-stderrâ€: Child process exited with code 1
     [java] Could not determine the accessibility bus address
     [java] 
     [java] ** (SWT:588): WARNING **: 06:53:45.676: WebKitWebView returned by WebKitWebView::create signal was not created with the related WebKitWebView
     [java] 
     [java] ** (SWT:588): ERROR **: 06:54:47.889: Unable to spawn a new child process: Failed to fork (Resource temporarily unavailable)
     [java] Java Result: 133
```

**Comment by sravanlakkimsetti** [comment]
> > I am running the test on ubuntu 22.04 https://ci.eclipse.org/releng/view/Smoke%20Tests/job/ep-smoke-test-ubuntu22/69/ Lets see if this works
> 
> Ubuntu 22.04 seems to have bigger issue with webkit even epiphany crashing as per #107 .

Ubuntu report indicates process hang https://ci.eclipse.org/releng/view/Smoke%20Tests/job/ep-smoke-test-ubuntu22/69/artifact/workarea/I20220510-1800/eclipse-testing/results/consolelogs/ep-smoke-test-ubuntu22_linux.gtk.x86_64_18_consolelog.txt

**Comment by laeubi** [comment]
The GH action run is complete, beside the usual Browser failures I see no problems here:

https://github.com/eclipse-platform/eclipse.platform.swt/runs/6383167193

**Comment by sravanlakkimsetti** [comment]
Based on https://ci.eclipse.org/releng/view/Smoke%20Tests/job/ep-smoke-test-centos8/265/artifact/workarea/I20220510-1800/eclipse-testing/results/ep-smoke-test-centos8_linux.gtk.x86_64_18/org.eclipse.swt.tests.junit.AllBrowserTests.txt

The test run aborted while running Test_org_eclipse_swt_browser_Browser#test_addTraverseListenerLorg_eclipse_swt_events_TraverseListener

**Comment by mickaelistria** [comment]
> It would help to understand where the regression happened, so we can report it to webkit

I'm not sure there is a regression in webkit. On my Fedora, I'm using webkitgtk 2.36.0 and don't get any issue with Browser in Eclipse IDE: welcome page works, Browser-based hovers (eg from LSP4E) work....

**Comment by iloveeclipse** [comment]
We have browser test results for Linux/Java 11 every second build or so, and not at all on Java 17/18.

**Comment by mickaelistria** [comment]
> We have browser test results for Linux/Java 11 every second build or so

I looked at test reports and the last success for BrowserTests I saw is from I20220509-1800. Am I missing something?

**Comment by mickaelistria** [comment]
@sravanlakkimsetti Is the Docker image id used for tests logged somewhere? I'd like to make sure https://download.eclipse.org/eclipse/downloads/drops4/I20220516-0600/testresults/html/org.eclipse.swt.tests_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html and https://download.eclipse.org/eclipse/downloads/drops4/I20220516-1800/testresults/html/org.eclipse.swt.tests_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html really use the same Docker image.

**Comment by iloveeclipse** [comment]
See #152, let print environment on test start, etc.

**Comment by iloveeclipse** [comment]
Looks like JVM is unable to start new threads. There is no dump, nothing, all tests end now with following:

[Java 18](https://download.eclipse.org/eclipse/downloads/drops4/I20220517-1800/testresults/ep424I-unit-cen64-gtk3-java18_linux.gtk.x86_64_18/org.eclipse.swt.tests.junit.AllBrowserTests.txt)
```
[2022-05-18 00:18:04 +0000] org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser#test_addPaintListenerLorg_eclipse_swt_events_PaintListener()
Running Test_org_eclipse_swt_browser_Browser#test_addPaintListenerLorg_eclipse_swt_events_PaintListener
[114.823s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[114.823s][warning][os,thread] Failed to start the native thread for java.lang.Thread "Secondary finalizer"
```

[Java 17](https://download.eclipse.org/eclipse/downloads/drops4/I20220517-1800/testresults/ep424I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17/org.eclipse.swt.tests.junit.AllBrowserTests.txt)
```
[2022-05-18 00:19:51 +0000] org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser#test_addPaintListenerLorg_eclipse_swt_events_PaintListener()
Running Test_org_eclipse_swt_browser_Browser#test_addPaintListenerLorg_eclipse_swt_events_PaintListener
[122.898s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
```

[Java 11](https://download.eclipse.org/eclipse/downloads/drops4/I20220517-1800/testresults/ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11/org.eclipse.swt.tests.junit.AllBrowserTests.txt)
```
[2022-05-18 00:20:57 +0000] org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser#test_addMouseListenerLorg_eclipse_swt_events_MouseListener()
Running Test_org_eclipse_swt_browser_Browser#test_addMouseListenerLorg_eclipse_swt_events_MouseListener
[91.939s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
```

I assume we (JVM process) either leak threads, processes or file handles, so the OS doesn't allow process to start or doesn't have free handles to start a process.

I will add printout for number of running threads to the log.

@fredg02: do we have any system limits changed in the docker? Can we set / control that from the test script or see it from the environment (see linked files, they have all environment variables printed out at begin of th elog file)?

**Comment by iloveeclipse** [comment]
After `test_setVisibility_and_sizing` we start leaking 2 descriptor per test. That's the only test that doesn't properly closes the shell.

**Comment by iloveeclipse** [comment]
OK, I believe I have a fix. We seem not properly wait after shells disposal, so it looks like some GTK events aren't handled / hang in the queue and that keeps file descriptors growing  (probably because webkit spawns some processes and if the browser is not properly disposed, they stay forever).

**Comment by fredg02** [comment]
> @fredg02: do we have any system limits changed in the docker? Can we set / control that from the test script or see it from the environment (see linked files, they have all environment variables printed out at begin of th elog file)?

I'm not aware of changed system limits for the docker images. You should be able to see them with `ulimit -a`.

**Comment by iloveeclipse** [comment]
I've merged https://github.com/eclipse-platform/eclipse.platform.swt/pull/154 now, so at least **SWT** leaks should be fixed.

**BUT!**

@mickaelistria , @laeubi : I see that the test framework (tycho) itself leaks file descriptors, **one for each test**, because I don't see **original** leakage locally in the IDE.

The descriptors are counted between setup & teardown, means, they leak **after** test code is done, **inside** test framework, here is the example output:
```
### Descriptors opened BEFORE test_setUrlWithNullArg: 625
### Descriptors opened AFTER test_setUrlWithNullArg: 625
[2022-05-18 13:56:10 +0000] org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser#test_setUrl_local()
Running Test_org_eclipse_swt_browser_Browser#test_setUrl_local

### Descriptors opened BEFORE test_setUrl_local: 626

### Descriptors opened AFTER test_setUrl_local: 626
```

I assume "stdout" redirection is broken, because we see following descriptors growing (example): 

```
### Descriptors opened AFTER test_setUrl_remote: 628
Delta to previous test: 1
	socket:[2367981657]

Delta to first test: 100
	/memfd:WebKitSharedMemory (deleted)
	/tmp/stdout10025304183554339060deferred
	/tmp/stdout10101648864789820786deferred
	/tmp/stdout104424146349535352deferred
	/tmp/stdout10469890275235030494deferred
	/tmp/stdout10757497078713430677deferred
	/tmp/stdout10768413038937016760deferred

... much more from that crap...
```

**Comment by laeubi** [comment]
How do you measure the descriptors? Surefire forks one vm and reuse that (so it *might* explain the "leaked" socket) and _probably_ also created one stdout per test and do not close them before the vm exit.

There is a `<forkMode>pertest</forkMode>` setting one can use in that case ... but this will slow down things.

**Comment by iloveeclipse** [comment]
@laeubi : let continue tycho / surefire discussion on https://github.com/eclipse/tycho/issues/965

**Comment by iloveeclipse** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20220518-1100/testResults.php :

- [Java 11 log](https://download.eclipse.org/eclipse/downloads/drops4/I20220518-1100/testresults/ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11/org.eclipse.swt.tests.junit.AllBrowserTests.txt) looks good, no descriptor leaks anymore, and tests are executed.

**Comment by mickaelistria** [comment]
Many many thanks Andrey for tackling this difficult problem!
