### ISSUE TITLE
.api_description in SWT is empty in 4.31 RC2, API analysis broken

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#1093]
See https://github.com/eclipse-pde/eclipse.pde/issues/1187.
Looks like we don't properly build SWT bundles since some late 4.31 build.
The `.api_description` files are empty in SWT OS specific bundles, which breaks API analysis.

- SDK-I20240202-1800 OK (org.eclipse.swt.win32.win32.x86_64_3.125.0.v20240201-1628.jar)
- SDK-I20240209-1800 Bad (org.eclipse.swt.win32.win32.x86_64_3.125.0.v20240208-1757.jar)

This is a big problem, because we will be unable to properly analyse API for 4.32!

@laeubi , @HannesWell , @merks : can we create 4.32 RC2a?

**Comment by laeubi** [comment]
> Looks like we don't properly build SWT bundles since some late 4.31 build.
> The `.api_description` files are empty in SWT OS specific bundles, which breaks API analysis.

Why is this not discovered by I-Builds?

**Comment by merks** [comment]
You could build a repo just for use as a baseline, but rebuilding SimRel, EPP, and all that is just not realistic at this late state of the game.  I think the publishing to Maven is done already too.  Can we even do a branch build at this point?

**Comment by laeubi** [comment]
What I wonder most is why this was not discovered earlier?
Does it mean that here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/f8bde409fa0267b917464fc197e4f2a0a25366ec/eclipse-platform-parent/pom.xml#L130

it is not pointing to the "real" RC2?

**Comment by merks** [comment]
The real one is this:

https://download.eclipse.org/justj/?file=eclipse/updates/4.31/R-4.31-202402290520

But I expect they have identical content.

**Comment by merks** [comment]
Another concern I have about a respin is that it will (I assume) produce IUs and artifacts with identical version as the current ones, so there would be one variant of the artifact with API descriptions and one without, though they would look like the same artifact.  If the description-less version is already in the shared bundle pool, you'd not get a new one to be downloaded.  Also, depending on what repositories are visible, you might get either one being downloaded non-deterministically; these have been out in the wild for quite some time now, so could be in many other p2 repositories. 

This seems like a bit of a disaster.  😱  How can we do proper development with an API baseline for 4.31? 😭

**Comment by merks** [comment]
@iloveeclipse 

I think it's only the SWT bundles that are affected, right?   It seems to me we really do need some type of solution to this problem.  I don't think we need to respin SimRel or EPP, but we need something for the SWT baseline...

**Comment by laeubi** [comment]
Technically one could copy the repo, modify the jars, update the swt + fragments with a micro increment in the manifest and adjust the p2 metadata... and use that as a api-baseline repo for this release.

**Comment by merks** [comment]
Unfortunately there are includes involved that percolate up the dependencies:

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/208716/dd9f934e-9d7a-49a5-ac0f-4a931fcbe714)

I guess features are in the baseline? 

If so, I think we'd probably need to build a full repo with the smallest increments to SWT possible and use that purely for the API baseline for this release cycle (assuming that the API descriptions are 100% necessary).

**Comment by laeubi** [comment]
As far as I know only bundles are supported:

- https://github.com/eclipse-pde/eclipse.pde/issues/44

**Comment by iloveeclipse** [comment]
I wonder if we can "simply" do something like
- generate proper API description xml for 4.31 SWT
- add it to git in SWT in each SWT fragment (because I believe they have different API)
- add some build property where to look for (baseline vs git)
- modify PDE and/or Tycho to load the description file from git and not from baseline jar

**Comment by laeubi** [comment]
Honestly this does not sound simple at all even though API Tools theoretically support that, also note that IBuilds using Ant for comparison so this must also be adjusted.

If it where only Tycho, you can specify multiple baslines so having an additional repo with only the fixed swt jars would work: https://tycho.eclipseprojects.io/doc/latest/tycho-apitools-plugin/verify-mojo.html#baselines

As far as I know we have sometimes *backports* to older releases not sure if these publish a repository we can use given we create a backporting PR....

**Comment by laeubi** [comment]
I now enhanced the Tycho Mojo here:
- https://github.com/eclipse-tycho/tycho/pull/3561

once this is done we need this here:
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1891

**Comment by iloveeclipse** [comment]
> once this is done we need this here

But that fixes master only, we need a build / patch on 4.31 maintenance branch, to produce one 4.31 build with proper SWT API descriptions.

**Comment by laeubi** [comment]
> But that fixes master only, we need a build / patch on 4.31 maintenance branch, to produce one 4.31 build with proper SWT API descriptions.

One step after the other... for me its not clear if we can do anything, what are the "diffs" to the last working, e.g. can we somehow "archive" SDK-I20240202-1800 build and just use that? It should not have any API changed I would assume.

**Comment by iloveeclipse** [comment]
SDK-I20240202-1800 is the last "good" build I have at home, SDK-I20240209-1800 is the first "bad", and in between I simply don't have an idea where exactly it was broken and if that would be the "same" API as in 4.31.

But assuming last 4.31 RC2 contains officially released SWT API for 4.31, we should build on maintenance branch once one build nased on that with proper API description for SWT and somehow mark this build that it is not removed and use it as baseline for 4.32 development.

Or we just save api description to git and don’t care about extra build :)

**Comment by laeubi** [comment]
> Or we just save api description to git and don’t care about extra build :)

I don't understand to what feature this refers to, usually one has two description files:

1. baseline bundle (what is broken and we can't change easily)
2. current / workspace what is the one used to compare against (1) and will be fixed soon.

how would any adding to git help with (1)?

**Comment by iloveeclipse** [comment]
What I mean is: if I understand it right, API tooling, given an API baseline, lookups .api_description files from the bundles in the baseline. Right now it gets almost empty files for SWT bundles. What we can do is to add a simple check in PDE API tooling for the "known broken" bundles and in case we see them, load "fixed full" SWT API descriptions from PDE API bundle itself. Given the fact there is only one final SWT 4.31 version possible, we can checkin & ship the 4 platform specific SWT API description files with 4.32 PDE API and use them during 4.32 release.
After 4.32 we can remove them and that's it.

**Comment by iloveeclipse** [comment]
I have a patch, that does what I've wrote above. 

Assuming tycho uses API tools code in org.eclipse.pde.api.tools.internal.model.BundleComponent.loadApiDescription(File), that should also work for tycho.

The last good build is https://download.eclipse.org/eclipse/updates/4.31-I-builds/I20240207-0610/ and that is matching my guess that the root cause for broken description is https://github.com/eclipse-platform/eclipse.platform.swt/commit/15d3065bc26e206eac005917adb3814b3dd497f7

I will use api descriptions from that build. There was an API change later on, but I believe it didn't introduced new "annotated" API, so we should be fine (has to be checked).

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-pde/eclipse.pde/pull/1191

**Comment by iloveeclipse** [comment]
> Why is this not discovered by I-Builds?

I assume because they used 4.30 baseline till release (I guess this must be configured somewhere in aggregator?). 
And new baseline is probably not set yet there?

**Comment by iloveeclipse** [comment]
> There was an API change later on, but I believe it didn't introduced new "annotated" API, so we should be fine (has to be checked).

I've compared code between c61465f079addb7cecfe9b42bbef8e5bedcc0bea and dcada01874ff21d5d734425b6001cb4a7666277f  and see no **annotated** API changes. So we should be OK with API descriptions from [I20240207-0610/](https://download.eclipse.org/eclipse/updates/4.31-I-builds/I20240207-0610/), assuming they were properly created (at least files are not empty) :-)

**Comment by iloveeclipse** [comment]
> > Why is this not discovered by I-Builds?
> 
> I assume because they used 4.30 baseline till release (I guess this must be configured somewhere in aggregator?). And new baseline is probably not set yet there?

Another possibility is that during API check tycho calls API tooling to compare two **bundles** with each other, and as long as api description files are broken (empty) both in baseline and in the IBuild bundle, there are no API errors reported?

So before merging https://github.com/eclipse-pde/eclipse.pde/pull/1191 (that fixes comparison between "broken" 4.31 baseline and workspace baseline (which uses SWT sources) we should make sure we can properly generate api description files for SWT.

**Comment by laeubi** [comment]
I triggered I build now: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.31/

**Comment by iloveeclipse** [comment]
> I triggered I build now: https://ci.eclipse.org/releng/job/Builds/job/I-build-4.32/15/

That has now api description. But why don't we have API errors reported during build if baseline has no descriptions, and current build has? Or is the baseline wrong? Or the errors are reported but ignored?

**Comment by laeubi** [comment]
I have no clue, the I-Build uses special scripts for API comparison.

https://download.eclipse.org/eclipse/downloads/drops4/I20240310-0340/testResults.php says

> This tool verifies the versions of the plugins against Eclipse 4.30. 

Looking here: https://download.eclipse.org/eclipse/downloads/drops4/I20240310-0340/apitools/analysis/html/index.html I can't find that swt is actually checked at all...

**Comment by laeubi** [comment]
And then there is this list:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.tychoeclipsebuilder/eclipse/apiexclude/exclude_list_external.txt

what claims something is checked by its host... but only for win32 ..
