### ISSUE TITLE
Older binaries are not deleted

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.swt#1095]
Discovered by @chirontt [here](https://github.com/eclipse-platform/eclipse.platform.swt/discussions/1088)  but perhaps better opened as an issue rather than a discussion to get more visibility.

This is since 47db2f0e

**Comment by Phillipus** [comment]
The latest I-builds contain both the old and new binaries in the `org.eclipse.swt.xxxx` jar files.

**Comment by jukzi** [comment]
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/51790620/8445839a-d049-4f63-8241-e03892ebfeff)

**Comment by iloveeclipse** [comment]
@HannesWell : please look at this issue, I've described why it happens in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1100.

I've pushed a possible fix (https://github.com/eclipse-platform/eclipse.platform.swt/pull/1100) but I fear that is too simple and we will miss some native libraries that aren't built yet (like https://github.com/eclipse-platform/eclipse.platform.swt/blob/d80b3268354ffc76afe1d3c2cf6cf9bb881c2c86/binaries/org.eclipse.swt.win32.win32.x86_64/WebView2Loader.dll).

**Comment by HannesWell** [comment]
Resolved by running the master build with enforced native-build after #1100 has been submitted.
