### ISSUE TITLE
Why is  the latest Eclipse Equinox built using JDK17?

### ISSUE THREAD

**Issue by Georges6324** [eclipse-platform/eclipse.platform.swt#1113]
Due to the latest Eclipse Equinox being built using jdk17, my project running on jdk11 cannot be completed

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/49939824/f5ca6fa5-0172-46c4-8831-217a9c0a639c)

**Comment by Georges6324** [comment]
The latest Eclipse Equinox was released on March 13th

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/49939824/00edff4b-8db9-4287-b49b-21294544192e)

**Comment by deepika-u** [comment]
Hi, I am sorry but just trying to understand how is it an issue with swt? Is it meant to be opened in a different repo?
