### ISSUE TITLE
Arrow buttons are not shown on Windows 11

### ISSUE THREAD

**Issue by x21L** [eclipse-platform/eclipse.platform.swt#112]
The arrow buttons do not work correctly on Windows 11. They are not shown.
Please take a look at [Bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577911) for example screenshots.
I created a GitHub repo with a small example to recreate the bug. https://github.com/x21L/swt-button-test

**Comment by SyntevoAlex** [comment]
Already fixed in https://bugs.eclipse.org/bugs/show_bug.cgi?id=577129

**Comment by SWATHIBHUMA** [comment]
Still Arrow Buttons and CCombo are not working in Windows 11.
