### ISSUE TITLE
On MacOs Sonoma with Eclipse 4.31 items in views are very spaced

### ISSUE THREAD

**Issue by ptrussart** [eclipse-platform/eclipse.platform.swt#1123]
Hello,

Since I have updated my Eclipse, the items in the views are displayed differenty than before, they are displayed with a lot of spaces between each elements (see capture).

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/11556849/51e1556d-05a7-4f91-9457-c6b69ceaba65)

Is it a bug or is there a settings somewhere ?
I have tried to disable the themes but it is the same.

**Environment:**
- - [ ] All OS
- - [ ] Windows
- - [ ] Linux
- - [X] macOS 

It happens with MacOs Sonoma and Eclipse 4.31

Any known workarounds for the problem?

**Comment by merks** [comment]
Duplicates https://github.com/eclipse-platform/eclipse.platform.ui/issues/1674
