### ISSUE TITLE
fixFocus works differently between SWT and RWT

### ISSUE THREAD

**Issue by Nick-Hanson** [eclipse-platform/eclipse.platform.swt#1160]
SWT Version: 3.7.2
RWT Version: 3.14.0

![fixFocusIssue](https://github.com/eclipse-platform/eclipse.platform.swt/assets/30707151/53009feb-9bfe-4ed5-b5b7-b94c6c2dfd08)

We have a UI component that we assemble in an RCP application and in a standalone RAP application. User can type in a text field to select a printer, click the + (Add) button to add that printer to the below list. The system then clears the text field and disables the Add button. So the add button has focus when we disable it. There is logic in Control#setEnabled to 'fixFocus' avoid leaving the user in a state where nothing has focus.
In our RCP application, focus is set to the text field. (Left picture in attachment) But in our RAP application it is not. I believe the dialog itself has focus in our RAP application. (Right picture in attachment)

**Comment by akurtakov** [comment]
If I understand correctly the issue is that RAP that doesn't set focus to the text field, in this is the case you should report it at https://github.com/eclipse-rap/org.eclipse.rap
