### ISSUE TITLE
Scrollable.getScrollbarsMode returns SWT.SCROLLBAR_OVERLAY even when overlay scrolling is disabled on Linux/GTK3

### ISSUE THREAD

**Issue by wiresketch** [eclipse-platform/eclipse.platform.swt#1182]
**Describe the bug**
On Linux/GTK3 overlay scrolling can be disabled by setting the GTK_OVERLAY_SCROLLING=0 environment variable. However the Scrollable.getScrollbarsMode() still returns SWT.SCROLLBAR_OVERLAY in this case. Scrollable.gtk_draw method already checks this environment variable on GTK3 using the OS.GTK_OVERLAY_SCROLLING_DISABLED constant populated from it. So it would only be logical to use the same kind of check in Scrollable.getScrollbarsMode() to return a consistent result.

**To Reproduce**

[ScrollbarsModeOverlayTest.java.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/15027110/ScrollbarsModeOverlayTest.java.txt)

Run the attached snippet with and without GTK_OVERLAY_SCROLLING=0 setting. In both cases the result of Scrollable.getScrollbarsMode() will be printed as SWT.SCROLLBAR_OVERLAY.
  
**Expected behavior**
With GTK_OVERLAY_SCROLLING=0 the result of Scrollable.getScrollbarsMode() should be SWT.NONE

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [x] Linux
- - [ ] macOS

**Comment by iloveeclipse** [comment]
@wiresketch : do you want to provide a patch?

**Comment by iloveeclipse** [comment]
The patch I have in mind would be:
```
diff --git a/bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Scrollable.java b/bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Scrollable.java
index 0157962..e19aad6 100644
--- a/bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Scrollable.java
+++ b/bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Scrollable.java
@@ -306,3 +306,5 @@
 	if (GTK.gtk_scrolled_window_get_overlay_scrolling(scrolledHandle)) {
-		return SWT.SCROLLBAR_OVERLAY;
+		if(!OS.GTK_OVERLAY_SCROLLING_DISABLED) {
+			return SWT.SCROLLBAR_OVERLAY;
+		}
 	}
```
Is this what you were thinking about?

**Comment by wiresketch** [comment]
I've created a pull request. I believe this case can be checked before calling gtk_scrolled_window_get_overlay_scrolling.

**Comment by wiresketch** [comment]
Please also note that the GTK_OVERLAY_SCROLLING variable support is not supported on GTK4, hence the GTK4 check.
