### ISSUE TITLE
Provide Scrollable.setScrollbarsMode to add the possibility to change the scrollbars mode

### ISSUE THREAD

**Issue by wiresketch** [eclipse-platform/eclipse.platform.swt#1184]
**Is your feature request related to a problem? Please describe.**
We've encountered a performance issue with GEF/Draw2d and overlay scrollbars on Linux/GTK3. See [eclipse#430](https://github.com/eclipse/gef-classic/issues/430).

This performance issue can be avoided by disabling overlay scrolling using GTK_OVERLAY_SCROLLING=0 environment variable. However this is not a good solution since it impact all scrollable controls in the application and not only the specific control with have performance issues with. Also in GTK4 this variable is not supported anymore so this solution won't work in the future (see https://docs.gtk.org/gtk4/running.html#environment-variables where GTK_OVERLAY_SCROLLING variable is not listed anymore).

A more appropriate solution would be to add Scrollable.setScrollbarsMode(int) method that would allow to disable overlay scrolling for a specific scrollable control without affecting the rest of the application.

**Describe the solution you'd like**

Add Scrollable.setScrollbarsMode(int) method that would allow to change the scrolling mode for a specific Scrollable control. On GTK3 and GTK4 this can be easily implemented using the [gtk_scrolled_window_set_overlay_scrolling](https://docs.gtk.org/gtk3/method.ScrolledWindow.set_overlay_scrolling.html) method.

On Windows as far as I can see this method would be noop since overlay scrollbars are not supported there.

I am not familiar with macOS API, but it looks like it would be possible to set scrollerStyle property on NSScrollView.

**Comment by iloveeclipse** [comment]
@wiresketch : would be nice if you could contribute a patch.

**Comment by wiresketch** [comment]
I've created a pull request and added the required implementation for GTK. On Windows I've left the method as noop.

On macOS I've also left the method as noop. I am not sure if this method needs such an implementation there. Those with more experience on macOS please chime in.

**Comment by iloveeclipse** [comment]
Thanks for contributing!
