### ISSUE TITLE
Code suggestions keep crashing Eclipse (Segmentation Fault)

### ISSUE THREAD

**Issue by CopperEagle** [eclipse-platform/eclipse.platform.swt#1249]
- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce
When coding, the completion suggestions (content assist) typically crash eclipse. Usually it shows the recommendations once but when updating (e.g. when I type the next character) then it crashes. What I am noticing is that if I wait a second or two when the suggestions are shown, it crashes as well.

Now I assumed that this has something to do with the environment - I used the 2021 version of eclipse for a long time and it worked. So I removed all folders I found that eclipse uses and reinstalled it, also the newest version, 2024-3. No change. When looking at the error, it does not look like it is an environment error, though...

The fix for me right now is to disable auto activation of content assist. 

## Here is some relevant log output
[hs_err_pid25962.log](https://github.com/eclipse-platform/.github/files/15407976/hs_err_pid25962.log)

## Tested under this environment:
* OS & version: Ubuntu 22.04 LTS
* Eclipse IDE/Platform version (as shown in *Help > About*):  2024-03
* Clean sheet Eclipse: I didn't install plugins, etc. 
* I did recently install ant and gradle. (Using `apt`.)

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

Any help is appreciated. Thank you :heart:

**Comment by jukzi** [comment]
```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 4716  org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Z)Z (0 bytes) @ 0x00007c0b153b0fe1 [0x00007c0b153b0fa0+0x0000000000000041]
J 4717 c1 org.eclipse.swt.widgets.Display.readAndDispatch()Z (88 bytes) @ 0x00007c0b0d9b2fac [0x00007c0b0d9b2de0+0x00000000000001cc]
j  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run()V+564
```

**Comment by jukzi** [comment]
duplicates:
https://github.com/search?q=repo%3Aeclipse-platform%2Feclipse.platform.swt+gtk_main_iteration_do&type=issues

**Comment by CopperEagle** [comment]
Thanks for your answer.

I mean the reports that are present are not quite duplicates but I guess I get it, Wayland causing all sorts of trouble.
