### ISSUE TITLE
 UI freezes because of DPI configuration: "Per-Monitor (v2)"

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.swt#1262]
_(Moved here as requested in https://github.com/vi-eclipse/Eclipse-Platform/issues/68#issuecomment-2150376055)_

Setting the DPI configuration to "Per Monitor (v2)" can trigger a UI freeze, as described in this old eclipse issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=571209

Most of the findings have already been discussed with Vector and Yatta colleagues and possible solutions and workarounds have been planned. This issue should work as an umbrella for the future steps.

## Goal
Investigate and document:
* Why does the UI-freeze happen?
* Is it avoidable? How?
* Are there any possible workarounds?

## Starting point
See Heiko's E-Mail below (in German):

```text
From: Klare, Heiko 
Sent: Friday, April 19, 2024 11:15 AM 
Subject: RE: Langsame IDE-Reaktionen

Hallo zusammen,

hier noch eine weitere Info zu unseren IDE-Performance-Problemen: es gab von einigen Kollegen die 
Meldung, dass es Freezes in der Breakpoints-View gibt.

Da sich der Corretto-JDK-Build ja in Bezug auf DPI-Awareness 
sowieso unkonventionell verhält, habe ich Christian mal geraten einen anderen JDK-Build (z.B. Temurin) 
zu nutzen. Es wäre auch möglich, dass die anderen Freezes, bei denen die VM in OS-Calls hängt (was laut 
Grafana-Logs ja die meisten sind) mit DPI-bezogenen Problemen in Multi-Monitor-Setups zusammen 
und könnten durch einen anderen JDK-Build oder ein modifiziertes Java-Manifest für unsere IDE gelöst 
werden.

Was bei Christian ersten Erkenntnissen nach (auch ohne anderen JDK-Build) funktioniert hat, ist es im „-
vm“-Argument in der .ini nicht  „javaw“ zu nutzen. Also konkret das Ersetzen von
-vm 
D:/Dev/java/corretto-jdk17.0.5.8.1_x86_64/bin/javaw
durch
-vm 
D:/Dev/java/corretto-jdk17.0.5.8.1_x86_64/bin

Das führt nebenbei euch dazu, dass die gemeldeten HiDPi-Probleme in Multi-Monitor-Setups 
verschwinden, sodass wir auf den Workaround mit den Kompatibilitäts-Einstellungen verzichten 
können.

Perspektivisch sollten wir dann aus meiner Sicht wirklich auf einen Temurin-JDK-Build wechseln. Darüber 
könnten wir am kommenden Donnerstag im Dev-Tools-Standup sprechen.

Viele Grüße und ein schönes Wochenende
Heiko
```

**Comment by fedejeanne** [comment]
Here are some of my notes and findings.

## The problem
When working with multiple monitors with different DPI configurations, some UI freezes may occur.

## The setup
_(As explained in [comment#23](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571209#c23))_
* 2 monitors
* Monitor on the left is set to zoom = 100%
* Monitor on the right is set to zoom = 125%

## How to reproduce the problem
_(As explained in [comment#29](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571209#c29))_
* Open Eclipse and put it on the left monitor
* Open the _outline view_, it should be on the right (close to the other monitor)
* Hover over the name of a method that is very long --> A "tooltip" (I call it "overlay") with the whole name of the method will appear. If most of that overlay goes to the monitor on the right then the hang occurs.

## Why does this happen?
The issue seems to be that a repaint event is "triggering itself again". This is a very short simplification, of course. The whole analysis is in [comment#36](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571209#c36).

## Is this an SWT/Eclipse problem?
I don't think so! I was able to reproduce the problem with the **Windows Explorer**, which means that this is probably a problem with Windows and it should be reported.

![Explorer hangs on mutiple DPI configuration](https://github.com/vi-eclipse/Eclipse-Platform/assets/2205684/50fcd1b4-b21a-4df3-848c-827e6e36cfef)

## Workaround
_(As explained in [comment#44](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571209#c44))_
 Avoid using the DPI configuration _Per monitor (v2)_ and use _System_ instead. This can be achieved by either:
* Pointing the start parameter `-vm` to the `<JDK_FOLDER>\bin` instead of `<JDK_FOLDER>\bin\javaw` or...
* Overriding the DPI configuration via the _properties_ of the EXE file (`Righ click > Properties > ...)` as described in [comment#38](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571209#c38) and [comment#39](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571209#c39) or...
* Providing a **Manifest file** for the proper `javaw.exe` and override the property `dpiAwareness` (and also `dpiAware`, for older systems) so it uses `system` instead of `PerMonitorV2system`. Ours looks like this:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
   <assemblyIdentity version="1.0.0.0" processorArchitecture="*" name="SWT.javaw" type="win32" />
   <description>Standard Widget Toolkit</description>
   <dependency>
      <dependentAssembly>
         <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*" />
      </dependentAssembly>
   </dependency>
   <application xmlns="urn:schemas-microsoft-com:asm.v3">
      <windowsSettings>
         <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/pm</dpiAware>
         <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">system</dpiAwareness>
      </windowsSettings>
   </application>
   <!--Specifically targeting your application for Windows 8.1 or Windows 10: https://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx -->
   <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
        <application>
            <!-- Windows 10 -->
            <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
            <!-- Windows 8.1 -->
            <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
            <!-- Windows Vista -->
            <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
            <!-- Windows 7 -->
            <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
            <!-- Windows 8 -->
            <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
        </application>
    </compatibility>
</assembly>
```

## TO-DO
* [ ] Report the issue to Microsoft

**Comment by fedejeanne** [comment]
fyi @akoch-yatta , @HeikoKlare

**Comment by jukzi** [comment]
This a duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/557 ?!

**Comment by fedejeanne** [comment]
> This a duplicate of #557 ?!

And here I was, thinking I just had an original thought 😛  . Thank you for pointing it out, @jukzi !
