### ISSUE TITLE
Move TabFolderLayout into SWT and set it as a default in TabFolder

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.swt#1317]
Today I debugged some issues with `TabFolder` and noticed that it at least behaves strange if tabs are added dynamically, after investigate a little bit more I tried to fix it with an own Layout as usual layout mangers (like `FillLayout`) get sometimes confused as `TabFolder` has more childs than are actually displayed.

Short after that I noticed that there are already some instances of `TabFolderLayout` in platform:
![grafik](https://github.com/eclipse-platform/eclipse.platform.swt/assets/1331477/ed71f6db-1a50-44cd-a960-a29feb278f43)

They all seem to be copies of each other (more or less) except the license header and when they where added, I therefore wonder if we should simply add that layout to SWT and even set it by default to `TabFolder`.

**Comment by Kiiv** [comment]
Hi !

Seems a HUGE breaking change to me. What about "old" plugins steel using those classes ?

For example, after upgrading to Eclipse 2024-12, Subversive does not work anymore :
```
Opération de mise à jour échouée .
java.lang.NoClassDefFoundError: org/eclipse/compare/internal/TabFolderLayout
```

I will open an issue over-there but in the meantime I'll probably need to revert to Eclipse 2024-09 (and it's not easy :s).
Since Subversive, even if it's part of the Eclipse Foundation, does not seems alive, I have no much hope.

Any workaround ?

**Comment by dogla** [comment]
Hi Kiiv,

> For example, after upgrading to Eclipse 2024-12, Subversive does not work anymore :
> ```
> java.lang.NoClassDefFoundError: org/eclipse/compare/internal/TabFolderLayout
> ```

I had the same problem.

To use eclipse 4.34 with a working subversive I opened the org.eclipse.compare_3.11.200.v20241024-1455.jar and added the TabFolderLayout.class from a previous eclipse version, in my case from 4.33, into the right subfolder.
After starting eclipse SVN worked as before.

It's a hack but it works for me.
So I can use the latest eclipse with an old subversive version, that depends on the removed org.eclipse.compare.internal.TabFolderLayout.

**Comment by Rajagopalang** [comment]
@dogla Working fine your solution...I have added same TabFolderLayout.class from old version to org.eclipse.compare_3.11.200.v20241024-1455.jar... Thanks lot...

![image](https://github.com/user-attachments/assets/0c31b652-d651-48ae-ac27-11ce54de7fb5)

**Comment by Kiiv** [comment]
@dogla thanks for the workaround ! On my side, I've forked and patched subversive to support the change.
If I understand how to submit a patch, I will try to share the fix...

**Comment by vogella** [comment]
Please do not forget to report to https://github.com/subclipse/subclipse so that the team has at least the chance to fix this.

**Comment by Kiiv** [comment]
> Please do not forget to report to https://github.com/subclipse/subclipse so that the team has at least the chance to fix this.

It's about subversive, not tested with subclipse.
I've already opened an issue there: https://gitlab.eclipse.org/eclipse/subversive/subversive/-/issues/245
