### ISSUE TITLE
Source code compilation of SWT reports errors.               can not find eclipse.platform.swt:pom:4.26.0-SNAPSHOT

### ISSUE THREAD

**Issue by TheShy123456789** [eclipse-platform/eclipse.platform.swt#1322]
[ERROR] The build could not read 13 projects -> [Help 1]
[ERROR]   
[ERROR]   The project org.eclipse.swt:org.eclipse.swt:3.122.0-SNAPSHOT (/home/eclipse.platform.swt/bundles/org.eclipse.swt/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.eclipse.swt:org.eclipse.swt:3.122.0-SNAPSHOT: Failure to find eclipse.platform.swt:eclipse.platform.swt:pom:4.26.0-SNAPSHOT in https://repo.eclipse.org/content/repositories/eclipse/ was cached in the local repository, resolution will not be reattempted until the update interval of eclipse-hosted has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 16, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project org.eclipse.swt:org.eclipse.swt.fragments.localbuild:3.105.0-SNAPSHOT (/home/eclipse.platform.swt/local-build/org.eclipse.swt.fragments.localbuild/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.eclipse.swt:org.eclipse.swt.fragments.localbuild:3.105.0-SNAPSHOT: Failure to find eclipse.platform.swt:eclipse.platform.swt:pom:4.26.0-SNAPSHOT in https://repo.eclipse.org/content/repositories/eclipse/ was cached in the local repository, resolution will not be reattempted until the update interval of eclipse-hosted has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 14, column 11 -> [Help 2]

**Comment by TheShy123456789** [comment]
I'm very interested in swt, but I couldn't find eclipse.platform.swt:pom:4.26.0-SNAPSHOT at the repository address provided in the pom file during the compilation process, I would like to hear from you, thank you very much.

**Comment by akurtakov** [comment]
In such cases you are supposed to force redownload by using -U mvn flag.
