### ISSUE TITLE
Class org.eclipse.swt.graphics.Image does not have member field 'int currentDeviceZoom'

### ISSUE THREAD

**Issue by gnl42** [eclipse-platform/eclipse.platform.swt#1343]
**Describe the bug**

After Eclipse updated itself with
![348375083-9b63ca7e-852a-4c4c-a600-6663a3b945fc](https://github.com/user-attachments/assets/3bb5e708-1081-4217-81cd-2e6244138ee3)

it started crashing at startup with:
```
java.lang.NoSuchFieldError: Class org.eclipse.swt.graphics.Image does not have member field 'int currentDeviceZoom'
        at org.eclipse.swt.graphics.Image._createDisabled(Image.java:2528)
        at org.eclipse.swt.graphics.Image.<init>(Image.java:254)
        at org.eclipse.jface.resource.DerivedImageDescriptor.internalCreateImage(DerivedImageDescriptor.java:83)
        at org.eclipse.jface.resource.DerivedImageDescriptor.createResource(DerivedImageDescriptor.java:51)
        at org.eclipse.jface.resource.DeviceResourceManager.allocate(DeviceResourceManager.java:56)
        at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
        at org.eclipse.jface.resource.LazyResourceManager.create(LazyResourceManager.java:88)
        at org.eclipse.jface.resource.LocalResourceManager.allocate(LocalResourceManager.java:71)
        at org.eclipse.jface.resource.AbstractResourceManager.create(AbstractResourceManager.java:92)
        at org.eclipse.jface.resource.ResourceManager.createImageWithDefault(ResourceManager.java:192)
        at org.eclipse.jface.action.ActionContributionItem.updateImages(ActionContributionItem.java:1017)
        at org.eclipse.jface.action.ActionContributionItem.updateToolItem(ActionContributionItem.java:777)
        at org.eclipse.jface.action.ActionContributionItem.update(ActionContributionItem.java:740)
        at org.eclipse.jface.action.ActionContributionItem.update(ActionContributionItem.java:714)
        at org.eclipse.jface.action.ToolBarManager.update(ToolBarManager.java:345)
        at org.eclipse.ui.internal.CoolBarToTrimManager.update(CoolBarToTrimManager.java:596)
        at org.eclipse.ui.internal.WorkbenchWindow.updateActionBars(WorkbenchWindow.java:2481)
        at org.eclipse.ui.internal.WWinActionBars.updateActionBars(WWinActionBars.java:123)
        at org.eclipse.ui.SubActionBars.updateActionBars(SubActionBars.java:602)
        at org.eclipse.ui.internal.e4.compatibility.ActionBars.updateActionBars(ActionBars.java:88)
        at org.eclipse.ui.internal.e4.compatibility.CompatibilityView$1.compute(CompatibilityView.java:203)
        at org.eclipse.e4.ui.workbench.renderers.swt.ToolBarManagerRenderer.postProcess(ToolBarManagerRenderer.java:961)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:676)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:762)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:727)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
```
**To Reproduce**
Steps to reproduce the behavior.

Update eclipse and restart

**Expected behavior**
Eclipse should launch normally

**Screenshots**

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [] All OS
- - [X] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Windows 11

3. JRE/JDK version
 22
**Version since**
```
!SESSION 2024-07-12 10:18:22.441 -----------------------------------------------
eclipse.buildId=4.33.0.20240711-1200
java.version=22.0.1
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_CA
Framework arguments:  -product org.eclipse.epp.package.committers.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.committers.product
```

**Workaround (or) Additional context**
Any known workarounds for the problem?

Unknown

**Comment by merks** [comment]
This was changed by this:

![image](https://github.com/user-attachments/assets/5b104778-e1b7-4b3a-ac92-e65f88828d33)

I assume you restarted after the update...  It's hard to imagine how SWT could be only partially updated.  It's a single bundle with a single fragment so it must be either the old one or the new one.  I don't get it...

**Comment by laeubi** [comment]
@gnl42 please try to start eclipse with the `-clean` option

**Comment by gnl42** [comment]
-clean made no difference

**Comment by merks** [comment]
What versions of SWT are installed?  I've updated 3 IDEs today.  My Mylyn IDE has this installed:

![image](https://github.com/user-attachments/assets/d29c6b85-bb01-4a8b-ae90-db81af1a2da5)

**Comment by gnl42** [comment]
Eclipse has crashed before I can get to that point, but the file system shows:
```
.plugins/org.eclipse.pde.core/.bundle_pool/plugins/org.eclipse.swt.win32.win32.x86_64_3.126.0.v20240528-0813.jar
.plugins/org.eclipse.pde.core/.bundle_pool/plugins/org.eclipse.swt.win32.win32.x86_64_3.127.0.v20240624-1000.jar
```

**Comment by merks** [comment]
These are contents  of your target platforms.   It's not that easy to see what's installed just from the file system when a shared bundle pool is used.  The <installation-folder>/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info has a list.

**Comment by gnl42** [comment]
I get the same:
```
$ grep org.eclipse.swt.win32.win32 mylyn-main/ws/.metadata/.plugins/org.eclipse.pde.core/Mylyn-Runtime/org.eclipse.equinox.simpleconfigurator/bundles.info
org.eclipse.swt.win32.win32.x86_64,3.127.0.v20240624-1000
```

A fresh install gives me the expected: `org.eclipse.swt.win32.win32.x86_64,3.127.0.v20240704-1545`

I don't know what would cause the update to skip updating the jar.

**Comment by merks** [comment]
It's the bundle.info of the installation that gives the information; sorry I left out the back quotes so `<installation-folder>` looked like an XML tag that was ignored.  Anything in the workspace or nested under org.eclipse.pde.core will have to do with the target platform which is orthogonal to whats installed.

It would be strange and unexpected that it doesn't update to v20240704-1545 but its beyond strange that it behaves as if it has updated but somehow is also still expecting fields form an older version of the class which is no longer installed.

**Comment by merks** [comment]
It's not entirely clear how one got into this state and even less clear what that state is exactly.  In any case, it's not something that can be fixed by SWT, and since it looks like we cannot make further progress, I'll close it as not planned.  Sorry.

**Comment by coehlrich** [comment]
I did some debugging and found that the `_createDisabled` method is added to the `Image` class by devstyle.

**Comment by ekekakos** [comment]
After the last update I cannot start ECLIPSE and as a result I cannot work and I think that this is the problem.
I select the workspace but stop with a message to look the included file.
[.log](https://github.com/user-attachments/files/16963602/default.log)
When the workspace is new it is opening but I cannot work. And if I close and open again the same problem.
![New workspace error](https://github.com/user-attachments/assets/27ba7bb4-137a-4290-a352-7130fbc4b398)
Help please in order to work.
Thanks 
Elias

**Comment by HeikoKlare** [comment]
The `_createDisabled` method is not available in the `Image` class. It seems to be patched into it via bytecode manipulation or the like. You should consider contacting the provider of the "extensions" that relies on this kind of integration. This kind of integration is supposed to fail at some point in time.

**Comment by ekekakos** [comment]
Thanks but I cannot understand which EXTENSION has the problem.

**Comment by cosminstaicu** [comment]
More or less, I have the same problem. After the last update, Eclipse does not start (at all) with my existing workspace. If I create a new one, then the interface loads, but it is unusable.

The crash seems related to Genuitec extension - DevStyle

The error log starts with:

````
!SESSION 2024-09-11 20:17:54.249 -----------------------------------------------
eclipse.buildId=4.33.0.20240905-0613
java.version=22.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.php.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.php.product

!ENTRY org.eclipse.ui 2 0 2024-09-11 20:18:06.205
!MESSAGE Warnings while parsing the images from the 'org.eclipse.ui.commandImages' extension point.
!SUBENTRY 1 org.eclipse.ui 2 0 2024-09-11 20:18:06.205
!MESSAGE Cannot bind to an undefined command: plug-in='com.genuitec.eclipse.theming.ui', id='com.genuitec.myeclipse.help.darktheme.commandid'

!ENTRY org.eclipse.ui.ide 4 4 2024-09-11 20:18:06.711
!MESSAGE Not properly disposed SWT resource
!STACK 0
java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
.......................................................
````

**Comment by cosminstaicu** [comment]
I managed to start Eclipse without the Genuitec extensions.

From eclipse\configuration\org.eclipse.equinox.simpleconfigurator I have edited the bundles.info file, by  commenting (using #) all lines starting with `com.genuitec.eclipse`.

After that I have just started Eclipse. It is working ok, just the genuitec extensions (I am using the darkest dark theme) are missing.

**Comment by ekekakos** [comment]
Thanks HEXEDHERO for the solution. So the problem was the DARK THEME. Now I can work without this. Thanks again

**Comment by karthickow** [comment]
> I managed to start Eclipse without the Genuitec extensions.
> 
> From eclipse\configuration\org.eclipse.equinox.simpleconfigurator I have edited the bundles.info file, by commenting (using #) all lines starting with `com.genuitec.eclipse`.
> 
> After that I have just started Eclipse. It is working ok, just the genuitec extensions (I am using the darkest dark theme) are missing.

You just saved my day. Thanks a lot

**Comment by fanian** [comment]
> I managed to start Eclipse without the Genuitec extensions.
> 
> From eclipse\configuration\org.eclipse.equinox.simpleconfigurator I have edited the bundles.info file, by commenting (using #) all lines starting with `com.genuitec.eclipse`.
> 
> After that I have just started Eclipse. It is working ok, just the genuitec extensions (I am using the darkest dark theme) are missing.

Thank you. You save my time also.

**Comment by maxkratz** [comment]
fyi, the devs behind the darkest dark theme published an update today and claim that it is compatible with Eclipse 2024-09 R: https://marketplace.eclipse.org/content/darkest-dark-theme-devstyle

(I could not test it yet, though.)

**Comment by gnl42** [comment]
It works for me

**Comment by ekekakos** [comment]
I uninstall and install again and it works also for me.
Thanks all for your valuable help.
Elias
