### ISSUE TITLE
New crash with newest SWT

### ISSUE THREAD

**Issue by cdietrich** [eclipse-platform/eclipse.platform.swt#1350]
our Xpect build fail in test against latest nightly 

https://ci.eclipse.org/xpect/job/Xpect/job/master/1056/artifact/org.eclipse.xpect.tests/target/work/data/.metadata/.log

java.lang.UnsatisfiedLinkError: 'long org.eclipse.swt.internal.gtk3.GTK3.gtk_gesture_zoom_new(long)

**Comment by iloveeclipse** [comment]
Probably https://github.com/eclipse-platform/eclipse.platform.swt/pull/1348 .
SDK build itself is affected, most Linux tests are failing.

**Comment by akurtakov** [comment]
I can check later today but most likely natives rebuild failed. @HannesWell can you check?

**Comment by akurtakov** [comment]
Natives are rebuild via this job https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/master/637/ which timed out. If one looks at https://ci.eclipse.org/releng/ he will see that all the macos test jobs are pending too. So mac os machines are down.

**Comment by HannesWell** [comment]
> Natives are rebuild via this job https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/master/637/ which timed out. If one looks at https://ci.eclipse.org/releng/ he will see that all the macos test jobs are pending too. So mac os machines are down.

Exactly. The Mac machines are in launching state and the windows machine is offline:
https://ci.eclipse.org/releng/

All have to be brought back online, the master has to be rebuild and then an I-build can be re-triggered.

In general maybe a check should be added to the I-build to be informed if the SWT or equinox binaries are out of sync, so that the I-build fails early and clearly.

**Comment by iloveeclipse** [comment]
I've created https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4834

**Comment by iloveeclipse** [comment]
@HannesWell : assuming machines will start up again, we just need to trigger https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/master/ , correct?

**Comment by HannesWell** [comment]
> I've created https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4834

Thanks!

> @HannesWell : assuming machines will start up again, we just need to trigger https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/master/ , correct?

Affirmative. That's correct.

**Comment by iloveeclipse** [comment]
https://ci.eclipse.org/releng/computer/rs68g%2Dwin10/ seem to be back?

**Comment by merks** [comment]
The Oomph build failed too when launching the installer.  But doesn't fail locally on my Windows machine.  Seeing this issue helps me to avoid investigating further!  @cdietrich  Thanks for reporting!

**Comment by iloveeclipse** [comment]
The SWT build seem to be fine now, I've triggered SDK build

- https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/master/640/
- https://ci.eclipse.org/releng/job/Builds/job/I-build-4.33/70/

**Comment by iloveeclipse** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/I20240718-0510/ is available, the tests aren't yet done, but locally I'm able to start SDK without issues on RHEL9.

I've marked https://download.eclipse.org/eclipse/downloads/drops4/I20240717-1800/ build as unstable now.

**Comment by iloveeclipse** [comment]
tests are OK too for https://download.eclipse.org/eclipse/downloads/drops4/I20240718-0510/testResults.php, closing.
