### ISSUE TITLE
Have hook for instantiation of Display

### ISSUE THREAD

**Issue by frankbenoit** [eclipse-platform/eclipse.platform.swt#1371]
**Is your feature request related to a problem? Please describe.**

In complex projects, it might happen that a display instance is created by the use of Display.getDefault in the own code, or in dependencies. This changes the state for the application.
Later tests for being in the ui thread `Display.getCurrent() != null` might conclude, yes you are in the UI thread, but it was the faulty Display instance. Later resulting in strange "invalid thread access" because the widgets are using the other display instance.

**Describe the solution you'd like**

With an API that allows to verify that the creation of a new display instance is really allowed, before creation/registration of the instance.
eg checking that the thread name is "main", if not throw an exception to prevent the instantiation.

````
Display.addNewDisplayListener( SwtRunnable )
````

**Describe alternatives you've considered**

To hunt down such problems in my project, I figure out how to intercept Display with Byte-Buddy. But it was not an easy way.

**Additional context**

**Comment by laeubi** [comment]
> To hunt down such problems in my project, I figure out how to intercept Display with Byte-Buddy. But it was not an easy way.

Why not simply put a breakpoint?

> Later tests for being in the ui thread Display.getCurrent() != null might conclude, yes you are in the UI thread, but it was the faulty Display instance. Later resulting in strange "invalid thread access" because the widgets are using the other display instance.

There is nothing "faulty" with such instance (even though not all OS allow to create additional `Display`s)... being in a Display thread (and "main" is just a random name here) does not mean you can access everything, if that's important one needs to fetch the display of the widget itself.

If you want to be sure, `Display#execute` might be an better alternative at all because it always do the right thing (either execute in place or async) and do not need any boilerplate checks.

**Comment by frankbenoit** [comment]
Breakpoint is not helping with sporadic problems.
When I want this runtime verification on the build server and in the system testing.

The usage of Display.getDefault and Display.getCurrent() compare with null, is spread over all the eclipse ecosystem.
What if something was called from the wrong thread and the resulting Display instances causes trouble later. How to locate this?
I know there are setups where multiple Display instances are legal. But when I want to ensure a single one in my setup, then it is difficult to enforce. Testing for thread name "main" is just for my example use case.

Hence I request a listener, where I have a chance to react, if I need to.

**Comment by laeubi** [comment]
Even at Eclipse IDE (what can be considered "complex projects")  we never see any complains in this regard so I doubt it would be good to have an to track down programming errors. Such "listener" would only be useful for Windows anyways (as its the only OS that supports multiple `Display`s), so what should such listener offer (beside in your debugging case) to make it generally useful? 

The general "rule" is (and that's documented) that the first call to `Display.getDefault()` create *one* Display and makes it the "UI Thread" so an UI application should call this in the very beginning and then I don't see any problems or pitfalls here, the rest is only relevant.

> Hence I request a listener, where I have a chance to react, if I need to.

I don't see how one can "react" in such case, if the Application actively creates new Displays it has manage them, this is nothing that usually happens nor I know of any "dependencies" that do so.

**Comment by frankbenoit** [comment]
Right, this is primarily for debugging and the reaction might be to throw or log.

**Comment by laeubi** [comment]
> Right, this is primarily for debugging and the reaction might be to throw or log.

If you want you can start a Thread that periodically [iterates over all threads](https://stackoverflow.com/questions/1323408/get-a-list-of-all-threads-currently-running-in-java) and calls `org.eclipse.swt.widgets.Display.findDisplay(Thread)` there should always only be one Display thread and you can log an error.

I personally would just put a breakpoint in Display constructor and make sure it is only called once for the lifetime of your application.

**Comment by frankbenoit** [comment]
The debugger is not an option because of the remote build infrastructure and system testing. Those instances seem to happen sporadically.
Polling is not an option, because it does not help in showing from where the instance were coming.

Indeed my tour started in defensive code detecting the presence of the 2nd instance. But finding the origin is much harder, than I thought.

**Comment by laeubi** [comment]
> Polling is not an option, because it does not help in showing from where the instance were coming.

But you see what Threads create them, together with sensible naming it can give you some hints, you can also have a JUnit Rule, a JMX Bean and so on... nothing that really qualifies for a new API.

> Those instances seem to happen sporadically.

So are you sure you problems are caused by different Displays being created? It sounds a bit odd, you know that different Displays are involved but can't debug it so how do you know its the causing issue?

> Indeed my tour started in defensive code detecting the presence of the 2nd instance. But finding the origin is much harder, than I thought.

There must be somewhere a `new Display` call in your code, only using `Display.getCurrent()` or `Display.getDefault()` won't create more than one display, If you want to guard your own code you can do like this:

```
if (Display.getCurrent() == null) {
  //do what ever you do now to create the one and only display
} else {
 //throw an exception, something is fishy in your code...
}
```

**Comment by frankbenoit** [comment]
Anyway, I found a solution with byte-buddy.
Closing it.
