### ISSUE TITLE
[HiDPI] The mouse position is "scaled"

### ISSUE THREAD

**Issue by wolfgang-ch** [eclipse-platform/eclipse.platform.swt#1414]
**Describe the bug**
In the provided video the image height is 320px, the mouse max y position is 64px

VM arguments
```
-Dswt.autoScale.updateOnRuntime=true
-Dswt.autoScale=500
```

**To Reproduce**
Log the mouse position when a mouse is moved

**Expected behavior**
The mouse y max position should be 320px

**Screenshots**

https://github.com/user-attachments/assets/0afc4ce2-32a5-4aec-9b2e-655a0ec5ffba

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [?] All OS
- - [x] Windows
- - [?] Linux
- - [?] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Win 10

3. JRE/JDK version
java.vendor.version=Temurin-17.0.8+7
 
**Version since**
Build id: I20240818-1800

**Workaround**
unknown

**Comment by HeikoKlare** [comment]
As far as I know, the mouse event contains coordinates in points, not in pixels. SWT internally uses a point-based coordinate system with points being a linear scaling of pixels according to the current zoom factor. Most calculations are done based on values according these coordinates.
The y coodinate of 64 conforms to a pixel value of 320 when having a zoom of 500%. Thus the behavior you describe is, in my opinion, correct and expected.

**Comment by wolfgang-ch** [comment]
After debugging the mouse move event and how the locations are retrieved, I discovered that "all" locations are scaled. But to know the exact mouse location there is the method `org.eclipse.swt.widgets.Display.getCursorLocationInPixels()` however it is not public, so we need reflection.

This code shows how to get the exact location for the mouse within a control when the display is scaled:

```
if (_deviceScaling != 1) {

         try {

            /*
             * Get mouse position without scaling, there is no public API, so we use reflection
             */

            final Method getLocation_Method = Display.class.getDeclaredMethod("getCursorLocationInPixels");
            getLocation_Method.setAccessible(true);
            final Object getLocation_Result = getLocation_Method.invoke(getDisplay());

            if (getLocation_Result instanceof final Point displayLocation_Pixel) {

               final Method toControlInPixels_Method = Control.class.getDeclaredMethod("toControlInPixels", int.class, int.class);
               toControlInPixels_Method.setAccessible(true);
               final Object toControlInPixels_Result = toControlInPixels_Method.invoke(this, displayLocation_Pixel.x, displayLocation_Pixel.y);

               if (toControlInPixels_Result instanceof final Point relativeLocation_Pixel) {

                  _mouseMove_DevPosition_X_Pixel = relativeLocation_Pixel.x;
                  _mouseMove_DevPosition_Y_Pixel = relativeLocation_Pixel.y;
               }
            }

         } catch (NoSuchMethodException
               | SecurityException
               | IllegalAccessException
               | IllegalArgumentException
               | InvocationTargetException e) {

            StatusUtil.log(e);
         }
      }
```
