### ISSUE TITLE
[Help Needed] Screen flickering under Hyprland (DBeaver & Eclipse IDEs)

### ISSUE THREAD

**Issue by n5a5** [eclipse-platform/eclipse.platform.swt#1424]
**Describe the bug**
DBeaver users on Hyprland [report](https://github.com/dbeaver/dbeaver/issues/34528) screen flickering.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [x] Linux
- - [ ] macOS 

2. Additional OS info (e.g., OS version, Linux Desktop, etc)
Hyprland

3. JRE/JDK version
17.0.6

DBeaver is an Eclipse RCP application. I believe that the root cause of the issue is somewhere upstream. To verify that, I asked the reporters to check if the issue also exists in Eclipse IDEs. Two reporters confirmed.

Unfortunately, we don't have enough expertise to judge whether it is a bug in Hyprland or somewhere in the Eclipse Platform. I'm asking for your help here, guys. Thanks.

**Comment by akurtakov** [comment]
A check with kwin and/or mutter would be nice as it will point whether the issue lies in swt or in hyprland(first time I hear about it).

**Comment by n5a5** [comment]
Thanks a lot, everyone. I'm closing the issue since it's a Hyprland bug.
