### ISSUE TITLE
Build `org.eclipse.swt.gtk.linux.riscv64` and SWT native binaries on riscv64

### ISSUE THREAD

**Issue by yuzibo** [eclipse-platform/eclipse.platform.swt#1443]
Hi,

The background I have reported it at [#1431](https://github.com/eclipse-platform/eclipse.platform/issues/1431) on [eclipse.platform](https://github.com/eclipse-platform/eclipse.platform). If I understand correctly, if we want to get Eclipse built on riscv64, we first build 
`org.eclipse.swt.gtk.linux.riscv64` and SWT native binaries on riscv64 from the value[ guidance](https://github.com/eclipse-platform/eclipse.platform/issues/1431#issuecomment-2174476196).

First I followed[ these instructions](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator?tab=readme-ov-file#how-to-build-the-eclipse-sdk) to build the Eclipse on riscv64 machines, and got the [log](https://gist.github.com/yuzibo/006dce0f4c0e849edca39e89cdfecb60) at last.  From the [REAMDME](https://github.com/eclipse-platform/eclipse.platform.swt/blob/7ac43c0d40016f04974ae6ef971f4e5f39bd3c3c/bundles/org.eclipse.swt/Readme.md#building-and-testing-locally), I got confused that:

```python
From Eclipse:

If necessary, install the M2E - Maven integration for Eclipse (see [m2e](https://eclipse.dev/m2e/))
Open the Launch Configurations dialog.
Run the Maven configuration called: Build-SWT-native-binaries-for-running-platform.
If compile fails, inspect build log for warnings, they can point out issues in your configuration.
```
Are these operations performed on the Eclipse IDE? I mean we do not have Eclipse on riscv64 however. If not on Eclipse, just to use [build.sh](https://github.com/eclipse-platform/eclipse.platform.swt/blob/7ac43c0d40016f04974ae6ef971f4e5f39bd3c3c/bundles/org.eclipse.swt/Eclipse%20SWT%20PI/gtk/library/build.sh):

```
$ ./Eclipse\ SWT\ PI/gtk/library/build.sh
./Eclipse SWT PI/gtk/library/build.sh: 152: [: missing ]
-e Cairo found, compiling SWT support for the cairo graphics library.
-e jni.h found
-e libjawt.so found, the SWT/AWT integration library will be compiled.
-e Building SWT/GTK+ for Architectures: linux riscv64
-e Building GTK3 bindings:
make: make_linux.mak: No such file or directory
make: *** No rule to make target 'make_linux.mak'.  Stop.
-e *** GTK3 Build failed, aborting further actions..
```
Even though I fixed the issue, I got another error:
```
./build.sh: 152: [: missing ]
-e Cairo found, compiling SWT support for the cairo graphics library.
-e jni.h found
-e libjawt.so found, the SWT/AWT integration library will be compiled.
-e Building SWT/GTK+ for Architectures: linux riscv64
-e Building GTK3 bindings:
make: *** No rule to make target 'swt.c', needed by 'swt.o'.  Stop.
-e *** GTK3 Build failed, aborting further actions..
```

I must have wrongly understand here.

I built one Eclipse on window also, but no luck. Is this right direction?

Thank you in advance.

**Comment by chirontt** [comment]
> $ ./Eclipse\ SWT\ PI/gtk/library/build.sh

No, this wouldn't work, as it would be missing a few `.c` source files.

From the root of this repo, do the following:
```
cd binaries/org.eclipse.swt.gtk.linux.riscv64
mvn clean process-resources -Dnative=gtk.linux.riscv64
```
If the compile fails (as it did to me for the `x86_64` arch), all the relevant `.c` source files will be available in the `target/natives-build-temp` directory, including the `build.sh` file. You can then re-invoke that `build.sh` to build the SWT binaries from there, after fixing the compile failures.

**Comment by yuzibo** [comment]
> No, this wouldn't work, as it would be missing a few `.c` source files.
> 
> From the root of this repo, do the following:
> 
> ```
> cd binaries/org.eclipse.swt.gtk.linux.riscv64
> mvn clean process-resources -Dnative=gtk.linux.riscv64
> ```
> 
> If the compile fails (as it did to me for the `x86_64` arch), all the relevant `.c` source files will be available in the `target/natives-build-temp` directory, including the `build.sh` file. You can then re-invoke that `build.sh` to build the SWT binaries from there, after fixing the compile failures.

Thanks for pointing to this, I can confirm that it can be built with the command. Next I'll see how to add more support on riscv64.

Thanks again!

**Comment by yuzibo** [comment]
As discussed in [here](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2310), now Eclipse can support riscv64 natively, so I close the issue.
