### ISSUE TITLE
Build `swt` failed on v4967r3

### ISSUE THREAD

**Issue by yuzibo** [eclipse-platform/eclipse.platform.swt#1481]
Based on 02e20d69dcd, if use ` mvn clean verify  -DskipTests=true` we will get the below error. I am not sure this is bug or not. So if not, please close this.

```python
...
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:4.0.9:testCompile (default-testCompile) on
 project org.eclipse.swt.win32.win32.aarch64: Compilation failure: Compilation failure:
[ERROR] /home/debian/eclipse/vimer/eclipse.platform.swt/bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclip
se/swt/graphics/GCWin32Tests.java:[35]
[ERROR]         scaledGcNativeZoom.complete(event.gc.getGCData().nativeZoom);
[ERROR]                                                          ^^^^^^^^^^
[ERROR] nativeZoom cannot be resolved or is not a field
[ERROR] /home/debian/eclipse/vimer/eclipse.platform.swt/bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclip
se/swt/graphics/GCWin32Tests.java:[37]
[ERROR]         gcNativeZoom.complete(event.gc.getGCData().nativeZoom);
...
```

**Comment by HannesWell** [comment]
> I am not sure this is bug or not.

It indeed seems to be a bug, but in Tycho not in SWT. It occurs since we upgraded to Tycho 4.0.9 so something is wrong in that area.
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2360#issuecomment-2363386380.
Let's continue any discussion there.
This is kind of a duplicate, therefore I'm closing this.

**Comment by HeikoKlare** [comment]
If you need a workaround, you can execute maven with `-Dtycho.version=4.0.8` to use the previous Tycho version.

**Comment by yuzibo** [comment]
> If you need a workaround, you can execute maven with `-Dtycho.version=4.0.8` to use the previous Tycho version.

Okay, thanks for hinting.
