### ISSUE TITLE
[GTK] "Unsupported modifier, resource creation failed" error in Eclipse

### ISSUE THREAD

**Issue by joel-majano** [eclipse-platform/eclipse.platform.swt#151]
On latest Fedora 36 on GTK 4.6.3 upon launching Snippet 1 the following error appears.

```
Unsupported modifier, resource creation failed.
XXX: resource creation failed
```
Related links: 
1. https://github.com/alacritty/alacritty/issues/5967
2. https://bugs.webkit.org/show_bug.cgi?id=238513

**Comment by akurtakov** [comment]
I see such warnings when running Eclipse SDK on GTK3 too.

**Comment by joel-majano** [comment]
Closing as this is not Eclipse, this is a graphics driver issue.
