### ISSUE TITLE
[Win11] Styling with SWT.Skin listener breaks look

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#1573]
**Describe the bug**
If I add a Skin listener and set the foreground color of a checkbox, it looks too compact.

**To Reproduce**
Run the following snippet on Windows 11 with 150% zoom level.
```java
import java.io.*;

import org.eclipse.swt.*;
import org.eclipse.swt.layout.*;
import org.eclipse.swt.widgets.*;

public class HiDpiTest {
	public static void main(String[] args) throws IOException {
		final Display display = new Display();
		display.addListener(SWT.Skin, event -> {
			if (event.widget instanceof Button button && (button.getStyle() & SWT.CHECK) != 0) {
				button.setForeground(display.getSystemColor(SWT.COLOR_BLACK));
			}
		});

		final Shell shell = new Shell(display);
		shell.setLayout(new GridLayout(1, false));

		addCheckbox(shell);
		addCheckbox(shell).setSelection(true);
		addCheckbox(shell).setGrayed(true);

		final Button button = new Button(shell, SWT.PUSH);
		button.setText("Button");
		button.setLayoutData(new GridData(GridData.END, GridData.CENTER, false, false));

		shell.setSize(shell.computeSize(SWT.DEFAULT, SWT.DEFAULT));
		shell.open();
		while (!shell.isDisposed()) {
			if (!display.readAndDispatch()) {
				display.sleep();
			}
		}
		display.dispose();
	}

	private static Button addCheckbox(Composite parent) {
		final Button checkbox = new Button(parent, SWT.CHECK);
		checkbox.setText("Checkbox");
		checkbox.setLayoutData(new GridData(GridData.BEGINNING, GridData.CENTER, false, false));
		return checkbox;
	}
}
```
The checkbox text is too close to the box:
![2024-11-05 15_42_51-](https://github.com/user-attachments/assets/9d3a69ba-fea5-40fd-9690-f2a341534185)

With older SWT builds before commit 5dd0c286) it looks correctly:
![2024-11-05 15_43_26-](https://github.com/user-attachments/assets/7db77605-0665-46ec-972b-060dd1d3c377)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Windows 11, 4k monitor, 150% zoom level

**Version since**
 Eclipse or SWT version since when the behavior is seen [e.g. 4.23]

**Workaround (or) Additional context**
No known workaround.

**Comment by HeikoKlare** [comment]
@akoch-yatta @ShahzaibIbrahim maybe you can have a look at this?

**Comment by akoch-yatta** [comment]
I'll have a look @HeikoKlare

**Comment by Phillipus** [comment]
> With older SWT builds before commit https://github.com/eclipse-platform/eclipse.platform.swt/commit/5dd0c286133e703d5b203732577bbbd6025750e8) it looks correctly

Forgive me if I misunderstand but I thought that these recent changes to DPI on Windows were opt-in?

**Comment by HeikoKlare** [comment]
> Forgive me if I misunderstand but I thought that these recent changes to DPI on Windows were opt-in via a property argument?

That's mostly correct. The enhanced HiDPI support (monitor-specific rescaling at runtime) is opt-in. Still, there are also changes/improvements that unavoidably affect existing HiDPI support, but those changes should of course not produce regressions. We thoroughly test changes to not produce regressions in existing behavior. Actually, that's the primary goal, while proper functionality of the new opt-in functionality is only secondary goal.
