### ISSUE TITLE
SWT Browser component (Windows Edge): URLs sent to LocationListener are not complete

### ISSUE THREAD

**Issue by hmackamul** [eclipse-platform/eclipse.platform.swt#1581]
**Describe the bug**
In Eclipse APP4MC we are using SVG diagrams to show specific aspects of the data model.
The diagram is:
 - generated by PlantUML
 - displayed in SWT Browser component
 - contains links like **href="#obj37"**

The links are used to navigate in the model and select the corresponding object in the model editor (handled by a LocationListener).

The LocationListener of 
 -  **IE browser component** can be user to handle the clicks by analyzing the URL
 -  **Edge browser component** is not receiving the complete URL

**Details**
- IE links look like: `about:blank#obj37`
 - Edge links look like: `file:///C:/Users/abc/AppData/Local/Temp/base12703840119113867392.html#obj37`
 - Browser is setup with LocationListener like this:
    ```
   browser.addLocationListener(LocationListener.changingAdapter(c -> {
        int idx = c.location.lastIndexOf('#');
        if (idx >= 0) {
            <compute link to object>
            <sent (topic + link) to IEventBroker to select object in editor>
        }
    }));
    ```

**Screenshots**
![SVG_displayed_in_SWT_Browser](https://github.com/user-attachments/assets/9876f019-68b9-4c2d-864e-8c235d882509)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Windows 11
 
**Version**
 Eclipse 2024-12 M2

**Comment by sratz** [comment]
The behavior with regards to fragments broke with the recent changes to the location events (#1451).

@hmackamul Could you test whether #1584 fixes the issue for your use-case?

**Comment by hmackamul** [comment]
> The behavior with regards to fragments broke with the recent changes to the location events (#1451).
> 
> @hmackamul Could you test whether #1584 fixes the issue for your use-case?

I downloaded the integration build from yesterday evening but the pull request (#1584) is not included there.
Do you have a simple possibility to test the patch?
(I do not have the SWT repos/builds locally)

**Comment by sratz** [comment]
> Do you have a simple possibility to test the patch?

Can you try with this win32 fragment?
https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-1584/2/execution/node/3/ws/eclipse.platform.swt/binaries/org.eclipse.swt.win32.win32.x86_64/target/org.eclipse.swt.win32.win32.x86_64-3.128.0-SNAPSHOT.jar

**Comment by hmackamul** [comment]
> Can you try with this win32 fragment? https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-1584/2/execution/node/3/ws/eclipse.platform.swt/binaries/org.eclipse.swt.win32.win32.x86_64/target/org.eclipse.swt.win32.win32.x86_64-3.128.0-SNAPSHOT.jar

Sorry, I got:
Access Denied
... is missing the Job/Workspace permission

**Comment by sratz** [comment]
> > Can you try with this win32 fragment? https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-1584/2/execution/node/3/ws/eclipse.platform.swt/binaries/org.eclipse.swt.win32.win32.x86_64/target/org.eclipse.swt.win32.win32.x86_64-3.128.0-SNAPSHOT.jar
> 
> Sorry, I got: Access Denied ... is missing the Job/Workspace permission

Hmm, weird, I was able to download even without logon from incognito.

Here it is (rename .zip to .jar):
[org.eclipse.swt.win32.win32.x86_64-3.128.0.v20241110-0844.zip](https://github.com/user-attachments/files/17711119/org.eclipse.swt.win32.win32.x86_64-3.128.0.v20241110-0844.zip)

**Comment by hmackamul** [comment]
Thanks, I got the file and will test it.

**Comment by hmackamul** [comment]
Sorry, I was not able to test the fragment.

My attempt:
 - Downloaded Eclipse 2024-12 integration build
	* https://download.eclipse.org/eclipse/downloads/drops4/I20241110-1800/
 - Replaced files in **plugins** folder
 	* org.eclipse.swt.win32.win32.x86_64.source_3.128.0.v20241107-1257.jar
 	* org.eclipse.swt.win32.win32.x86_64_3.128.0.v20241107-1257.jar
  - with your new file
 	* org.eclipse.swt.win32.win32.x86_64-3.128.0.v20241110-0844.jar

Result was 
[1731417804740.log](https://github.com/user-attachments/files/17717418/1731417804740.log)

Any idea?

**Comment by HeikoKlare** [comment]
You will probably have to adapt the configuration in your installation folder under `configuration/org.eclipse.equinox.simpleconfigurator/bundles.info`. There should be a line referring to the SWT fragment, in which you have to adapt the version so that the fragment is properly resolved at startup.

**Comment by hmackamul** [comment]
Thanks for the hint. With the update of simpleconfigurator I could start the fragment.
![capture_2024-11-12_205202_001](https://github.com/user-attachments/assets/79c62174-1b11-40e1-be65-81c5f7c6ddaf)

But no reaction in the editor. I assume the LocationEvent with for #fragment navigation is still missing.

**Comment by sratz** [comment]
> But no reaction in the editor. I assume the LocationEvent with for #fragment navigation is still missing.

According to your initial post in this issue you are only reacting to the `changing` event:

```
browser.addLocationListener(LocationListener.changingAdapter(c -> {
    int idx = c.location.lastIndexOf('#');
    if (idx >= 0) {
        <compute link to object>
        <sent (topic + link) to IEventBroker to select object in editor>
    }
}));
```

Edge however does not send out any event *before* fragment navigation that we could forward via a `changing` event and it is impossible to cancel such a fragment navigation event.

Edge only sends out an event *after* the navigation, which we forward as a `changed` event in the `LocationListener`.

You'd have to adapt your code to
```diff
- browser.addLocationListener(LocationListener.changingAdapter(c -> {
+ browser.addLocationListener(LocationListener.changedAdapter(c -> {
    int idx = c.location.lastIndexOf('#');
    if (idx >= 0) {
        <compute link to object>
        <sent (topic + link) to IEventBroker to select object in editor>
    }
}));
```

**Comment by hmackamul** [comment]
Thanks!
The changed event works perfectly with Edge.

https://github.com/user-attachments/assets/4e90a29d-ec23-45a7-8c77-f6d384ebd5f4

**Comment by hmackamul** [comment]
Some more results (for the records):

1. LocationListener.changed does not work with WebKit under Linux

2. In case of links generated by PlantUML:

    - Internet Explorer shows a unwanted behavior (other than Edge):
        - after klick a blank page is shown
    - Generated links looked like:
         - &lt;a href="#obj1"
		    **target="_top"**
		    title="#obj1"
		    xlink:actuate="onRequest"
		    xlink:href="#obj1"
		    **xlink:show="new"**
		    xlink:title="#obj1"
		    xlink:type="simple"&gt;

I fixed the problems in my application by
* filtering the generated PlantUML code (remove the 'target' and 'xlink:show' attributes)
* using the 'changed' listener only under Windows (other platforms keep listening for 'changing')

It is possible to handle the different behavior but it makes it harder to write platform independent applications.
