### ISSUE TITLE
[24] Investigate? JEP 479: Remove the Windows 32-bit x86 Port 

### ISSUE THREAD

**Issue by mpalat** [eclipse-platform/eclipse.platform.swt#1633]
**Describe the bug**
Refer to [JEP 479](https://openjdk.org/jeps/479) - leaving to SWT folks to investigate the impact of the same.

Also to https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3295

**To Reproduce**
Refer to [JEP 479](https://openjdk.org/jeps/479) 

**Expected behavior**
Win32 support is going away 

**Screenshots**

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

3. JRE/JDK version

**Version since**
JDT Version 24

**Workaround (or) Additional context**
Any known workarounds for the problem?

**Comment by laeubi** [comment]
SWT already has dropped 32 bit support a long while ago:

https://github.com/eclipse-platform/eclipse.platform.swt/tree/master/binaries

**Comment by mpalat** [comment]
ok. So this is a non-issue then for SWT. thanks
