### ISSUE TITLE
org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.test_TabTraversalOutOfBrowser fails intermittently, both on IE and on Edge

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.swt#1656]
The test fails locally and it can fail with both browsers on Windows.

I ran the test using the parameterized version of the test class `org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser` that can be found in #672 (I disabled all other tests in the class to speed up the testing), I swapped the parameters around and also enabled/disabled them, just for fun, and this is what I saw:

![image](https://github.com/user-attachments/assets/b36cb90f-7ffd-40e6-9b0a-5c291a5742ab)
---

![image](https://github.com/user-attachments/assets/2e99d9a8-9692-4dcc-b85d-c3e078853004)
---

![image](https://github.com/user-attachments/assets/f8d73434-7daa-4f30-a680-b42923ccd4b5)
---

![image](https://github.com/user-attachments/assets/64fbfb5d-e3c5-458c-a642-cb48897698aa)
---

![image](https://github.com/user-attachments/assets/a8fe6170-35db-4e24-a33d-c830fb69d7ba)
---

**Note: `[browser flags: 0]` means _Edge_ and `[browser flags: 524,288]` means _IE_**

The only combination that I couldn't get was: First Edge then IE and **both** failing... but I can't say that one won't fail either.

**Comment by HeikoKlare** [comment]
Browser tests are still executed with IE, not with Edge, see:
- #671
- #672 

So failure seems to occur with IE. The test has just been introduced via:
- #1641

**Comment by fedejeanne** [comment]
@jukzi just for the record, this is a regression in a test and **not** in productive code. In productive code I tested the snippet provided in https://github.com/eclipse-platform/eclipse.platform.swt/issues/1640#issue-2727327071 and it worked, both for IE and for Edge.

**Comment by jukzi** [comment]
Thanks for clarification. I also put labels regression+test on tests that started to fail.

**Comment by sratz** [comment]
I think the `Display.getDefault().post(event)` is really fragile.

I don't think there is any other way to simulate an event that is supposed to original from within the browser.

Maybe we'd need to remove the test again.

**Comment by fedejeanne** [comment]
It failed again in yesterday's I-BUILD: https://download.eclipse.org/eclipse/downloads/drops4/I20241217-1800/testresults/html/org.eclipse.swt.tests_ep435I-unit-win32-x86_64-java21_win32.win32.x86_64_21.html

@sratz do you think it's worth leaving it active?

**Comment by sratz** [comment]
> @sratz do you think it's worth leaving it active?

Probably not, I guess this kind of `let's send an event and hope the right control is active / has focus` test is just too fragile.
