### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Could not load SWT library

### ISSUE THREAD

**Issue by AlBundy33** [eclipse-platform/eclipse.platform.swt#1669]
**Describe the bug**
Statically loading a class that extends Scrollable ends in this exception on headless servers (e.g. ci/cd pipelines)

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-pi4-gtk-4934r6 in java.library.path: [/opt/java/openjdk/lib/server, /opt/java/openjdk/lib, /opt/java/openjdk/../lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	no swt-pi4-gtk in java.library.path: [/opt/java/openjdk/lib/server, /opt/java/openjdk/lib, /opt/java/openjdk/../lib, /usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
	Can't load library: /root/.swt/lib/linux/x86_64/libswt-pi4-gtk-4934r6.so
	Can't load library: /root/.swt/lib/linux/x86_64/libswt-pi4-gtk.so
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:342)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:256)
	at org.eclipse.swt.internal.gtk.OS.<clinit>(OS.java:90)
	at org.eclipse.swt.widgets.Scrollable.<clinit>(Scrollable.java:44)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
....
```
It seems that this call
https://github.com/eclipse-platform/eclipse.platform.swt/blob/603eecdebc52c09897d4916fbef5e566de216c66/bundles/org.eclipse.swt/Eclipse%20SWT/gtk/org/eclipse/swt/widgets/Scrollable.java#L46
causes the load of a native library
https://github.com/eclipse-platform/eclipse.platform.swt/blob/603eecdebc52c09897d4916fbef5e566de216c66/bundles/org.eclipse.swt/Eclipse%20SWT%20PI/gtk/org/eclipse/swt/internal/gtk/OS.java#L82

we are analyzing the classes during our build and therefore load classes with Class.forName

I think we have this error wirh RCP 4.16 (have to check this in detail if necessary)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [x] Linux
- - [ ] macOS

**Comment by janesser** [comment]
same here, when trying to build eclipse-based product; which happens to lack some required library

in the hosting eclipse-instance files like these can be found
```
find $SNAP_USER_DATA -name "libswt*"
/home/jan/snap/eclipse-pde/x7/amd64/configuration/org.eclipse.osgi/477/0/.cp/libswt-webkit-gtk-4967r8.so
/home/jan/snap/eclipse-pde/x7/amd64/configuration/org.eclipse.osgi/477/0/.cp/libswt-gtk-4967r8.so
/home/jan/snap/eclipse-pde/x7/amd64/configuration/org.eclipse.osgi/477/0/.cp/libswt-atk-gtk-4967r8.so
/home/jan/snap/eclipse-pde/x7/amd64/configuration/org.eclipse.osgi/477/0/.cp/libswt-cairo-gtk-4967r8.so
/home/jan/snap/eclipse-pde/x7/amd64/configuration/org.eclipse.osgi/477/0/.cp/libswt-pi3-gtk-4967r8.so
```

on the contrary the built eclipse-product only has 
```
.metadata/.plugins/org.eclipse.pde.core/archi.product/org.eclipse.osgi/185
.metadata/.plugins/org.eclipse.pde.core/archi.product/org.eclipse.osgi/185/0
.metadata/.plugins/org.eclipse.pde.core/archi.product/org.eclipse.osgi/185/0/.cp
.metadata/.plugins/org.eclipse.pde.core/archi.product/org.eclipse.osgi/185/0/.cp/libswt-gtk-4967r8.so
```

pointers of where to dig deeper are welcome.

**Comment by AlBundy33** [comment]
I think my exception is different from yours - I just try to load a class-file that extends Scrollable.
Simple example `Class.forName("org.eclipse.swt.widgets.Composite")`
which nitialize the static fields like RESIZE_ON_GETCLIENTAREA which need to load the OS-class that tries to load swt-libraries which result in an exception if gtk is not installed.
imho this should be avoided (e.g. with a static method instead RESIZE_ON_GETCLIENTAREA) because gtk should be no prerequirement for loading classes because it is not available in build environments ci/cd pipelines etc.

and if you would ask why it's root operating in this case I would answer because I've tried this in a local docker container without graphical environment to get the stacktrace. 😉

**Comment by iloveeclipse** [comment]
> because gtk should be no prerequirement for loading classes

I believe your expectation cannot be ever satisfied in the **GTK** SWT port. SWT GTK port is a library that depends on GTK. So if some classes need GTK code to be loaded, it is not a bug.

My recommendation for your use case is to avoid loading classes via Class.forName() and inspect their bytecode instead.

**Comment by AlBundy33** [comment]
@iloveeclipse this was just an example - our use case is more like this:

We have a lot ui classes like
```
@SomeAnnotation()
public class SomeFancyDialog extends Composite {
...
}
```
To find all classes annotated with @SomeAnnotation we have to load our classes with Class.fiorName and read the annotations.
And because the dialogs extends Composite the UnsatisfiedLinkError is thrown as described above and we are not able to read the annotations.

**Comment by iloveeclipse** [comment]
> To find all classes annotated with @SomeAnnotation we have to load our classes with Class.fiorName

Once again, the best, fastest and safest way to do it is to inspect bytecode, for example with ASM.
