### ISSUE TITLE
[Win32] Broken compatibility with swt.autoScale=false

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#1671]
**Describe the bug**
Because of [serious painting problems on Windows](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1596) we have to set `swt.autoScale` to `false` and use `display.getDPI()` to (indirectly) find out the zoom level. However, build c66545ba broke this compatibility.

**To Reproduce**
Run this snippet
```java
import org.eclipse.swt.*;
import org.eclipse.swt.graphics.*;
import org.eclipse.swt.widgets.*;

public class AutoScaleFalseTest {

	public static void main(String[] args) {
		System.getProperties().putIfAbsent("swt.autoScale", "false");

		final Display display = new Display();

		final Shell shell = new Shell(display);
		shell.addListener(SWT.Paint, event -> {
			final String deviseZoom = System.getProperty("org.eclipse.swt.internal.deviceZoom");
			event.gc.drawString(deviseZoom, 0, 0);
			final Point dpi = display.getDPI();
			event.gc.drawString(String.valueOf(dpi), 0, 30);
		});

		shell.setSize(400, 300);
		shell.open();

		while (!shell.isDisposed()) {
			if (!display.readAndDispatch()) {
				display.sleep();
			}
		}

		display.dispose();
	}
}
```
on commit 40b4fc6c and on commit c66545ba on a system with 4k monitor set to 150% zoom level. The first will report correctly 144 dpi, the latter 96dpi.

**Expected behavior**
If `swt.autoScale` is set to `false`, no autoscaling must happen.

**Screenshots**
Commit 40b4fc6c:
<img width="191" alt="40b4fc6c" src="https://github.com/user-attachments/assets/130458ba-1cdc-4f21-89f5-b5e9d04ed10d" />

Commit c66545ba:
<img width="191" alt="c66545ba" src="https://github.com/user-attachments/assets/29ee06a7-2219-4ce7-bcab-d98d4a304ccd" />

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
We are Win11 24H2, but this should not have any influence.

**Workaround (or) Additional context**
Nothing known.

**Comment by akoch-yatta** [comment]
There is already PR #1646 that should restore the previous behavior

**Comment by tmssngr** [comment]
Yes, thanks, this fixes the problem for me.
