### ISSUE TITLE
GH Actions failing since today

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.swt#1683]
**Describe the bug**
Starting today, several [SWT Matrix Build Actions](https://github.com/eclipse-platform/eclipse.platform.swt/actions/workflows/maven.yml) fail with this error: 

```java
Warning:  The POM for org.eclipse.jdt:ecj:jar:3.41.0-SNAPSHOT is missing, no dependency information available
[INFO] Downloading from eclipse-snapshots: https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/jdt/ecj/3.41.0-SNAPSHOT/ecj-3.41.0-SNAPSHOT.jar
Error: [ERROR] Internal error: java.lang.RuntimeException: org.apache.maven.plugin.PluginResolutionException: Plugin org.eclipse.tycho:tycho-compiler-plugin:4.0.10 or one of its dependencies could not be resolved:
Error:  	Could not find artifact org.eclipse.jdt:ecj:jar:3.41.0-SNAPSHOT in eclipse-snapshots (https://repo.eclipse.org/content/repositories/eclipse-snapshots/)
Error:  -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: org.apache.maven.plugin.PluginResolutionException: Plugin org.eclipse.tycho:tycho-compiler-plugin:4.0.10 or one of its dependencies could not be resolved:
	Could not find artifact org.eclipse.jdt:ecj:jar:3.41.0-SNAPSHOT in eclipse-snapshots (https://repo.eclipse.org/content/repositories/eclipse-snapshots/)

    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:109)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:906)
...
```

The error message says that there is no **POM** file under https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/jdt/ecj/3.41.0-SNAPSHOT/, which is correct, but what I don't understand is how did it work before since there are no POM files under other folders of https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/jdt/ecj/ either.

**Screenshots**

![image](https://github.com/user-attachments/assets/3f9194a4-7427-4d68-aa2f-6a3831b32a8b)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [x] All OS
- - [ ] Windows
- - [ ] Linux
- - [ ] macOS 

**Version since**
It seems to be failing starting **today**

**Workaround (or) Additional context**
None that I know of. I re-triggered the builds but it fails consistently in my case.

**Comment by fedejeanne** [comment]
@laeubi , @HannesWell , @merks any hints?

**Comment by akurtakov** [comment]
We had similar issue couple of weeks ago https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5387 . Please engage with EF infra team to be investigated.

**Comment by merks** [comment]
Note that these files are new as of a couple of hours ago (because someone messed up the cron figuration of

https://ci.eclipse.org/releng/view/Publish%20to%20Maven/job/CBIaggregator/

so that job was no longer running and new ecj versions stopped being produced.

Perhaps some mirror/cache system needs to get caught up.  😭

**Comment by fedejeanne** [comment]
Thank you both, I commented in the existing ticket (https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5387) since it seems to be the exact same error as before:

**Comment by merks** [comment]
I created this new issue because it's best there be an **open** issue:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5454

**Comment by akurtakov** [comment]
This has been resolved.
