### ISSUE TITLE
Mac: opening font dialog causes warning message in log

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.swt#17]
macOS 12.3.1
M1 Mac Mini
Eclipse Version: 2022-03 (4.23)
Eclipse Build id: I20220308-0310

1. Launch child Eclipse
2. Set a font in Preferences
3. When the FontDialog opens this is written to the log:

`java[3258:51770] It's not legal to call -layoutSubtreeIfNeeded on a view which is already being laid out.  If you are implementing the view's -layout method, you can call -[super layout] instead. Break on void _NSDetectedLayoutRecursion(void) to debug.  This will be logged only once.  This may break in the future.`

It occurs at line 178 in `org.eclipse.swt.widgets.FontDialog`:

`panel.orderFront(null);`

Not sure if this is an indication of something important or not. Thought I'd open an issue, just in case.

**Comment by lshanmug** [comment]
I'm unable to reproduce this error on x86_64, does it happen only on M1?

**Comment by Phillipus** [comment]
Yes, only on M1 with macOS 12.3.1.

**Comment by Phillipus** [comment]
On further investigation, I don't think this is an SWT thing, or at least it's not related to `org.eclipse.swt.widgets.FontDialog` and I don't think there's anything that can be changed.

When I debug and launch our RCP app from Eclipse, and then open the Font dialog from the RCP app, then close the RCP app, the next time I debug/launch the RCP app the Font dialog automatically opens without user intervention. Somehow its "open" state gets saved to `~/Library/Saved Application State`. Anyway, because the Font Dialog is being opened by macOS, a `org.eclipse.swt.widgets.FontDialog` is not created, but the warning message is still written to the log. So this must be a Mac thing.

**Comment by Phillipus** [comment]
Test Snippet

```java
import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.*;
import org.eclipse.swt.widgets.*;

public class FontDialogTest {

    public static void main(String[] args) {
        final Display display = new Display();
        final Shell shell = new Shell(display);
        shell.setLayout(new GridLayout(1, true));

        Button button = new Button(shell, SWT.PUSH);
        button.setText("Font...");
        button.addListener(SWT.Selection, e -> {
            new FontDialog(shell).open();
        });

        shell.open();

        while(!shell.isDisposed()) {
            if(!display.readAndDispatch()) {
                display.sleep();
            }
        }

        display.dispose();
    }
}
```

**Comment by Phillipus** [comment]
The warning message doesn't occur on macOS Ventura Beta 4, so maybe this issue can be closed when Ventura full release happens.

**Comment by Phillipus** [comment]
This message occurs on macOS 12.6.3 but not 13.2 so I think we should close this one.
