### ISSUE TITLE
SWT GitHub Actions not able to capture failing JUnit similar to Jenkins CI.

### ISSUE THREAD

**Issue by niraj-modi** [eclipse-platform/eclipse.platform.swt#170]
Idea is to bring Github PR validation at par with Jenkins CI validation:
- Raised this issue to captured the problem noticed during #165 review:
https://github.com/eclipse-platform/eclipse.platform.swt/pull/165#issuecomment-1135984331

**Comment by akurtakov** [comment]
GH Action is running and reporting tests. Format is different and sometimes failing tests due to Jenkins using CentOS and GH Ubuntu with all the changes in underlying libraries. I close this one now as quite a lot of things has changed since then and the mentioned tests are no longer failing.
