### ISSUE TITLE
[win32][DarkTheme] Text's SWT.ICON_SEARCH and SWT.ICON_CANCEL are hard to see in dark theme

### ISSUE THREAD

**Issue by SyntevoAlex** [eclipse-platform/eclipse.platform.swt#18]
Here's an example from our app:
![image](https://user-images.githubusercontent.com/45797751/161351599-b090d06c-be70-40f9-a871-2da09ef50a4f.png)

**Comment by SyntevoAlex** [comment]
I'll make a patch.

**Comment by vogella** [comment]
> I'll make a patch.

Cool :-)

**Comment by SyntevoAlex** [comment]
And you'll make the N&N if necessary, is that a deal? 😇

**Comment by vogella** [comment]
> And you'll make the N&N if necessary, is that a deal? innocent

+1 :-)

**Comment by SyntevoAlex** [comment]
Snippet attached in patch, before and after:
![Snippet_Before](https://user-images.githubusercontent.com/45797751/161354346-53616d44-e475-49cc-9a59-cc0868516433.png)
![Snippet_After](https://user-images.githubusercontent.com/45797751/161354349-da5feda8-2928-4c6a-8d4a-8a6c1906ec60.png)

Eclipse, before and after:
![Eclipse_Before](https://user-images.githubusercontent.com/45797751/161354355-30f6100c-3c4a-48a1-b8e2-cb5170637484.png)
![Eclipse_After](https://user-images.githubusercontent.com/45797751/161354358-a8e66db7-128e-40df-8e90-152bb2396679.png)

**Comment by SyntevoAlex** [comment]
@vogella testing is welcome. If you're lazy though, I could just merge it and hope that the world still stands tomorrow :)

**Comment by SyntevoAlex** [comment]
Note that this change requires native libs to be rebuilt.

**Comment by Phillipus** [comment]
FWIW, I tested this and it looks good to me (at least better than before ;-) )

**Comment by niraj-modi** [comment]
Tested the fix Search and close buttons look better now but it seems the mouse hover on the Close button is coming in light:
<img width="327" alt="Win10_DarkTheme_CloseButton_MouseHover_looks_light" src="https://user-images.githubusercontent.com/92304759/161689575-d7319bc8-1607-47ad-b536-7179eb0294d7.png">

**Comment by SyntevoAlex** [comment]
Thanks for catching! I didn't see that because it only occurs on Win10 and I'm on Win11.
Improved via https://github.com/eclipse-platform/eclipse.platform.swt/pull/23, please test

**Comment by SyntevoAlex** [comment]
![PatchV1V2](https://user-images.githubusercontent.com/45797751/161903806-60cef0cb-1992-47ce-bd85-d3ce0a222b0b.png)

**Comment by niraj-modi** [comment]
Thanks Alexandr for the fix. Once N&N is done, we can close this.

**Comment by niraj-modi** [comment]
Will add an SWT N&N entry shortly.

**Comment by niraj-modi** [comment]
> Will add an SWT N&N entry shortly.

Added below:
https://www.eclipse.org/eclipse/news/4.24/platform_isv.php#win32-dark-Text-search-cancel-buttons

Thanks Alexandr for this improvement, closing for 4.24 M1

**Comment by vogella** [comment]
Thanks @niraj-modi for the N&N entry.

**Comment by vogella** [comment]
And @SyntevoAlex for the implementation
