### ISSUE TITLE
Test failure in TextLayout.test_getLineOffsets on Mac since I20220606-1800

### ISSUE THREAD

**Issue by lshanmug** [eclipse-platform/eclipse.platform.swt#201]
Test failure in TextLayout.test_getLineOffsets on Mac since I20220606-1800

https://download.eclipse.org/eclipse/downloads/drops4/I20220606-1800/testresults/html/org.eclipse.swt.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

Test doesn't fail locally but seems to happen after https://github.com/eclipse-platform/eclipse.platform.swt/commit/4409473e40eb841b9fa4d91780b76f7eca08b409

@akurtakov

**Comment by akurtakov** [comment]
If it doesn't happen locally, it's most probably unstable test. Let's see few more builds.

**Comment by Phillipus** [comment]
I was interested in testing this locally on macOS, and for me the test fails every time:

```
array lengths differed, expected.length=4 actual.length=3; arrays first differed at element [3]; expected:<15> but was:<end of array>
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:89)
```

**Comment by akurtakov** [comment]
@Phillipus would you please revert https://github.com/eclipse-platform/eclipse.platform.swt/commit/4409473e40eb841b9fa4d91780b76f7eca08b409 and tell us whether issue still persist. I would have done it myself but I don't have access to Mac.

**Comment by Phillipus** [comment]
@akurtakov The test passes by reverting that commit.

**Comment by akurtakov** [comment]
Thanks for confirmation. I fail to see why it happens thus I'll revert the changes in test_getLineOffsets method only.

**Comment by Phillipus** [comment]
I'm looking at it. I can't see why `assertArrayEquals` should fail. I'll investigate...

**Comment by Phillipus** [comment]
offsets size is 3 not 4

`[0, 8, 15]`

**Comment by akurtakov** [comment]
How/why does it work at all with the old test at all?

**Comment by Phillipus** [comment]
> How/why does it work at all with the old test at all?

Because it's not comparing array length.

**Comment by akurtakov** [comment]
OK, so this is not caused by my change but a fix in Mac port is needed. I can get back to finding why Gtk tests are failing in that case. Thanks, @Phillipus for helping narrow the issue.

**Comment by Phillipus** [comment]
Indeed. Your new test is correct and reveals the underlying problem. Original test was missing `assertEquals(expected.length, offsets.length);`

**Comment by Phillipus** [comment]
If it's any help to debug the underlying issue on macOS:

On Windows, with the string `0123456\n890123\n` `TextLayout.getLineOffsets` returns an array of ints `[0, 8, 15, 15]`. 

According to javadoc:

> Each value in the array is the offset for the first character in a line except for the last value, which contains the length of the text.
 
However, on macOS we get `[0, 8, 15]`. It is missing the last offset from the last `\n` in the string. 

Using string `0123456\n0123456\n0123` in the test returns `[0, 8, 16, 20]` which is correct. It does not have `\n` as the last character. So it seems the macOS version of `TextLayout.getLineOffsets` is not calculating the last `\n` character.

**Comment by lshanmug** [comment]
Thanks for the analysis @Phillipus. Looks like the lineCount is not computed correctly when there is a trailing \n. getLineCount() also returns the incorrect value in that case. Fixing the lineCount should fix both APIs.

**Comment by lshanmug** [comment]
Test passes in the latest I-builds - https://download.eclipse.org/eclipse/downloads/drops4/I20220626-1800/testresults/html/org.eclipse.swt.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

**Comment by lshanmug** [comment]
Reverted this change due to https://github.com/eclipse-platform/eclipse.platform.swt/issues/249. Will update the test for  Mac accordingly.
