### ISSUE TITLE
[win32] HDC leak in Image.createGdipImage()

### ISSUE THREAD

**Issue by SyntevoAlex** [eclipse-platform/eclipse.platform.swt#21]
[Bug 493455](https://bugs.eclipse.org/bugs/show_bug.cgi?id=493455) accidentally removed `device.internal_dispose_GC(hDC, null)` from `Image.createGdipImage()` on win32, which now leaks one `HDC` per image created. Note that `GC.drawImage()` may create the image internally.

As the leak grows, Windows get slower. When leak reaches 10000 (default maximum for one process), SWT will begin to throw `SWT.error()` and UI begins to malfunction.

I'll provide a patch.

**Comment by SyntevoAlex** [comment]
This is a serious regression. It makes entire Windows slower. Also, when leak reaches 10000, application either dies on `SWT.ERROR_NO_HANDLES` exception, or, if exceptions are consumed, UI gets completely broken - various parts will not be painted, buttons can't be pushed, and it's not even possible to close app without Task manager.

**Comment by iloveeclipse** [comment]
To be more precise, this was the change here:

https://github.com/eclipse-platform/eclipse.platform.swt/commit/22797d3f9f09ca67bfd29c864f2aaf8eb452c75c#r70580523

Thanks Alex, I can reproduce & verified the fix is working.

**Comment by niraj-modi** [comment]
> To be more precise, this was the change here:
> 
> [22797d3#r70580523](https://github.com/eclipse-platform/eclipse.platform.swt/commit/22797d3f9f09ca67bfd29c864f2aaf8eb452c75c#r70580523)
> 
> Thanks Alex, I can reproduce & verified the fix is working.

Thanks Alexandr/Andrey, closing for 4.24 M1
