### ISSUE TITLE
Empty java-doc hover tool-tip with Edge browser in Eclipse

### ISSUE THREAD

**Issue by niraj-modi** [eclipse-platform/eclipse.platform.swt#212]
**Describe the bug**
This bug is to support Edge based JavaDoc tooltip in Eclipse, original bugzilla bug report:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=571278

**To Reproduce**
When Eclipse is launched with Edge browser:
- Empty Java-doc hover tool-tip is seen with Java Editor.

**Expected behavior**
Java-doc contents should be shown similar to embedded IE.

**Screenshots**
https://bugzillaattachments.eclipsecontent.org/bugs/attachment.cgi?id=285441

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

3. JRE/JDK version
 
**Version since**
 4.19

**Workaround (or) Additional context**
Use embedded IE instead of Edge.

**Comment by felipeaf** [comment]
I'm not sure if i should open a new bug or comment here, but i'm having a similar bug in UBUNTU 22.04, with blanck tool-tip and blank internal web browser. Just after opens it works for a few minutes, but something triggers the bug and then, all java-doc hover tool-tip looks exactly like this screenshot. Same with the Internal web browser, it works right after starting Eclipse, but soon all new browser window keeps blank.

**Comment by akurtakov** [comment]
@felipeaf It's definitely different bug as the underlying browser engine under Ubuntu is not MS Edge.

**Comment by 0x3b879** [comment]
Same issue with Debian 11, MS Edge and Version: 2022-09 (4.25.0) Build id: 20220908-1902.

**Comment by akurtakov** [comment]
> Same issue with Debian 11, MS Edge and Version: 2022-09 (4.25.0) Build id: 20220908-1902.

There is no way you can use MS Edge in SWT on Linux, SWT has absolutely zero knowledge about Edge under Linux and will never try to load it.

**Comment by mfvalenta** [comment]
This is not an SWT issue. Please see my comment on https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/248 for information on how to address the issue in JDT.

**Comment by amartya4256** [comment]
Fixed with https://github.com/eclipse-platform/eclipse.platform.swt/pull/1395
