### ISSUE TITLE
Welcome page has missing color and styling with Edge browser in Eclipse

### ISSUE THREAD

**Issue by niraj-modi** [eclipse-platform/eclipse.platform.swt#213]
**Describe the bug**
This bug is to support improved Edge based Welcome page in Eclipse, original bugzilla bug report:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=578700

**To Reproduce**
When Eclipse is launched with Edge browser:
- Welcome page has missing color and styling.

**Expected behavior**
Welcome page should show color and styling similar to embedded IE.

**Screenshots**
https://bugzillaattachments.eclipsecontent.org/bugs/attachment.cgi?id=285442

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

3. JRE/JDK version
 
**Version since**
 4.19

**Workaround (or) Additional context**
 Use embedded IE instead of Edge.

**Comment by thegreystone** [comment]
This one would be very interesting for https://github.com/openjdk/jmc. The embedded IE is old enough that most new views in Mission Control (that are using various popular Java Script visualization frameworks) do not work on Windows. Not being able to load local resources is a huge problem.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/456

**Comment by thegreystone** [comment]
Also, see https://bugs.openjdk.org/browse/JMC-7118.

**Comment by viragpurnam** [comment]
Hi, we have a similar requirement. We have designed some views using Java Script. These views work absolutely fine on Mac and Linux platforms but not on Windows. Unfortunately, most of the users are on windows and they are not able to use these views. (These views are the main feature of the tool). ** Could you please take this bug on priority? ** This will surely help many developers. Thanks. Looking forward for a positive response.

**Comment by laeubi** [comment]
>  Could you please take this bug on priority?

You can contact the Eclipse-WG and offer some funding for this particular issue getting fixed:

https://eclipseide.org/working-group/#members

> This will surely help many developers. 

... or some of the "many developers" can take a look and provide a PR to fix this.

**Comment by Phillipus** [comment]
Correct me if I'm wrong, but my understanding is that calling `Browser.setText("some html")` where the html text includes references to local files (CSS and JS) is not permitted by Edge, so Welcome page doesn't display. Therefore this can't be fixed in Eclipse and SWT.

`BrowserIntroPartImplementation` calls `Browser#setText()` for HTML based Intro pages and so local images and CSS file are not loaded as noted [here](https://bugs.eclipse.org/bugs/show_bug.cgi?id=571278#c1).

In our app we only have one welcome page so I inlined the CSS and converted images to embedded Bas64 strings into a  single HTML page.

> Could you please take this bug on priority?

Have you come up with a fix or workaround yet?

**Comment by Phillipus** [comment]
For reference, the issue arises when calling `Browser#setText()` which in the `org.eclipse.swt.browser.Edge` class calls the `ICoreWebView2#NavigateToString`  method.

The [MS documentation](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/working-with-local-content?tabs=dotnetcsharp#additional-web-resources-1) for this says:

> Loading local content by using the `NavigateToString` method doesn't make it possible for the resulting document to reference additional web resources such as CSS, image, or script files. The method only lets you specify the string content of the HTML document. To reference additional web resources from your HTML document, use one of the other approaches described in this article, or represent those additional web resources inline in the HTML document.

**Comment by amartya4256** [comment]
Fixed with https://github.com/eclipse-platform/eclipse.platform.swt/pull/1395
