### ISSUE TITLE
[Documentation] Tried to install swt but ...

### ISSUE THREAD

**Issue by rubyFeedback** [eclipse-platform/eclipse.platform.swt#257]
Hey guys,

I am using swing right now. I know, I know, outdated ... but it works. And it is simple. Ugly but
simple.

Anyway. I wanted to try out JavaFX but I had issues with the installation. So I went back to
swing. I lack tenacity. :P

Others recommended swt. Ok. I want to install it.

Well:

https://www.eclipse.org/swt/

I click through and end up on:

https://download.eclipse.org/eclipse/downloads/drops4/R-4.24-202206070700/testResults.php

Please guys - what the heck is this? Just the URL alone, but all the confusing content.

I thought It is a download link, instead it is some link that tells me what the content of it
all is? Hmmm.

Ok so I go back to:

https://www.eclipse.org/swt/

This time I go to stable builds.

https://download.eclipse.org/eclipse/downloads/index.html#Stable_Builds

Let me copy/paste what I see:

    Build Name 	Build Status 	Build Date
    I20220713-0100 	Build is available Integration tests are running ...  (5 of 6 platforms) 	Wed, 13 Jul 2022 -- 01:00 (-0400)
    I20220712-1800 	Build is available Tests results are available  (6 of 6 platforms) 	Tue, 12 Jul 2022 -- 18:00 (-0400)
    I20220712-0820 	Build is available Tests results are available  (6 of 6 platforms) 	Tue, 12 Jul 2022 -- 08:20 (-0400)
    I20220710-1800 	Build is available Tests results are available  (6 of 6 platforms) 	Sun, 10 Jul 2022 -- 18:00 (-0400)
    I20220709-1800 	Build is available Tests results are available  (6 of 6 platforms) 	Sat, 9 Jul 2022 -- 18:00 (-0400)
    I20220709-0920 	Build is available Tests results are available  (6 of 6 platforms) 	Sat, 9 Jul 2022 -- 09:20 (-0400)
    I20220706-1800 	Build is available Tests results are available  (6 of 6 platforms) 	Wed, 6 Jul 2022 -- 18:00 (-0400)
    I20220704-0500 	Build is available Tests results are available but did not finish on all machines  (5 of 6 platforms) 	Mon, 4 Jul 2022 -- 05:00 (-0400)
    I20220627-1800 	Build is available Tests results are available  (6 of 6 platforms) 	Mon, 27 Jun 2022 -- 18:00 (-0400)
    I20220620-1050 	Build is available Tests results are available  (6 of 6 platforms) 	Mon, 20 Jun 2022 -- 10:50 (-0400)
    I20220613-1030 	Build is available Tests results are available  (6 of 6 platforms) 	Mon, 13 Jun 2022 -- 10:30 (-0400)
    I20220606-1800 	Build is available Tests results are available  (6 of 6 platforms) 	Mon, 6 Jun 2022 -- 18:00 (-0400)

That is all nice but ... I want to download SWT only. Why do I get like 12 entries stating "Build is available"? Does every
new user need all these 12 entries? Is this giving me anything useful? Shall I manually click through all of that? Is every user expected to click on that? I mean you could add that on a separate tab or window I suppose, for the few users who need that.

Then I see "Latest Downloads" and "Latest Release". Ok what is the difference? Why is this confusing like hell? Did
a monkey design the webpage? No insults meant to monkeys - they could come up with a cleaner and less confusing
design.

There is also another entry called "Stable Builds". Ok so ... it's cool that we have like 30 different choices. But I only need
one!

Do we really have to scan which one is the correct? How about simplifying the layout?

I ended up downloading the whole of eclipse, but now I have no idea where the heck SWT can be found.

So I have two suggestions:

(1) Please, for the love of god or any spirital entity assumed to exist: SIMPLIFY the whole web-page. It's way overcrowded
with information. Look at the homepage of GraalVM, it contains tons of useful information without being overcrowded, neatly
arranged in smaller chunks of information.

(2) Perhaps also consider making SWT kind of separate, ideally if the java ecosystem could have something like "java install swt", and then we can just use it. That would be GREAT. Even Rust allows for this; scripting languages such as perl ruby php R etc... all allow that. I am ok downloading manually; I downloaded graalvm too and it works fine. But, yikes, whoever was at designing the SWT homepage, really loves making things complicated. A smaller separated SWT add-on would be nice, we could just download it, put it somewhere on the local filesystem, perhaps add it to some ENV variable and then use it. Right now I have no idea what to do with any of that - it's confusing to no ends. Java could REALLY need some simplification; part of this I assume is to be blamed on Oracle, I get it, but then you downstream folks could kindly ask Oracle to clean up the java ecosystem. Other languages managed to do that - and no, ant+XML is not really an epic solution to anything in 2022 ...

**Comment by Phillipus** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/R-4.24-202206070700/

Scroll to the bottom for SWT binaries.

**Comment by akurtakov** [comment]
On the very first url you went one segment deeper than needed - testResults is not smth you care about. https://download.eclipse.org/eclipse/downloads/drops4/R-4.24-202206070700/#SWT has what you look for. 
The page is not the most welcoming I know and we are improving things with each release - help with that is more than welcome!

P.S. If you want your comments to be taken more seriously please resist from coments like "Did a monkey design the webpage" especially when in no dictionary "download" equals "release", one can download many other versions - alpha, beta, milestone, integration, nightly and etc. builds.

**Comment by akurtakov** [comment]
I'll close this one now. If one wants to improve things further please come up with direct and actionable item.
