### ISSUE TITLE
test_traverseCheckButton fails on Linux.

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#27]
This test fails on Linux, it is a regression from #24.
https://download.eclipse.org/eclipse/downloads/drops4/I20220406-0600/testresults/html/org.eclipse.swt.tests_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

```
Test_org_eclipse_swt_widgets_Button | test_traverseCheckButton | Failure | N/A
java.lang.AssertionErrorat org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_widgets_Button.test_traverseCheckButton(Test_org_eclipse_swt_widgets_Button.java:448)
```

_Originally posted by @iloveeclipse in https://github.com/eclipse-platform/eclipse.platform.swt/pull/24#discussion_r844103000_

**Comment by iloveeclipse** [comment]
The test fails now on SWT jenkins too (now the new SWT code is used), see for example https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/PR-28/1/

It is also stable fail locally on Linux.

**Comment by rolfth** [comment]
Probably a focus issue, but cannot investigate with high prio. Please disable the test for Linux, will take a look later.

**Comment by iloveeclipse** [comment]
OK.
