### ISSUE TITLE
SWT crashes on Linux with webkit2gtk 2.36.5

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.swt#281]
Originally reported to wildwebdeveloper https://github.com/eclipse/wildwebdeveloper/issues/843 .
Quite useful data in this report, the gist of it is:

Enabling debuginfod in gdb obtains a more useful backtrace:[ https://linx.marussy.com/obbv0az6.txt](https://linx.marussy.com/obbv0az6.txt)
It looks like the crash is due to this failed assertion:[ https://github.com/WebKit/WebKit/blob/webkitgtk/2.36/Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.cpp#L101](https://github.com/WebKit/WebKit/blob/webkitgtk/2.36/Source/WebKit/UIProcess/WebsiteData/WebsiteDataStore.cpp#L101)
While the files mentioned in the trace haven't been changed recently, the semantics of isMainThread have indeed been changed between 2.36.4 and 2.36.5: see[ https://github.com/WebKit/WebKit/commit/50d7bfe855ca043cc72ec09b3d3d75100015101b#r78597817](https://github.com/WebKit/WebKit/commit/50d7bfe855ca043cc72ec09b3d3d75100015101b#r78597817) and[ https://github.com/WebKit/WebKit/commit/6a1445596f978d93f7eafe50629115d896d3a22b](https://github.com/WebKit/WebKit/commit/6a1445596f978d93f7eafe50629115d896d3a22b)
I suspect this is either an upstream bug (the semantics of isMainThread are still off), or a bug in Eclipse, i.e., SWT is calling webkitgtk2 functions in a manner that is not thread-safe, but allowed by the previous (wrong) isMainThread semantics.

**Comment by akurtakov** [comment]
Reproduced on my Fedora 36 system too.

**Comment by 4javier** [comment]
Pinging original debugger @kris7t for further info.

**Comment by LorenzoBettini** [comment]
Reported in Arch as well https://bugs.archlinux.org/task/75453

**Comment by akurtakov** [comment]
Eclipse is not using webkitgtk on MacOS as it uses the Cocoa UI toolkit there.

**Comment by cherio** [comment]
I confirm, my up-to-date Arch environment is affected. Certain dialogs (e.g. Marketplace) crash the IDE with coredump.

**Comment by mbooth101** [comment]
I get this crash 100% when using content assist (typing a dot or typing ctrl+space)

I am a Fedora user, and can confirm doing `sudo dnf downgrade webkit2gtk3\*` fixes the problem for me.

**Comment by cherio** [comment]
This was fixed in Arch (mine crashes no more) late last night when the patched version 2.36.5-2 of webkit2gtk rolled out. My guess Fedora should follow shortly.

**Comment by akurtakov** [comment]
There is a fixed build of webkit in Fedora's updates-testing repository.

**Comment by akurtakov** [comment]
Closing as there is nothing to be done on our side.
