### ISSUE TITLE
org.eclipse.swt.tests.junit.Test_org_eclipse_swt_custom_StyledText.test_caretSizeAndPositionVariableGlyphMetrics fails on master

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.swt#294]
see https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/master/571/testReport/junit/org.eclipse.swt.tests.junit/Test_org_eclipse_swt_custom_StyledText/test_caretSizeAndPositionVariableGlyphMetrics/

**Comment by jukzi** [comment]
Please revert whatever caused that or fix the test.

**Comment by akurtakov** [comment]
This failure is due to change in Pango library which changed in the OS. Reverting to older docker image is not an option for security reasons. I have spent some time trying to fix this one but still can't figure it. If there is anyone knowledgable of pango details help is more than welcome.

**Comment by iloveeclipse** [comment]
As discussed on https://github.com/eclipse-platform/eclipse.platform.swt/pull/504, if we don't have solution for 4.27 M3 we will "mute" the test via https://github.com/eclipse-platform/eclipse.platform.swt/pull/504.

**Comment by akurtakov** [comment]
If only there was XFAIL concept in JUnit so these can stay easily findable while not breaking the build.

**Comment by HannesWell** [comment]
> This failure is due to change in Pango library which changed in the OS. Reverting to older docker image is not an option for security reasons. I have spent some time trying to fix this one but still can't figure it. If there is anyone knowledgable of pango details help is more than welcome.

In #514 I noticed that all tests pass, as mentioned in https://github.com/eclipse-platform/eclipse.platform.swt/pull/504#issuecomment-1399351991, this is maybe because with that change the tests run on the standard centos-latest/8 image?

**Comment by akurtakov** [comment]
Running the build on older pango version will make the tests work but they would still fail on newer one.

**Comment by HannesWell** [comment]
> Running the build on older pango version will make the tests work but they would still fail on newer one.

So the centos-latest images use the old pango version and the tests will fail again, if those images use newer versions?
I have to admit, that until now I never heard of pango.^^

**Comment by akurtakov** [comment]
> > Running the build on older pango version will make the tests work but they would still fail on newer one.
> 
> So the centos-latest images use the old pango version and the tests will fail again, if those images use newer versions? I have to admit, that until now I never heard of pango.^^

Correct. The reason why tests were run on new fedora was exactly that to test on new version of dependencies like supported Ubuntu, Fedora, Suse while reducing build script differencies as centos and fedora are kind of cousins.
Pango is the text rending library used by Gtk https://gitlab.gnome.org/GNOME/pango/ .

**Comment by HannesWell** [comment]
Understand. So https://github.com/eclipse-platform/eclipse.platform.swt/pull/514 is kind of a step backwards, in this regard since it uses `centos-latest`?

**Comment by akurtakov** [comment]
> Understand. So #514 is kind of a step backwards, in this regard since it uses `centos-latest`?

Yes, but I fully understand how this step is needed to get more automation on swt side. It can be looked at how to get tests run on newer platform later.

**Comment by HannesWell** [comment]
> > Understand. So #514 is kind of a step backwards, in this regard since it uses `centos-latest`?
> 
> Yes, but I fully understand how this step is needed to get more automation on swt side. It can be looked at how to get tests run on newer platform later.

Sounds good. Yes once #514 many other things can be improved as well.
