### ISSUE TITLE
org.eclipse.swt.tests.junit.Test_org_eclipse_swt_graphics_TextLayout.test_getLineOffsets fail on master

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.swt#295]
See https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/master/571/testReport/junit/org.eclipse.swt.tests.junit/Test_org_eclipse_swt_graphics_TextLayout/test_getLineOffsets/

**Comment by joel-majano** [comment]
Getting a 404 Error on that link. I would link to https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/master/ then look at the latest build (currently #576).

**Comment by laeubi** [comment]
571 is gone but the just finished master shows the same problem:
https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/master/576/testReport/junit/org.eclipse.swt.tests.junit/Test_org_eclipse_swt_graphics_TextLayout/test_getLineOffsets/

**Comment by lshanmug** [comment]
I assume this is on Linux as the Jenkins job runs the tests the Linux. Also, this failure is not seen in the I-build test results - https://download.eclipse.org/eclipse/downloads/drops4/I20220809-1800/testresults/html/org.eclipse.swt.tests_ep425I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

**Comment by laeubi** [comment]
See https://ci.eclipse.org/platform/job/eclipse.platform.swt/job/master/582/#showFailuresLink

**Comment by akurtakov** [comment]
This is caused by Pango 1.44 putting soft hyphenation (SHY) when wrapping now . It's explained in https://blogs.gnome.org/mclasen/2019/07/27/more-text-rendering-updates/ . From the documentation pango_attr_insert_hyphens_new should be cure but I haven't managed to make it work so far.

**Comment by akurtakov** [comment]
One can run `pango-view --text WMWM --wrap word-char --width 28` and see the SHY displayed. There seems to be extra issue on SWT side in g_utf16_pointer_to_offset to consider it thus calculating wrong offsets.

**Comment by akurtakov** [comment]
And `pango-view --wrap word-char --width 28 --markup --text "<span insert_hyphens='false'>WMWM</span>"` makes the hyphens disappear so this is the ultimate goal for SWT too.
