### ISSUE TITLE
test_bug493455_drawImageAlpha_srcPos fails on both MAC platforms

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#30]
test_bug493455_drawImageAlpha_srcPos fails on both MAC platforms

See
- https://download.eclipse.org/eclipse/downloads/drops4/I20220406-1800/testresults/html/org.eclipse.swt.tests_ep424I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
- https://download.eclipse.org/eclipse/downloads/drops4/I20220406-1800/testresults/html/org.eclipse.swt.tests_ep424I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

```
expected:<RGB {0, 255, 0}> but was:<RGB {255, 255, 255}>

java.lang.AssertionError: expected:<RGB {0, 255, 0}> but was:<RGB {255, 255, 255}>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:120)
at org.junit.Assert.assertEquals(Assert.java:146)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_graphics_GC.test_bug493455_drawImageAlpha_srcPos(Test_org_eclipse_swt_graphics_GC.java:681)
```

_Originally posted by @iloveeclipse in https://github.com/eclipse-platform/eclipse.platform.swt/pull/12#discussion_r844809774_

**Comment by iloveeclipse** [comment]
@jonathan-meier : please check. In doubt, we can disable this test on Mac, similar to #29.

**Comment by lshanmug** [comment]
Bug https://bugs.eclipse.org/bugs/show_bug.cgi?id=493455 was happening on both Windows and Mac. It has been fixed on Windows now. But, it's still a problem on Mac, causing the test failures. Will disable the test on Mac and track the Mac bug in a separate issue.

**Comment by lshanmug** [comment]
The failing test is now ignored on Mac - https://download.eclipse.org/eclipse/downloads/drops4/I20220412-1800/testResults.php and bug is tracked by #40
