### ISSUE TITLE
[WebKit] InjectedBundle deprecation impact analysis

### ISSUE THREAD

**Issue by trancexpress** [eclipse-platform/eclipse.platform.swt#316]
We got a notification from RHEL support about this: https://lists.webkit.org/pipermail/webkit-dev/2022-August/032329.html

```
Hi,

Apple announced on Friday that they will remove the injected bundle (WebKitWebExtension) APIs sometime within the next 1-3 years:

https://lists.webkit.org/pipermail/webkit-dev/2022-August/032329.html

This means webkit-web-extension.pc will probably go away. It's a disastrous API change that will break Yelp, Evolution, Epiphany, Eclipse, and more. Some of these applications will require substantial work to keep alive. Since there are no replacement APIs yet, that work cannot begin yet: at this point, I'm just providing a heads-up as early as possible.

We'll be able to continue updating WebKitGTK in RHEL 9 because it is provided at Application Compatibility Guidelines level 4 (zero compatibility). The same is technically true for RHEL 8, but I will probably stop updating WebKitGTK in RHEL 8 before these changes arrive to dodge any impact there.

Red Hat will have to take care of the packages that are provided by us. I understand we no longer have an Eclipse package, so I've included Simeon on this mail as a heads-up that this will be a problem for Eclipse.

I'll probably wait a couple weeks before announcing this more generally, just in case any of this changes unexpectedly.

Michael
```

We'll have to check what the impact is for SWT and Eclipse.

**Comment by akurtakov** [comment]
SWT no longer uses web extension since https://github.com/eclipse-platform/eclipse.platform.swt/commit/a56c5b55c9ec05607ae31a2f3865406d2288980f#diff-82e5053d6a9f4a148e71fa52021ef3b27bc0407a5a2763a72b4ebac64ba4e2a2 . We seem to be safe now thanks to @nnemkin

**Comment by mcatanzaro** [comment]
Nice, that avoids this problem indeed.

**Comment by trancexpress** [comment]
> SWT no longer uses web extension since [a56c5b5#diff-82e5053d6a9f4a148e71fa52021ef3b27bc0407a5a2763a72b4ebac64ba4e2a2](https://github.com/eclipse-platform/eclipse.platform.swt/commit/a56c5b55c9ec05607ae31a2f3865406d2288980f#diff-82e5053d6a9f4a148e71fa52021ef3b27bc0407a5a2763a72b4ebac64ba4e2a2) . We seem to be safe now thanks to @nnemkin

Sounds great, thanks Alexander!

**Comment by trancexpress** [comment]
@akurtakov , a question about GTK4 and RHEL. RHEL no longer officially supports Eclipse, does this have an impact on the GTK4 move? I see there are still commits for the move, so RHEL Eclipse maintainers are still driving the move?

**Comment by akurtakov** [comment]
In a way yes. But it's best effort move and trying to be less broken at the time when something forces us to to GTK4 by default like webkitgtk forced us to go GTK3 at one point.
There is no time frame nor enough time spent from my team to handle it alone but Eclipse itself already starts with GTK4 although with severe issues. At best, we are prepared for the same bumpy road like the GTK 2->3 migration in the past :( . Overall, we are at the mercy of surrounding ecosystem.

**Comment by trancexpress** [comment]
> In a way yes. But it's best effort move and trying to be less broken at the time when something forces us to to GTK4 by default like webkitgtk forced us to go GTK3 at one point. There is no time frame nor enough time spent from my team to handle it alone but Eclipse itself already starts with GTK4 although with severe issues. At best, we are prepared for the same bumpy road like the GTK 2->3 migration in the past :( . Overall, we are at the mercy of surrounding ecosystem.

OK, thanks. I've asked @iloveeclipse if Advantest can invest effort in the move. I assume sooner or later more maintainers will have to step in, better sooner than too late.
