### ISSUE TITLE
SWT/AWT native library not usable with OpenJDK 11.0.16 / 17.0.4 (libjawt.so: version `SUNWprivate_1.1' not found)

### ISSUE THREAD

**Issue by sratz** [eclipse-platform/eclipse.platform.swt#321]
**Describe the bug**
SWT/AWT bridge cannot be used again with OpenJDK 11.0.16 / 17.0.4.

**To Reproduce**
Try to run org.eclipse.swt.snippets.Snippet135 with SapMachine 11.0.16 or 17.0.4:
https://github.com/SAP/SapMachine/releases/tag/sapmachine-11.0.16
https://github.com/SAP/SapMachine/releases/tag/sapmachine-17.0.4
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/foo/.swt/lib/linux/x86_64/libswt-awt-gtk-4954r6.so: /home/foo/java/sapmachine-jdk-11.0.16/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /home/foo/.swt/lib/linux/x86_64/libswt-awt-gtk-4954r6.so)
```

**Expected behavior**
Snippet should work on all JVMs. `libswt-awt-gtk` should not depend on the obsolete  `SUNWprivate_1.1` reference. 

**Screenshots**

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [X] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
`x86_64` and `ppc64le` are affected.

4. JRE/JDK version
OpenJDK 11.0.16 / 17.0.4
 
**Version since**
n/a

**Workaround (or) Additional context**
Related issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=558874

Related OpenJDK/SapMachine bug report: https://github.com/SAP/SapMachine/issues/1227

`libswt-awt-gtk.so` appears to be built on a JDK8 version which uses the `SUNWprivate_1.1` versions, that have been removed in JDK11.

So, it seems that `libswt-awt-gtk.so` should be rebuilt against a JDK11 JNI.

 `SUNWprivate_1.1` appears only in 
`org.eclipse.swt.gtk.linux.ppc64le/libswt-awt-gtk-*.so`
and
`org.eclipse.swt.gtk.linux.x86_64/libswt-awt-gtk-*.so`.
All other `.so` files have no reference to it.

**Comment by akurtakov** [comment]
I looked at https://ci.eclipse.org/releng/view/SWT%20Natives%20(master)/job/gtk_linux_x86_64/100/console and see ` gcc -O -Wall -fPIC -DSWT_VERSION=4954r6    -DLINUX -DGTK -I/opt/tools/java/oracle/jdk-8/latest/include -I/opt/tools/java/oracle/jdk-8/latest/include/linux -DJNI64 -Werror `pkg-config --cflags atk gtk+-3.0 gtk+-unix-print-3.0` -c atk_stats.c ` so you're correct. @sravanlakkimsetti can we switch this one easily?

**Comment by sravanlakkimsetti** [comment]
if swt can be built locally using java 11 (I had trouble sometime back) we can definitely upgrade. updating https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/9cd5df82d9f6e99126528c525a0da57393c922d3/cje-production/dockerfiles/centos-gtk3-metacity/8-swtBuild/Dockerfile#L37 will move the java version. 

For ppcle and aarch64 I will need to upgrade the machines manually. Please try with x64 first and if successful I will update the ppcle and

**Comment by sravanlakkimsetti** [comment]
Linux can be upgraded quickly. But moving Mac and Windows will require help from foundation

**Comment by sratz** [comment]
I grabbed the latest https://ci.eclipse.org/releng/view/SWT%20Natives%20(master)/job/gtk_linux_x86_64/105/artifact/build/libs/libswt-awt-gtk-4954r7.so file build with JDK11 and tested with that.

SWT/AWT works fine again with SapMachine 11.0.16 and 17.0.4.

There is no reference to symbol `SUNWprivate_1.1` anymore.

**Comment by akurtakov** [comment]
Glad that it works for you now. Is Win/Mac supposed to have same failure according to you?

**Comment by sratz** [comment]
No, Windows / Mac work fine.

I have checked all `.so` / `.dylib` / `.dll` files. Symbol `SUNWprivate_1.1` was only found in 
```
org.eclipse.swt.gtk.linux.x86_64/libswt-awt-gtk-*.so
org.eclipse.swt.gtk.linux.ppc64le/libswt-awt-gtk-*.so
```

**Comment by akurtakov** [comment]
Can you verify linux ppc64le too?

**Comment by sratz** [comment]
> Can you verify linux ppc64le too?

No, I don't have access to such a machine/VM.

**Comment by akurtakov** [comment]
OK. I consider this one done as the fix for ppc64le is same as for x86_64, which is verified fixed.
