### ISSUE TITLE
Eclipse crashes when hover in Java editor is about to show

### ISSUE THREAD

**Issue by 15knots** [eclipse-platform/eclipse.platform.swt#350]
**Describe the bug**
Eclipse crashes when the hover in a Java editor is about to show after upgrading to libwebkit2gtk-4_0-37  version 2.36.5.

**To Reproduce**
- Open a java file in the java editor
- Move the cursor over the name of a Java symbol, e.g. Object

Eclipse is unresponsive for some seconds, then crashes. 
A core dump can be found in the journal (journalctl -e).
No JVM crashlog file is created.

**To Reproduce 2**
- Select _Help | Eclipse Marketplace_

**Expected behavior**
No Crashes.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [x] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
openSUSE 15.3, KDE

3. JRE/JDK version
adoptopenjdk-11-hotspot-11.0.11+9-3.x86_64

 Eclipse installation details:
awt.toolkit=sun.awt.X11.XToolkit
eclipse.application=org.eclipse.ui.ide.workbench
eclipse.buildId=4.24.0.I20220607-0700
eclipse.commands=-os
linux
-ws
gtk
-arch
x86_64
--launcher.library
/home/user/bin/eclipse//plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.500.v20220509-0833/eclipse_11701.so
-startup
/home/user/bin/eclipse//plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
-vm
/usr/lib64/jvm/adoptopenjdk-11-hotspot/bin/java

**Version since**
Version: 2022-06 (4.24.0)

**Workaround (or) Additional context**
Downgrading libwebkit2gtk-4_0-37  to version 2.36.3 fixed the problem.

Since I did not update Eclipse but libwebkit2gtk, this might be an issue for libwebkit2gtk.

**Comment by 15knots** [comment]
systemd-coredump[9542]: [🡕] Process 8857 (java) of user 1000 dumped core.
  
  Stack trace of thread 8858:
  #0  0x00007fabca983cdb raise (libc.so.6 + 0x4acdb)
  #1  0x00007fabca985375 abort (libc.so.6 + 0x4c375)
  #2  0x00007fab00b0ae0d n/a (libwebkit2gtk-4.0.so.37 + 0x6a8e0d)
  #3  0x00007fab011b618c n/a (libwebkit2gtk-4.0.so.37 + 0xd5418c)
  #4  0x00007fab0103ddfe n/a (libwebkit2gtk-4.0.so.37 + 0xbdbdfe)
  #5  0x00007fab010f05e1 webkit_security_manager_register_uri_scheme_as_local (libwebkit2gtk-4.0.so.37 + 0xc8e5e1)
  #6  0x00007fab01109a9d n/a (libwebkit2gtk-4.0.so.37 + 0xca7a9d)
  #7  0x00007fab720dd7da n/a (libgobject-2.0.so.0 + 0x197da)
  #8  0x00007fab720deded g_object_new_with_properties (libgobject-2.0.so.0 + 0x1aded)
  #9  0x00007fab720df8b1 g_object_new (libgobject-2.0.so.0 + 0x1b8b1)
  #10 0x00007fab01104891 n/a (libwebkit2gtk-4.0.so.37 + 0xca2891)
  #11 0x00007fab71e1b065 g_once_impl (libglib-2.0.so.0 + 0x7c065)
  #12 0x00007fab01104ecd webkit_web_context_get_default (libwebkit2gtk-4.0.so.37 + 0xca2ecd)
  #13 0x00007fab05e17e8c Java_org_eclipse_swt_internal_webkit_WebKitGTK_webkit_1web_1context_1get_1default (/home/user/bin/eclipse/configuration/org.eclipse.osgi/1770/0/.cp/libswt-webkit-gtk-4952r11.so + 0x5e8c)
  #14 0x00007fabac8875b0 n/a (n/a + 0x0)
  #15 0x00007fabac881a10 n/a (n/a + 0x0)
  #16 0x00007fabac881f03 n/a (n/a + 0x0)
  #17 0x00007fabac881f03 n/a (n/a + 0x0)
  #18 0x00007fabac8816d0 n/a (n/a + 0x0)
  #19 0x00007fabac881c80 n/a (n/a + 0x0)
  #20 0x00007fabac881d56 n/a (n/a + 0x0)
  #21 0x00007fabac881c80 n/a (n/a + 0x0)
  #22 0x00007fabac881f03 n/a (n/a + 0x0)
  #23 0x00007fabac881f03 n/a (n/a + 0x0)
  #24 0x00007fabac881f03 n/a (n/a + 0x0)
  #25 0x00007fabac881f03 n/a (n/a + 0x0)
  #26 0x00007fabac881f03 n/a (n/a + 0x0)
  #27 0x00007fabb4ba6ac8 n/a (n/a + 0x0)

**Comment by flyn-org** [comment]
I have the same problem on Fedora 39, which currently provides webkit2gtk4.0-2.42.3-1.fc39.x86_64. I have been unable to build webkit2gtk 2.36.3 on Fedora 39 to mimic what @15knots suggested for Ubuntu. Instead, I avoided the problem by disabling some of the features that trigger the bug:

Visit the preferences under `Window->Preferences`. Under `Java->Editor->Hovers`, uncheck all the options. Under `Java->Editor->Content Assist`, uncheck `Enable auto activation`.

**Comment by akurtakov** [comment]
@flyn-org On Fedora 39 please install webkit2gtk4.1, it works just fine for me and 4.0 is scheduled for removal https://fedoraproject.org/wiki/Changes/Remove_webkit2gtk-4.0_API_Version

**Comment by akurtakov** [comment]
You will have to uinstall 4.0 as 4.1 is fallback if 4.0 fails to dlopen. I'll provide a PR reversing this.

**Comment by 15knots** [comment]
I can confirm that it works with libwebkit2gtk-4_1-0-2.42.4 (on openSUSE).

**Comment by akurtakov** [comment]
As per original reporter test and change to prefer libwebkit2gtk-4.1 closing this one.
