### ISSUE TITLE
Fix keyboard handling issues

### ISSUE THREAD

**Issue by SyntevoAlex** [eclipse-platform/eclipse.platform.swt#351]
There is a number of issues when handling key presses in Windows, such as:
* [win32] JVM crash when pressing `1` in Nepali keyboard layout
* [win32] Bug 536041: Digit keys in Lithuanian type additional "trash" characters
* [win32] Digit keys in French and many other languages don't invoke corresponding keyboard shortcuts
* [win32] Various issues with dead keys reporting
* [cocoa] Bug 573487: Keyboard shortcuts don't work in non-latin layouts
* etc

I'm already working on a patch to fix these.

**Comment by akurtakov** [comment]
This has caused javadoc errors. See https://download.eclipse.org/eclipse/downloads/drops4/I20221009-1800/compilelogs/platform.doc.isv.javadoc.txt

Eclipse itself complains about it:
![image](https://user-images.githubusercontent.com/574788/194814100-2d57c718-3c4d-4372-b4bc-bad3f6530320.png)

I'm fixing it now but please keep in mind that javadoc for tests is not built and published.

**Comment by SyntevoAlex** [comment]
Thanks for taking care of it!
