### ISSUE TITLE
[win32] Native libs: treat warnings as errors

### ISSUE THREAD

**Issue by SyntevoAlex** [eclipse-platform/eclipse.platform.swt#369]
I noticed that some warnings occur when building native libs on Windows. These easily get overlooked, because nobody is watching. Previously, in Bug 570178, I already changed GTK native libs to treat build warnings as errors. Let's do the same for Windows.

**Comment by akurtakov** [comment]
Revert has been done so build can be unbroken . Here is the list to the failing build https://ci.eclipse.org/releng/view/SWT%20Natives%20(master)/job/win32_x86_64/120/console

**Comment by SyntevoAlex** [comment]
Hmm, so
* Build machine uses older VS2019, it seems, unlike GitHub and my own machine
* In it, Windows SDK has some warnings
* This causes build to fail.

That's a bit unfortunate.

@niraj-modi previously we discussed that VS2022 should be installed on build machines https://bugs.eclipse.org/bugs/show_bug.cgi?id=578519#c6 it seems that something went wrong?

**Comment by SyntevoAlex** [comment]
I prepared an updated PR that also covers warnings that are seen in older VS2019 and not seen in newer VS2022 (that's why I didn't see them when building on my machine but Eclipse build failed)

**Comment by majanojoel** [comment]
I'm seeing this generate code in gtk specific files such as os.c, gtk3.c, gtk4.c when I run the build.sh file like "./build.sh -gtk3 install". 

The code generated is:
```
#ifdef _WIN32
  /* Many methods don't use their 'env' and 'that' arguments */
  #pragma warning (disable: 4100)
#endif
```
Is this expected behaviour?

**Comment by SyntevoAlex** [comment]
Yes, this is expected. In `JNIGenerator`, it is not known which platform is being generated (because it generates all at once). Further, some files, such as `C.java`, are used by all platforms at once. The inserted code is harmless on non-windows platforms, because it's guarded with `#ifdef _WIN32`
