### ISSUE TITLE
Bug 579626 - RTL text is not rendered correctly on TextLayout

### ISSUE THREAD

**Issue by niraj-modi** [eclipse-platform/eclipse.platform.swt#37]
The changes made on https://bugs.eclipse.org/bugs/show_bug.cgi?id=565526 caused RTL texts to be rendered incorrectly on TextLayout.

**Comment by Phillipus** [comment]
Thanks for looking at this, Niraj.

I tested commit https://github.com/eclipse-platform/eclipse.platform.swt/commit/521940d173d5dde82c1c7b397a6947b3f08d1e1f but it doesn't seem to have fixed the issue.

`scriptState.fArabicNumContext)` is always returning false in my test cases.

**Comment by Phillipus** [comment]
If I run this snippet the text is wrong direction:

https://bugzillaattachments.eclipsecontent.org/bugs/attachment.cgi?id=288411

**Comment by Phillipus** [comment]
Here's simple test case:

```
import org.eclipse.swt.SWT;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Text;

class ArabicTest {

    private static final String ARABIC_TEXT = "جارِ التحميل";

    public static void main(String[] args) {
        final Display display = new Display();
        Shell shell = new Shell(display);
        shell.setLayout(new GridLayout());

        // This is rendered correctly
        Text text = new Text(shell, SWT.BORDER);
        text.setText(ARABIC_TEXT);

        // This is not rendered correctly
        StyledText styled = new StyledText(shell, SWT.BORDER | SWT.MULTI);
        styled.setText(ARABIC_TEXT);

        shell.pack();
        shell.open();

        while(!shell.isDisposed()) {
            if(!display.readAndDispatch()) display.sleep();
        }
    }
}
```

**Comment by Phillipus** [comment]
Hi Niraj,

I tested the PR and it has fixed the problem both in the test snippet and in our RCP app, Archi. Thanks!

**Comment by niraj-modi** [comment]
> Hi Niraj,
> 
> I tested the PR and it has fixed the problem both in the test snippet and in our RCP app, Archi. Thanks!

Thanks Phil for the test/confirmation, closing now.

**Comment by bbdalai** [comment]
Hi @niraj-modi ,

I was verifying this issue with I20220411-1800 build. Issue is fixed in eclipse Text editor. But issue is still there with Java editor and XML editor.  

e.g: 

public class RTLTest {
	public static void main(String[] args) {
		System.out.println("جارِ التحميل");
	}
}

<?xml version="1.0" encoding="UTF-8"?>
<RTL>جارِ التحميل</RTL>

**Comment by Phillipus** [comment]
I can confirm the issue still present in Java and XML editors.

If I completely comment out lines 2766 - 2789 in `TextLayout#itemize()` then the Arabic text is rendered correctly, So there must still be something else to do here:

`if (BidiUtil.resolveTextDirection(text) != SWT.RIGHT_TO_LEFT) {`

**Comment by Phillipus** [comment]
> Issue is fixed in eclipse Text editor

Well, not really. If the Arabic text is on one line then it's OK, but mixed with non-Arabic text it's wrong:

![text](https://user-images.githubusercontent.com/600504/162922610-4bfffd98-82fa-455d-8cf8-f5351309bbf5.png)

Again, in this case, commenting out the lines in TextLayout#itemize() displays correctly.

**Comment by Phillipus** [comment]
New test snippet:

```
import org.eclipse.swt.SWT;
import org.eclipse.swt.custom.StyledText;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;
import org.eclipse.swt.widgets.Text;

class ArabicTest {

    private static final String MIXED_TEXT = "English جارِ التحميل";

    public static void main(String[] args) {
        final Display display = new Display();
        Shell shell = new Shell(display);
        shell.setLayout(new GridLayout());

        // This is rendered correctly
        Text text = new Text(shell, SWT.BORDER);
        text.setText(MIXED_TEXT);

        // This is not rendered correctly
        StyledText styled = new StyledText(shell, SWT.BORDER | SWT.MULTI);
        styled.setText(MIXED_TEXT);

        shell.pack();
        shell.open();

        while(!shell.isDisposed()) {
            if(!display.readAndDispatch()) display.sleep();
        }
    }
}
```

**Comment by niraj-modi** [comment]
> I wonder if the problem lies in `BidiUtil#resolveTextDirection(text)`?
> 
> If there is mixed text, as in the above example, then it will return `SWT.LEFT_TO_RIGHT` if non-Arabic text is first.

That's how BidiUtil#resolveTextDirection(text) works and it's documented in it's JavaDoc as well:
![image](https://user-images.githubusercontent.com/92304759/162930224-bc67aeea-aca9-4125-8c85-20539f60e4de.png)

**Comment by niraj-modi** [comment]
Am planning to back-port this bug fix to 4.23+ maintenance branch shortly.

**Comment by Phillipus** [comment]
@niraj-modi Do you think it's possible to fix the mixed text issue in the above example? Arabic/Hebrew users will encounter it in mixed code and text such as:

`System.out.println("جارِ التحميل");`

**Comment by akurtakov** [comment]
@Phillipus Have you faced this issue on Mac/Linux? It was just noticed that the fix was purely Windows specific so the question is - do we need fixes for other OSes or they are better at i18n and only Windows need such fix?

**Comment by Phillipus** [comment]
@akurtakov It's only for Windows.

The cause was https://bugs.eclipse.org/bugs/show_bug.cgi?id=565526 which changed `TextLayout` for win32 only:

https://git.eclipse.org/c/platform/eclipse.platform.swt.git/commit/?id=bd786bc001096a195a4180b432b5d23d1cfcf3a2

**Comment by akurtakov** [comment]
Thanks for the explanation.
