### ISSUE TITLE
Support for changing the color of table separator lines

### ISSUE THREAD

**Issue by gayanper** [eclipse-platform/eclipse.platform.swt#386]
![image](https://user-images.githubusercontent.com/7471994/190396052-399c8ba6-1661-4cea-8262-838c6761f442.png)

As you can see in the above image, when the table lines are configured not to be visible the intensity of the column header separators are increased. It would be nice to add support to configure this color. 

In addition if the same color property can be used to control the table lines that would be a +1 as well since then the lines can be dimmed enough just to be a guide in dark themes.

OS: Windows 10
Eclipse Version: 2022-12 (4.26)
Build id: I20220913-1800

**Comment by SyntevoAlex** [comment]
Please use `Display.setData(Display.TABLE_HEADER_LINE_COLOR_KEY, new Color(...))`. Note that `OS.setTheme(true)` already does that, along with a number of other Dark Theme customizations.

**Comment by gayanper** [comment]
> Please use `Display.setData(Display.TABLE_HEADER_LINE_COLOR_KEY, new Color(...))`. Note that `OS.setTheme(true)` already does that, along with a number of other Dark Theme customizations.

Thanks will try this out. Could we make this as part of css theming ?

**Comment by SyntevoAlex** [comment]
To my understanding, CSS theming is part of Eclipse, not SWT.
In Eclipse, you should simply select Dark theme and it will apply these settings automatically.

**Comment by gayanper** [comment]
> To my understanding, CSS theming is part of Eclipse, not SWT.
> In Eclipse, you should simply select Dark theme and it will apply these settings automatically.

Sure will raise this in platform ui which manage the theming.
