### ISSUE TITLE
Four VirtualLazyTreeViewerTest fail on Windows since I20220915-0600

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#396]
First observed in https://download.eclipse.org/eclipse/downloads/drops4/I20220915-0600/testResults.php
Last good build https://download.eclipse.org/eclipse/downloads/drops4/I20220912-1800/testResults.php
(the builds in between were unfortunately either not executed or unstable)

https://download.eclipse.org/eclipse/downloads/drops4/I20220919-0240/testresults/html/org.eclipse.jface.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html

```
new siblings are visible

junit.framework.AssertionFailedError: new siblings are visible
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.assertTrue(Assert.java:22)
at junit.framework.Assert.assertNotNull(Assert.java:256)
at junit.framework.TestCase.assertNotNull(TestCase.java:399)
at org.eclipse.jface.tests.viewers.StructuredViewerTest.testInsertSiblings(StructuredViewerTest.java:356)
at org.eclipse.jface.tests.viewers.VirtualLazyTreeViewerTest.testInsertSiblings(VirtualLazyTreeViewerTest.java:192)
```

I would assume this is a regression from https://github.com/eclipse-platform/eclipse.platform.swt/pull/347

**Comment by iloveeclipse** [comment]
@SyntevoAlex : could you please check?

**Comment by SyntevoAlex** [comment]
Yes, sure.

**Comment by SyntevoAlex** [comment]
I will investigate on 2022-09-21.

**Comment by SyntevoAlex** [comment]
Indeed, I overlooked yet another cached variable `Tree.itemCount` that becomes invalid. I'll fix it on Friday.

**Comment by SyntevoAlex** [comment]
I have submitted a patch.
My my, this Tree thing is quite a minefield with its cached variables!
