### ISSUE TITLE
[Win] Native build need JDK 11 to switch JNI_VERSION to 10

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#417]
In https://github.com/eclipse-platform/eclipse.platform.swt/pull/410 JNI_VERSION was switched to 10, but the build script wants (and finds) Java 8 on the Windows build machine.

https://ci.eclipse.org/releng/job/win32_x86_64/123/console

```
'SWT_JAVA_HOME' was not provided, auto-searching for JDK...
-- JDK 'C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot' looks good, selecting it
SWT_JAVA_HOME x64: C:\Program Files\AdoptOpenJDK\jdk-8.0.292.10-hotspot
```

We should change the script to want Java 11, and in case it is not on the machine, request an update.
See related https://bugs.eclipse.org/bugs/show_bug.cgi?id=572733

I will try to update the build script first.

**Comment by iloveeclipse** [comment]
@fredg02 : is there any way to know which Java is installed on https://ci.eclipse.org/releng/computer/rs68g-win10/ and in which directory?

**Comment by merks** [comment]
If you created a job that ran on that machine and listed the contents of `C:/Program Files/Java` that would probably answer this question:
```
dir "C:/Program Files/Java"
```
Of course you can list `C:/Program File` to see if there are other possible Java-containing folders...

**Comment by iloveeclipse** [comment]
OK, looks like Sravan did this before: https://ci.eclipse.org/releng/job/Sravan-win-test/2/console

Let's try with new SDK build now.

**Comment by iloveeclipse** [comment]
I've triggered https://ci.eclipse.org/releng/job/Builds/job/I-build-4.26/31/

**Comment by iloveeclipse** [comment]
https://ci.eclipse.org/releng/job/win32_x86_64/124/console
```
'SWT_JAVA_HOME' was not provided, auto-searching for JDK...
-- JDK 'C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot' looks good, selecting it
SWT_JAVA_HOME x64: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot
```
Looks good so far...

**Comment by iloveeclipse** [comment]
Also this is fine: https://ci.eclipse.org/releng/job/SWT-Increment_if_needed/1228/console

**Comment by iloveeclipse** [comment]
Fixed in https://download.eclipse.org/eclipse/downloads/drops4/I20221002-0330
