### ISSUE TITLE
Can't deselect all items in a SWT tree by clicking on the "void"

### ISSUE THREAD

**Issue by php4fan** [eclipse-platform/eclipse.platform.swt#427]
**Describe the bug**
I reported this bug to MeGit: https://github.com/eclipsesource/megit/issues/23 and they say there's nothing they can do about it because it's intrinsic to SWT.

**To Reproduce**
see  https://github.com/eclipsesource/megit/issues/23

**Expected behavior**
see  https://github.com/eclipsesource/megit/issues/23

**Screenshots**

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [X] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc): **Manjaro KDE**

4. JRE/JDK version: no idea
 
**Version since**
 Eclipse or SWT version since when the behavior is seen [e.g. 4.23]

**Workaround (or) Additional context**
Ctrl+Click on the only selected item to de-select it.

**Comment by SyntevoAlex** [comment]
Please edit your post to follow the suggested bugreport template.

For example, it is unclear which platform is it about.

**Comment by php4fan** [comment]
Edited

**Comment by SyntevoAlex** [comment]
This is default behavior on Linux GTK. Easy to see with `gtk3-demo` app (`sudo apt install gtk-3-examples`) in `Tree view`.
Therefore, not a bug.

It's easy enough to change this behavior in SWT applications by subscribing to `SWT.MouseDown` and using `Tree.getItem()`. When null, this means that empty space is clicked, and app can then deselect items.

**Comment by php4fan** [comment]
I see, so their fault for not doing that in the application.

But still, I don't think this is a wheel that should be reinvented at the application level. At the very least, this should be a boolean flag, for whether or not you want all items to be unselected when clicking outside of everything. And I'm pretty sure the correct default would be `true`. An application shouldn't have to build this behavior for scratch (and possibly get it wrong - I bet your proposed implementation with a mouseDown listener has caveats and edge cases that need to be handled properly).

**Comment by SyntevoAlex** [comment]
Well, this is the default behavior on Linux. SWT has no interest to change that, because it tries to stay close to platform behavior, unless platforms disagree and it wants to stay close to other platforms.

You could try asking GTK to change the default, but I can already forecast that this request will be rejected, at least due to compatibility reasons.

And no, I don't think that there is a need for option when something is rarely needed and can be implemented easily.

**Comment by php4fan** [comment]
> And no, I don't think that there is a need for option when something is rarely needed

The thing that is rarely needed here is the current behavior, but ok to everything else you said.
