### ISSUE TITLE
Mixed RTL text(with LTR) is not rendered correctly in StyledText widget

### ISSUE THREAD

**Issue by niraj-modi** [eclipse-platform/eclipse.platform.swt#44]
Raised this issue to capture bug highlighted in below test Snippet seen StyledText widget:
https://github.com/eclipse-platform/eclipse.platform.swt/issues/37#issuecomment-1096440107

**Comment by Phillipus** [comment]
Thanks for opening this issue, Niraj.

To summarise:

1. Changes made on https://bugs.eclipse.org/bugs/show_bug.cgi?id=565526 caused RTL texts to be rendered incorrectly on TextLayout
2. This has been partially fixed in #37 
3. However there is still a problem with mixed Arabic and non-Arabic text as in `System.out.println("جارِ التحميل");`
4. This is a Windows-only issue. Mac and Linux display RTL text correctly in all cases

**Comment by Phillipus** [comment]
(Excuse my meddling in this, I'm just throwing out some ideas)

I got rid of the check for RTL (`if (BidiUtil.resolveTextDirection(text) != SWT.RIGHT_TO_LEFT)`) and made the for loop like this:
```
for (int i = 0, latestNeutralIndex = -2, latestUnicodeIndex = -2; i < length; i++) {
	char c = chars[i];

	// Check single char for RTL
	if(BidiUtil.resolveTextDirection(Character.toString(c)) == SWT.RIGHT_TO_LEFT) {
		continue;
	}

	if (c >= ' ' && c <= '~' && !Character.isAlphabetic(c)) {
		latestNeutralIndex = i;
	} else if (c > 255) {
		latestUnicodeIndex = i;
	} else {
		continue;
	}

	// If the latest neutral and unicode characters are adjacent
	if (Math.abs(latestNeutralIndex - latestUnicodeIndex) == 1) {
		// Change the neutral into a non-neutral alphabet character
		chars[latestNeutralIndex] = 'A';
	}
}
```

**Comment by Phillipus** [comment]
@niraj-modi I tested PR #45 and that seems to do the trick! But do you think changing `BidiUtil#resolveTextDirection()` might cause problems elsewhere?

**Comment by niraj-modi** [comment]
> @niraj-modi I tested PR #45 and that seems to do the trick! But do you think changing `BidiUtil#resolveTextDirection()` might cause problems elsewhere?

PR #45 fix is inline with JavaDoc of `BidiUtil#resolveTextDirection()`:
- this patch just improves the behavior for complete text String as opposed to starting character.

We need to test this a bit more to be sure:
- I plan to elaborate the current test Snippet, with other widgets where this particular method is being called in SWT

**Comment by niraj-modi** [comment]
Updated PR #45 with a detailed Test Snippet.

**Comment by niraj-modi** [comment]
Verified the fix in Eclipse Build id: I20220414-0120
Will be back-porting this fix to 4.23+ shortly.

**Comment by Phillipus** [comment]
> Will be back-porting this fix to 4.23+ shortly.

How are 4.xx maintenance releases accessed via update site or p2? Or is it only the source code that is updated?

**Comment by niraj-modi** [comment]
> > Will be back-porting this fix to 4.23+ shortly.
> 
> How are 4.xx maintenance releases accessed via update site or p2? Or is it only the source code that is updated?

Yes, we only update the SWT sources for specific bug fixes or regressions.
Maintenance branches are pulled-built and patch-sharing happens via non-public platforms only.

**Comment by niraj-modi** [comment]
Looks like scanning complete line in BidiUtil#resolveTextDirection() has caused performance issue: https://github.com/eclipse-platform/eclipse.platform.debug/issues/5

Reopening this issue, to optimize the fix made here.

**Comment by niraj-modi** [comment]
> Looks like scanning complete line in BidiUtil#resolveTextDirection() has caused performance issue: [eclipse-platform/eclipse.platform.debug#5](https://github.com/eclipse-platform/eclipse.platform.debug/issues/5)
Seems the performance JUnit was adjusted to avoid the deadlock. Hence closing this issue now.

> Reopening this issue, to improve BidiUtil#resolveTextDirection() implementation here.
Anyways, improvement done to BidiUtil#resolveTextDirection() is merged to master and R4_23_maintenance branches.
