### ISSUE TITLE
Broken scaling on WSLg

### ISSUE THREAD

**Issue by SyntevoAlex** [eclipse-platform/eclipse.platform.swt#457]
**Describe the bug**
WSLg is a Linux virtual machine inside Win11. It allows to run Linux UI apps in Windows.

When Windows is configured with screen DPI >= 200%, SWT scaling is very bad and the app overall is very hard to use.

Here's an example of GOOD eclipse running in WSLg at DPI=100%:
![01_Eclipse_DPI=100](https://user-images.githubusercontent.com/45797751/200194017-ab10f89d-f278-48a7-b409-ae9f1e7516ba.png)

The same at 200% (BAD, that's what the problem is about):
![02_Eclipse_DPI=200](https://user-images.githubusercontent.com/45797751/200194064-8f3f5a4e-e436-4ff7-adda-a6a90840e73a.png)

And this is how it should be at 200% (note: click image to compare, thumbnails are scaled and confusing)
![03_Eclipse_DPI=200_CairoAutoScale](https://user-images.githubusercontent.com/45797751/200194069-8d6e8097-1d22-4bf3-b915-ec64c897559f.png)

**To Reproduce**
1. Change your screen scaling to 200% in Windows in `Settings > System > Display > Scale`.
2. Run Eclipse in WSLg on Win11 (no special steps needed, just do everything as on proper Linux)
   
**Expected behavior**
Should like on 3rd screenshot, where Control contents fit, Controls themselves are properly sized, etc.

**Screenshots**
See above.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [x] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Win11 WSLg with Ubuntu 20.04

4. JRE/JDK version
Doesn't matter. 

**Version since**
Always since WSLg was released, I think.

**Comment by SyntevoAlex** [comment]
I have debugged and observed the following values

```
WSLg Ubuntu 20.04.4 with Windows DPI=200%
	96  = gdk_screen_get_resolution()
	2   = gdk_monitor_get_scale_factor()
	1   = cairo_surface_get_device_scale()
WSLg Ubuntu 20.04.4 with Windows DPI=100%
	96  = gdk_screen_get_resolution()
	1   = gdk_monitor_get_scale_factor()
	1   = cairo_surface_get_device_scale()
```

I observe the same values on real Ubuntu 22.04. This made me suspect [this line in SWT](https://github.com/eclipse-platform/eclipse.platform.swt/blob/b7d9421/bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Device.java#L711)
```
DPIUtil.setUseCairoAutoScale((sx[0]*100) == DPIUtil.getDeviceZoom() || OS.isGNOME)
```

Indeed, when I patch condition to `true`, problem is solved (see screenshot 2 above).

**Comment by SyntevoAlex** [comment]
This reminds me of [Bug 568641](https://bugs.eclipse.org/bugs/show_bug.cgi?id=568641). There, we struggled to support KUbuntu, which behaved differently from other modern Linux distros, and eventually gave up. If I remember correctly, eventually DPI support in SWT was simplified to get rid of all corner cases and only support modern Linux.

@sravanlakkimsetti Do you think that we should now always `DPIUtil.setUseCairoAutoScale(true)` ?

**Comment by sravanlakkimsetti** [comment]
> @sravanlakkimsetti Do you think that we should now always `DPIUtil.setUseCairoAutoScale(true)` ?

Since ubuntu 18.04 is not supported by eclipse anymore, yes we can get rid of the older implementation and use `DPIUtil.setUseCairoAutoScale(true)`

Old code was there just to support kde on ubuntu 18.04.

**Comment by mbooth101** [comment]
Is this fixed?
