### ISSUE TITLE
SWT FAQ says Eclipse/SWT 4.6.x on Linux needs GTK+ 2.24.0, but Display.java says 2.18.0

### ISSUE THREAD

**Issue by ManuelQS** [eclipse-platform/eclipse.platform.swt#468]
**Describe the bug**
https://www.eclipse.org/swt/faq.php#gtkstartup
Says:

> Q: Which GTK version do I need to run SWT?
> A: SWT requires the following GTK+ versions (or newer) to be installed: 
> ...
> Eclipse/SWT 4.6.x - 4.9.x: GTK+ 2.24.0

I looked into the Linux gtk x86 Display.java Eclipse/SWT version 4.6.3, there's a check against GTK version 2.18.0, so I guess this FAQ entry is wrong. Looks like 4.6.x has the same version requirement on GTK2 as 4.5.x, and this was only upped in 4.7.x to 2.24.0.

**To Reproduce**
Look at the FAQ entry 
https://www.eclipse.org/swt/faq.php#gtkstartup
and compare with code;
https://github.com/eclipse-platform/eclipse.platform.swt/blob/v4629/bundles/org.eclipse.swt/Eclipse%20SWT/gtk/org/eclipse/swt/widgets/Display.java#L452
```
	static final int GTK2_MAJOR = 2;
	static final int GTK2_MINOR = 18;
	static final int GTK2_MICRO = 0;
```

**Expected behavior**
I expected the FAQ entry to match the version given in the code.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [x] Linux
- - [ ] macOS 

**Additional context**
I built an RCP app based on 4.6.3 and tried it on a Linux System that has GTK version 2.22.1, and it worked, I could not find any defects.

**Comment by akurtakov** [comment]
These versions are out of support and I'm not aware of any committer that still pays attention to gtk 2.x. So if you want the faq fixed please provide a PR - you have to edit https://github.com/eclipse-platform/www.eclipse.org-swt/blob/master/faq.php
