### ISSUE TITLE
[Win32][Dark theme] Button with SWT.ARROW style has light background

### ISSUE THREAD

**Issue by betamaxbandit** [eclipse-platform/eclipse.platform.swt#473]
When Eclipse (on Windows) is in Dark Theme (Preferences > General > Appearance > Theme), org.eclipse.swt.widgets.Button widgets with style SWT.ARROW are shown with a light background. Expected to have a dark background.
The screenshot below shows a comparison of how this looks on Ubuntu 20.04 vs Win11_22621:

![SWT ARROW - ubuntu 20 04 vs win11_22621](https://user-images.githubusercontent.com/13015785/203947488-7f78c7f0-123c-4eeb-939c-923901472585.PNG)

**To Reproduce**
From an Eclipse SDK launch a runtime workbench and open the "SWT Controls" view [1].
Choose the Button tab and in Parameters choose SWT.ARROW
Expected: button has a dark background.
Actual: button has a light background.

**Environment**
Windows - Windows11 22H2 10.0.22621.755 and earlier.
Eclipse SDK Version: 2022-12 (4.26) Build id: I20221113-1800

**Workaround (or) Additional context**
None.

Originally reported in:
[Bug 566269](https://bugs.eclipse.org/bugs/show_bug.cgi?id=566269) - [Win32][Dark theme] Check boxes light in the dark theme

[1] "SWT Controls"
eclipse.platform.swt\examples\org.eclipse.swt.examples.views\
https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.examples.views/src/org/eclipse/swt/examples/controls/ControlView.java

**Comment by deepika-u** [comment]
@SyntevoAlex 
Can you please confirm if this is also a windows(windows 11 specifically) theming issue, not an SWT bug. If yes can we close it?

**Comment by SyntevoAlex** [comment]
Yes, I plan to look at it, but not sure how soon. My inbox is too full of things needing attention.

**Comment by deepika-u** [comment]
Hi @SyntevoAlex 

Without the patch seeing the buttons like this 
![image](https://user-images.githubusercontent.com/46807064/235146974-5bc5aedd-d242-43a9-9b66-44b7d9801a19.png)


With the patch i am seeing the buttons like this
![image](https://user-images.githubusercontent.com/46807064/235147147-fcb4226d-17f7-44c3-991e-bf68fe7f3ca8.png)


In the same context, does the background for the tabs named Button, Canvas, Color, Combo, CoolBar, DateTime and so on should also be in dark when we are in dark theme? as compared against linux shared image(shared in the starting of the issue #473)

Thanks alot for your quick fix.

**Comment by betamaxbandit** [comment]
> 

Hi @deepika-u ,

Thanks for testing this. I was going to do that, but haven't got round to it yet. Good to see it working now.

Was your test on Windows 10 or 11?

**Comment by SyntevoAlex** [comment]
> In the same context, does the background for the tabs named Button, Canvas, Color, Combo, CoolBar, DateTime and so on should also be in dark when we are in dark theme?

Please see [Bug 566359](https://bugs.eclipse.org/bugs/show_bug.cgi?id=566359)

**Comment by SyntevoAlex** [comment]
In master now.

**Comment by deepika-u** [comment]
> > 
> 
> Hi @deepika-u ,
> 
> Thanks for testing this. I was going to do that, but haven't got round to it yet. Good to see it working now.
> 
> Was your test on Windows 10 or 11?

I have tried it on below environment 
Eclipse SDK
Version: 2023-06 (4.28)
Build id: I20230426-1800
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Oracle Corporation
Java runtime version: 19.0.1+10-21
Java version: 19.0.1
