### ISSUE TITLE
[GTK4] FileDialog created with SWT.OPEN displays error if no FilterPath set

### ISSUE THREAD

**Issue by joel-majano** [eclipse-platform/eclipse.platform.swt#48]
If a FileDialog is created with SWT.OPEN but setFilterPath is not used to set a path other than the default empty string, the error: "The folder contents could not be displayed" "Operation not supported" is shown.

This does not happen with FileDialog created with SWT.SAVE or if setFilterPath sets the path to something valid. 

Tested using Snippet72 and commenting out all relevant lines that set filter related fields. 

Tracked in #228

**Comment by joel-majano** [comment]
This further only happens if a file name is not set using setFileName.

**Comment by akurtakov** [comment]
This one has been fixed.
