### ISSUE TITLE
CTabFolder.test_nestedTabHighlighting and ContextInformationTest.testContextInfo_hide_focusOut fail since I20221214-0610

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#502]
org.eclipse.swt.tests.junit.Test_org_eclipse_swt_custom_CTabFolder.test_nestedTabHighlighting fails since I20221214-0610

See https://download.eclipse.org/eclipse/downloads/drops4/I20221214-0610/testResults.php

```
expected CTabFolder to not need highlighting without any selection

java.lang.AssertionError: expected CTabFolder to not need highlighting without any selection
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertFalse(Assert.java:65)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_custom_CTabFolder.test_nestedTabHighlighting(Test_org_eclipse_swt_custom_CTabFolder.java:262)
```

**Update**
Also 

org.eclipse.jface.text.tests.contentassist.ContextInformationTest.testContextInfo_hide_focusOut fails since, with
```
N/A

java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.eclipse.jface.text.tests.contentassist.ContextInformationTest.testContextInfo_hide_focusOut(ContextInformationTest.java:117)
```

Reverting commit 961810fe5fb0991171cc0d0f7849fd90e0e350fa fixes the tests, so it is a regression from https://github.com/eclipse-platform/eclipse.platform.swt/pull/451.

@tmssngr : please check.

**Comment by iloveeclipse** [comment]
Note: I have a trivial fix for ContextInformationTest.testContextInfo_hide_focusOut, will push in a moment.

**Comment by akurtakov** [comment]
Thanks @iloveeclipse ! Much appreciated!

**Comment by iloveeclipse** [comment]
Before #451:
![image](https://user-images.githubusercontent.com/964108/207801836-b9cae1cc-0423-4de2-8c95-9f409a778d66.png)


After #451:
![image](https://user-images.githubusercontent.com/964108/207801611-3d958520-2ac0-4aae-a982-19522a4cb07f.png)

**Comment by iloveeclipse** [comment]
Should one change expectation in test_nestedTabHighlighting ???
It looks like now CTabFolder always "highlights" some tab (first one?), before it seem to not, see screenshots above

**Comment by iloveeclipse** [comment]
The original commit was reverted via #503
