### ISSUE TITLE
Revealing item sometimes does not work

### ISSUE THREAD

**Issue by cpfeiffer** [eclipse-platform/eclipse.platform.swt#508]
**Describe the bug**
Sometimes, when asking an item to be revealed in a Tree (e.g. package explorer or project explorer), the item _is_ selected, but not scrolled into the viewport. This happens in particular, when a dialog was shown before (see snippet).

**To Reproduce**
See snippet https://gist.github.com/cpfeiffer/ab68ac010ae22ea10ad4c224dd2a4e45
The corresponding project just needs these dependencies:
- swt
- ~jface~
- ~core.runtime~

Run the demo and click the big area labeled "Click to reveal...". It will pop up a dialog. After closing the dialog, the last item will be reveal()ed, but not scrolled into the view, although it should be. Repeat as often as you want, it toggles between revealing the very first tree item and the very last tree item, but they will never be scrolled into the viewport.

If you comment out the showing of the dialog, reveal()ing will correctly scroll the item into the viewport.

**Update**
Changed the gist to be plain SWT without jface.

**Expected behavior**
The item being reveal()ed should always be scrolled into the viewport.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [X] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
- Debian 11, Debian 12, Unstable
- KDE on Xorg and Wayland

4. JRE/JDK version
- JDK 11 (Adoptium, System)
- Debian JDK 11
 
**Version since**
4.18 at least

**Comment by cpfeiffer** [comment]
Any info on what could be the cause? SWT itself or rather GTK?

**Comment by akurtakov** [comment]
If you can reduce the snippet to pure swt it would help a lot. If I am to guess it's swt bug.

**Comment by laeubi** [comment]
Maybe the issue is if the component has lost focus (due to the dialog?)

**Comment by cpfeiffer** [comment]
It wasn't easy to create a standalone reproducer at all, but I can try to remove the jface dependencies.

**Comment by cpfeiffer** [comment]
I updated the gist to be plain SWT, without jface. The result is the same: it fails to reveal after the dialog popped up.

**Comment by iloveeclipse** [comment]
> After closing the dialog, the last item will be reveal()ed, but not scrolled into the view, although it should be. Repeat as often as you want, it toggles between revealing the very first tree item and the very last tree item, but they will never be scrolled into the viewport.

Snippet works for me on RHEL 7.9 / gtk 3.22 / X11 / latest SWT master.

**Comment by cpfeiffer** [comment]
Now that is fascinating. I just tested with
- eclipse 4.27
- JDK 17
- latest SWT integration build (https://download.eclipse.org/eclipse/downloads/drops4/I20230503-1800/download.php?dropFile=swt-I20230503-1800-gtk-linux-x86_64.zip)
- gtk 3.24.37

and still see the problem. I will try to test it with RHEL 7.9.

**Comment by cpfeiffer** [comment]
It works now. Same eclipse, same SWT, but
- gtk 3.24.38
