### ISSUE TITLE
Button#setAlignment() has no effect when Text and Image are set

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.swt#519]
This was already described in [Bug 172850](https://bugs.eclipse.org/bugs/show_bug.cgi?id=172850):

> setAlignment() is not working for Buttons who hold an image and text at the same time. Maybe this is platform-specific behaviour and can not be worked around but it should be documented in the javadoc of setAlignment() that this has no effect in the described situation.

See also:
- https://github.com/eclipse-m2e/m2e-core/pull/1157#issuecomment-1367513300

**Comment by lathapatil** [comment]
is it only the Javadoc change as it is mentioned WONFIX in bugzilla ?

**Comment by deepika-u** [comment]
I tried the below snippet for Button setAlignment() and not seeing any problem as such.
Can anyone give us more details on this issue if this is not the right snippet to showcase the reported problem.

`package org.eclipse.swt.bugs;
import org.eclipse.swt.*;
import org.eclipse.swt.graphics.*;
import org.eclipse.swt.layout.*;
import org.eclipse.swt.widgets.*;

public class ButtonAlignmentExample {

    public static void main(String[] args) {
        Display display = new Display();
        Shell shell = new Shell(display);
        shell.setText("Button Alignment Example");
        shell.setLayout(new GridLayout(1, false));

        // Load an image (you should replace "imagePath" with your image file path)
        Image image = new Image(display, "C:\\Users\\02236C744\\Desktop\\deepika.png");

        // Create a button with text and image
        Button button = new Button(shell, SWT.PUSH);
        button.setText("Button Text");
        button.setImage(image);

        // Set the alignment to CENTER
        button.setAlignment(SWT.CENTER);

        // Set layout data to center the button in the shell
        button.setLayoutData(new GridData(SWT.CENTER, SWT.CENTER, true, true));

        shell.pack();
        shell.open();

        while (!shell.isDisposed()) {
            if (!display.readAndDispatch()) {
                display.sleep();
            }
        }

        // Dispose of the image and resources
        image.dispose();
        display.dispose();
    }
}`

I have tried on below environment
Eclipse SDK
Version: 2023-09 (4.29)
Build id: I20230830-2200
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 20+36
Java version: 20

**Comment by ptziegler** [comment]
> I tried the below snippet for Button setAlignment() and not seeing any problem as such.

Due to the packing, the button is too small to notice the problem. I've edited your snipped to hopefully make the problem a little bit more clearer.

```
public static void main(String[] args) {
	Display display = new Display();
	Shell shell = new Shell(display);
	shell.setText("Button Alignment Example");
	shell.setLayout(new GridLayout(1, false));

	// Load an image (you should replace "imagePath" with your image file path)
	Image image = ImageDescriptor.createFromFile(Snippet.class, "error_tsk.png").createImage();

	// Create a button with text and image
	Button button = new Button(shell, SWT.PUSH);
	button.setText("Button Text");
	button.setImage(image);
	button.setSize(200, 50);

	// Set the alignment to CENTER
	button.setAlignment(SWT.LEFT);

	// Set layout data to take up the whole shell
	button.setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, true));

	shell.setSize(200, 50);
	shell.open();

	while (!shell.isDisposed()) {
		if (!display.readAndDispatch()) {
			display.sleep();
		}
	}

	// Dispose of the image and resources
	image.dispose();
	display.dispose();
}
```

This is the button that is shown with the code above:
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/70652978/ec432f1f-ae94-4af9-a6fd-3b1eec2973b0)

This is the same button, without the image:
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/70652978/ac1347e9-42af-4361-9184-ced09460d37a)

Both have the style set to SWT.LEFT, so my expectation is that the first button should also be left-aligned.

**Comment by deepika-u** [comment]
@ptziegler 
I picked up images from "..eclipse.platform.ui\bundles\org.eclipse.ui\icons\full\obj16\error_tsk.png" and pasted in my src folder then setting image as below, 

Image image = new Image(display, "src/error_tsk.png");
I am able to see the problem you were reporting.

When image is set 
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/46807064/b8b92dad-29a0-4a21-a2b7-2f26d6656314)

When image is not set seeing as below
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/46807064/b583a77f-75d0-4091-b7fd-429e9183d2b3)


Though in both the cases, left alignment is set but not effective when image is set. 
Thanks for the recreate now i understood the problem.

**Comment by iloveeclipse** [comment]
Is this Windows only issue, or also Mac/Linux?

**Comment by ptziegler** [comment]
> Is this Windows only issue, or also Mac/Linux?

I can reproduce it on both Windows and Linux. I can't say anything about Mac, given that I don't own one.

**Comment by Phillipus** [comment]
On Mac, the image is always on the left and the text is aligned as expected when set to left, center or right.
