### ISSUE TITLE
SWT minor version bump needed for 4.27 M1

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#520]
[This change](https://github.com/eclipse-platform/eclipse.platform.swt/pull/471) was incomplete, it produces API error (obviously)
`The minor version should be incremented in version 3.122.100, since new APIs have been added since version 3.122.0`
https://download.eclipse.org/eclipse/downloads/drops4/I20230102-1800/apitools/analysis/html/org.eclipse.swt/report.html

@laeubi : Please 
1) update SWT bundle version to `3.123.0` in MANIFEST file
2) Update "since" tags on `BusyIndicator` to match the version above `3.123`.
3) Update the pom's and manifests of SWT **fragments** to match host version, see the example list in [2e9528ed10a7a14f9c8afcd9c2fdcf0374773e96](https://github.com/eclipse-platform/eclipse.platform.swt.binaries/commit/2e9528ed10a7a14f9c8afcd9c2fdcf0374773e96)

**Comment by laeubi** [comment]
I think I have done most of it already here:
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/510

but not sure if it will really "fix" things... as a build without VB also succeeds

**Comment by akurtakov** [comment]
Fine in latest I-build.
