### ISSUE TITLE
GitHub: add cross-platform-gui tag

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#524]
So it occurs in this list: https://github.com/topics/cross-platform-gui

**Comment by mickaelistria** [comment]
Done. And if you're willing to promote SWT as a cross-platform-gui further, it would be good to rework the README.md file to at least add a description of SWT, so if some people get to this repo by following the tag, they can relatively quickly understand what it's about, while it's currently not the case at all.

**Comment by tmssngr** [comment]
Please look at https://github.com/eclipse-platform/eclipse.platform.swt/pull/526
