### ISSUE TITLE
Jenkins builds broken

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#531]
See https://github.com/eclipse-platform/eclipse.platform.swt/pull/530 build status.
- https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-530/1/console
- https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-530/2/console

Not sure if https://github.com/eclipse-platform/eclipse.platform.swt/pull/522 was supposed to fix that?

```
Pull request #530 opened
13:33:16 Connecting to https://api.github.com/ using GitHub bot (username/token)
Connecting to https://api.github.com/ to check permissions of obtain list of syntevo for eclipse-platform/eclipse.platform.swt
Loading trusted files from base branch master at 1e63f38c421feeb95fc9e94dbdf04241c2c714e1 rather than d01b7dd4da6f9cdfb359ddb6aad222ce74b1b59f
Obtained Jenkinsfile from 1e63f38c421feeb95fc9e94dbdf04241c2c714e1
[Pipeline] Start of Pipeline
[Pipeline] echo
[WARNING] label option is deprecated. To use a static pod template, use the 'inheritFrom' option.
[Pipeline] podTemplate
[Pipeline] {
[Pipeline] node
Still waiting to schedule task
‘[swtbuild-pod-8z9j2-kmr0j](https://ci.eclipse.org/releng/computer/swtbuild-pod-8z9j2-kmr0j/)’ is offline
```

**Comment by iloveeclipse** [comment]
Reported https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2526

**Comment by iloveeclipse** [comment]
According to IT:
```
According to [#2448 (comment 1059781)](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2448#note_1059781):
Is:

    persistentVolumeClaim:
      claimName: tools-claim-jiro-platform


https://github.com/eclipse-platform/eclipse.platform.swt/blob/1e63f38c421feeb95fc9e94dbdf04241c2c714e1/Jenkinsfile#L77
Should be:

    persistentVolumeClaim:
      claimName: tools-claim-jiro-releng
```

**Comment by iloveeclipse** [comment]
@HannesWell : seems that changes requested for this draft PR https://github.com/eclipse-platform/eclipse.platform.swt/pull/514 cause troubles for the current SWT build in Jenkins.

Please check what is needed now to do - either update Jenkinsfile or move forward with https://github.com/eclipse-platform/eclipse.platform.swt/pull/514 or request another change in the infra.

**Comment by HannesWell** [comment]
> @HannesWell : seems that changes requested for this draft PR #514 cause troubles for the current SWT build in Jenkins.
> 
That's right and I noticed that in two weeks ago already https://github.com/eclipse-platform/eclipse.platform.swt/issues/513#issuecomment-1371416710

> Please check what is needed now to do - either update Jenkinsfile or move forward with #514 or request another change in the infra.

The change mentioned in your Eclipse-infra issue seems reasonable, so I'm about to prepare a PR to adjust the Jenkinsfile. Maybe this already solves this issue.

Nevertheless I would love to proceed in #514, but I'm currently blocked by missing infrastructure, namely the mac-agent that is always down (see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2454) and a missing agent to build SWT-natives for linux-x86_64 (see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2448#note_1059781).
The infra-team is informed, but it looks like they are busy with other stuff. But I'll ping them again.

**Comment by HannesWell** [comment]
Looking at https://ci.eclipse.org/releng/job/eclipse.platform.swt/ and some of the PRs I rebased last night, it looks like the build is back like before.
Thank you @iloveeclipse to bring this up again.

> Not sure if #522 was supposed to fix that?

Yes it was, but it went into the wrong direction as https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2526 has shown. But IIRC I saw different errors and therefore wonder, if something else changed in the meantime.
However, it looks like everything is working now.

**Comment by iloveeclipse** [comment]
@HannesWell : Coming from https://github.com/eclipse-platform/eclipse.platform.swt/pull/535 build fail, I see now different error:

https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-535/2/console
```
Created Pod: kubernetes releng/swtbuild-pod-vtrhh-lfzvp
Still waiting to schedule task
‘[swtbuild-pod-vtrhh-lfzvp](https://ci.eclipse.org/releng/computer/swtbuild-pod-vtrhh-lfzvp/)’ is offline
releng/swtbuild-pod-vtrhh-lfzvp Container jnlp was terminated (Exit Code: 255, Reason: Error)

- container -- running
-----Logs-------------


- jnlp -- terminated (255)
-----Logs-------------
Jan 24, 2023 9:38:29 AM hudson.remoting.Engine startEngine
INFO: Using Remoting version: 4.13.3
Jan 24, 2023 9:38:29 AM org.jenkinsci.remoting.engine.WorkDirManager initializeWorkDir
INFO: Using /home/jenkins/agent/remoting as a remoting work directory
Jan 24, 2023 9:38:29 AM org.jenkinsci.remoting.engine.WorkDirManager setupLogging
INFO: Both error and output logs will be printed to /home/jenkins/agent/remoting
Jan 24, 2023 9:38:30 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://jenkins-ui.releng.svc.cluster.local/releng/]
Jan 24, 2023 9:38:50 AM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: Failed to connect to http://jenkins-ui.releng.svc.cluster.local/releng/tcpSlaveAgentListener/: jenkins-ui.releng.svc.cluster.local
java.io.IOException: Failed to connect to http://jenkins-ui.releng.svc.cluster.local/releng/tcpSlaveAgentListener/: jenkins-ui.releng.svc.cluster.local
	at org.jenkinsci.remoting.engine.JnlpAgentEndpointResolver.resolve(JnlpAgentEndpointResolver.java:214)
	at hudson.remoting.Engine.innerRun(Engine.java:745)
	at hudson.remoting.Engine.run(Engine.java:544)
Caused by: java.net.UnknownHostException: jenkins-ui.releng.svc.cluster.local
```
Is that related to changes on https://github.com/eclipse-platform/eclipse.platform.swt/pull/533 or is this an Eclipse infrastructure issue?

**Comment by iloveeclipse** [comment]
@HannesWell : hold on, the problem **is** in the infra: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2560#note_1068607
