### ISSUE TITLE
[GTK] Shell.open: incorrect order of bringToTop and setVisible

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#536]
**Describe the bug**
The beginning of `Shell.open()` looks as this:
```java
	...
	bringToTop (false);
	setVisible (true);
	...
```
The problem is that `bringToTop` is ignored if the shell is invisible. Hence, `bringToTop` is only invoked as a undesired side-effect of `control.setFocus` (see #450).

**To Reproduce**
Debug a `shell.open` invocation.

**Expected behavior**
`bringToTop` should be invoked after `setVisible`, so it does something useful.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [x] Linux
- - [ ] macOS

**Comment by tmssngr** [comment]
Are there objections against this patch or is currently a release period where no serious pull requests are accepted?

**Comment by tmssngr** [comment]
OK, this sounds reasonable. Removing the `bringToTop (false)` in #536 and reintroduce it in #450 as a fix.

**Comment by iloveeclipse** [comment]
Thanks Thomas, fixed via #537.
