### ISSUE TITLE
GC.copyArea() and Image.getImageData() strange behavior

### ISSUE THREAD

**Issue by MarioMarinatoSTech** [eclipse-platform/eclipse.platform.swt#552]
**Describe the bug**
Taking a screenshot into an Image using `GC.copyArea()` and then using `Image.getImageData()` to create a new one produces a white image.  It doesn't happen when working with an image drawn "by hand".

**To Reproduce**
Snippet:  [WhiteImage.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/10743201/WhiteImage.txt)
This snippet takes a snapshot and then opens a shell with two canvas.
The first draws the image directly, the other creates a new Image using the original's `Image.getImageData()`.
The lines 18 and 21 can be commented / uncommented to change the image used.

**Expected behavior**
Using `Image.getImageData()` should return the correct data and lead to a proper screen shot image.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [ ] Linux
- - [x] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
  macOS Ventura 13.1

3. JRE/JDK version
 Amazon Corretto JDK 11.0.17

**Version since**
As far as I checked, this behavior is happening since SWT 4.18.  Using SWT 4.17 it works as expected.

**Workaround (or) Additional context**
A similar problem was reported years ago on [bug 538487](https://bugs.eclipse.org/bugs/show_bug.cgi?id=538487) and then solved for SWT 4.11.

**Comment by iloveeclipse** [comment]
I assume this is this Mac only issue, I can't reproduce it on Linux. Have you checked if the Windows port also shows same issue?

**Comment by MarioMarinatoSTech** [comment]
Yes, on Windows it works as expected.
I checked on Eclipse 2020-09, 2020-12 and 2022-12.

**Comment by Phillipus** [comment]
This is caused by not specifying the image data zoom level. If you run the snippet at 100% (non-retina) it works. You need to add 200 like this - `new Image(display, image.getImageData(200))`

**Comment by Phillipus** [comment]
I use a custom method of getting the custom scaled image from the ImageData at zoom level. Try this:

```java
import org.eclipse.swt.SWT;
import org.eclipse.swt.custom.ScrolledComposite;
import org.eclipse.swt.graphics.Device;
import org.eclipse.swt.graphics.GC;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.graphics.ImageData;
import org.eclipse.swt.internal.DPIUtil;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.widgets.Canvas;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class WhiteImage {

	public static void main(String[] args) {
		final Display display = new Display();
		
		// Take the screen shot
		Image image = getScreenShot(display);
		
		final Shell shell = new Shell(display);
		shell.setLayout(new FillLayout());
		shell.setText("Print Screen");
		shell.setBounds(50, 50, 1000, 500);
		
		// OK: create and fill a canvas drawing the screen shot directly.
		ScrolledComposite scDirect = new ScrolledComposite(shell, SWT.V_SCROLL | SWT.H_SCROLL);
		Canvas cvsDirect = new Canvas(scDirect, SWT.NONE);
		scDirect.setContent(cvsDirect);
		cvsDirect.setBounds(display.getBounds());
		cvsDirect.addPaintListener(event -> event.gc.drawImage(image, 0, 0));

        // Get scaled image from ImageData
        Image newImage = getAutoScaledImage(image);
        
		ScrolledComposite scImageData = new ScrolledComposite(shell, SWT.V_SCROLL | SWT.H_SCROLL);
		Canvas cvsImageData = new Canvas(scImageData, SWT.NONE);
		scImageData.setContent(cvsImageData);
		cvsImageData.setBounds(display.getBounds());
		cvsImageData.addPaintListener(event -> event.gc.drawImage(newImage, 0, 0));
		
		shell.open();
		
		while (!shell.isDisposed()) {
			if (!display.readAndDispatch())
				display.sleep();
		}
		display.dispose();
	}

	private static Image getScreenShot(final Display display) {
		GC gc = new GC(display);
		final Image image = new Image(display, display.getBounds());
		gc.copyArea(image, 0, 0);
		gc.dispose();
		return image;
	}

    public static Image getAutoScaledImage(Image image) {
        ImageData imageData = image.getImageData(DPIUtil.getDeviceZoom());
        Device imageDevice = image.getDevice();
        return new Image(imageDevice, new DPIUtil.AutoScaleImageDataProvider(imageDevice, imageData, DPIUtil.getDeviceZoom()));
    }
}
```

**Comment by MarioMarinatoSTech** [comment]
Whoa, great!  Indeed, your solution works.
Thank you very much!  
I believe the issue can be closed.
