### ISSUE TITLE
[Windows] Scroll bars are wider at 200% scaling

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.swt#554]
**Describe the bug**
Using Eclipse on Windows 11 at 100% scaling, scroll bars are quite thin (expected behaviour). Setting the native display to 200% (for example, with 4k display) and the scroll bars are very wide.

**To Reproduce**
Start Eclipse with native display set to 200%.

**Expected behavior**
Scrollbars should be the same width at 100% and at 200% scaling.

**Screenshots**

At 100%:

![win100](https://user-images.githubusercontent.com/600504/219634989-9deccdee-da46-4d15-93ae-8b836e5e3429.png)

At 200%:

![win200](https://user-images.githubusercontent.com/600504/219634996-9ef72f54-15d9-4f99-93c2-e8343b8d3ef4.png)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Windows 11 Pro.
4k monitor at 200% scaling.

4. JRE/JDK version
JDK 17

**Workaround (or) Additional context**
The scrollbar width seems to be set at Eclipse startup.
I can set the native display to 100%, start Eclipse, then set the native display to 200% and the scrollbars remain thin.

**Comment by deepika-u** [comment]
@Phillipus 
I have checked on the scaling of 100% and 200% on windows 11 and please find my observations below
1. I have checked the scroll bars on word. Seeing as below screen shot(top circled part corresponds to 100% and bottom circled part corresponds to 200% scaling). -> 
![Scaling_word_100Left_200Right](https://user-images.githubusercontent.com/46807064/220836721-7a0d771b-8861-42f9-87f4-38bb228c3791.jpg)

2. I have checked the scroll bars on notepad. Seeing as below screen shot. To be specific when it is hovered the horizontal scroll bar widens up(as shown in the image) where as vertical scroll bar is as-is at different scaling levels. From screen shot top 2 circles corresponds to 100% and bottom 2 circles corresponds to 200% scaling.
![Scaling_notepad_100top_200bottom](https://user-images.githubusercontent.com/46807064/220836838-3fefe17f-c3e8-4966-8423-82f502e25984.jpg)

In both the native applications the vertical scroll bars are not of same width and horizontal hovered scroll bars heights are not same. This is the same as we are seeing on the eclipse as well.

**Comment by Phillipus** [comment]
Thanks for you findings, @deepika-u 

However, on Windows 11 at 100% and at 200% scaling I see thin scrollbars in Notepad and native apps such as Firefox and Thunderbird (and several other apps I tested). In my findings it is only SWT that uses thicker scrollbars at 200% scaling.

Perhaps there is a Windows 11 native method that needs to change for scrollbars similar to the change that @SyntevoAlex made for the Button class here[?](https://github.com/Phillipus/eclipse.platform.swt/commit/43187fa1ce25eb04c7fe417ffd3e1f7bb025577f)

**Comment by SyntevoAlex** [comment]
SWT in dark theme uses `Explorer` theme for many controls, including Table/Tree. If you check Windows Explorer at DPI=200%, you'll see the same thick scrollbar thumb. Notepad seems to use some other kind of theme.

This is pretty much a matter of tastes issue to me. It's weird that Windows theme looks different at different DPI, maybe a "bug" in Windows.

**Comment by Phillipus** [comment]
> If you check Windows Explorer at DPI=200%

Is this on Windows 11?

**Comment by SyntevoAlex** [comment]
Yes, I use Win11 as main Windows for SWT development currently.

**Comment by SyntevoAlex** [comment]
Is that not true for you? I mean, open Windows Explorer, the default Windows file manager, and make a screenshot of scrollbars there at DPI=200%

**Comment by Phillipus** [comment]
> Is that not true for you? I mean, open Windows Explorer, the default Windows file manager, and make a screenshot of scrollbars there at DPI=200%

Yes, you're right, it is true for Explorer. But not for the Windows Settings app, Firefox, Thunderbird, and a few third-party apps. I guess it's just one of those things.

> It's weird that Windows theme looks different at different DPI, maybe a "bug" in Windows.

And if there's no magic switch in SWT to change this behaviour I should close this one...

**Comment by SyntevoAlex** [comment]
Tree and Table controls are kind of special, they have significant visual difference in Explorer theme. I would suspect that trying to switch to any other theme will cause significant number of other problems. I also think that this is merely an oversight in Windows and will be fixed soon.

**Comment by Phillipus** [comment]
OK. Thanks for the insights. I'll close this one then to keep the noise down....

**Comment by Phillipus** [comment]
...one more thing. I found this:

https://techcommunity.microsoft.com/t5/windows-11/scroll-bar-ui-is-broken-in-hidpi/m-p/3386940

They say:

> This happens only in the Win32 UI, not in the UWP UI.

**Comment by SyntevoAlex** [comment]
This might explain, because all those Settings apps are likely UWP. I think newest Notepad is UWP too. But SWT is a "native desktop" app, like most other apps.

**Comment by Phillipus** [comment]
I still don't see how the 100% vs 200% thing affects it. 😕

**Comment by SyntevoAlex** [comment]
If you're curious, get `msstyleEditor` app, and open `%windir%\Resources\Themes\Aero\aero.msstyles` with it. You'll beable to inspect contents of Windows theme.

**Comment by SyntevoAlex** [comment]
> I still don't see how the 100% vs 200% thing affects it.

Windows themes usually have different images for different DPI. It's likely that they used different images by accident, or forgot to put one of the images, or something like that.

**Comment by SyntevoAlex** [comment]
I looked myself, but could only see the good thin thumb image in `Scrollbar`. Not sure why.
