### ISSUE TITLE
Migrate still relevant SWT wiki pages

### ISSUE THREAD

**Issue by trancexpress** [eclipse-platform/eclipse.platform.swt#559]
The Eclipse wiki is getting shut down and deleted, so we must migrate pages that are still useful.

See: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/681

Essentially we'll try the automatic process: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/681#note_414703

> Export the pages you want to convert from https://wiki.eclipse.org/Special:Export,  save the file to /tmp/wikiexport (or somewhere else, but adjust below accordingly) then

```
docker run -it --rm -v /tmp/wikiexport:/wikiexport --entrypoint /bin/bash php:8
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
apt-get update && apt-get install -y git vim pandoc
git clone https://github.com/outofcontrol/mediawiki-to-gfm.git
cd mediawiki-to-gfm
composer update --no-dev
./convert.php --filename=/wikiexport/Eclipsepedia-.xml --output=/wikiexport/markdown/
```

Note that this doesn't export images.

We'll have to gather pages we want to migrate first, since unlike JDT I don't find an SWT category.

**Comment by trancexpress** [comment]
After searching for "SWT" on the wiki, I find these pages that seem relevant:

- https://wiki.eclipse.org/SWT
- https://wiki.eclipse.org/SWT/Beginners
- https://wiki.eclipse.org/SWT/Developer_Guide
- https://wiki.eclipse.org/FAQ_What_is_SWT%3F
- https://wiki.eclipse.org/FAQ_Why_does_Eclipse_use_SWT%3F
- https://wiki.eclipse.org/FAQ_Is_SWT_platform-specific%3F
- https://wiki.eclipse.org/FAQ_Is_SWT_better_than_Swing%3F
- https://wiki.eclipse.org/FAQ_Can_I_use_SWT_outside_Eclipse_for_my_own_project%3F
- https://wiki.eclipse.org/FAQ_Are_there_any_visual_composition_editors_available_for_SWT%3F
- https://wiki.eclipse.org/FAQ_How_do_I_display_a_Web_page_in_SWT%3F
- https://wiki.eclipse.org/FAQ_How_do_I_embed_AWT_and_Swing_inside_SWT%3F
- https://wiki.eclipse.org/FAQ_Where_can_I_find_more_information_on_SWT%3F
- https://wiki.eclipse.org/FAQ_How_do_I_create_an_executable_JAR_file_for_a_stand-alone_SWT_program%3F
- https://wiki.eclipse.org/FAQ_How_do_I_configure_an_Eclipse_Java_project_to_use_SWT%3F
- https://wiki.eclipse.org/SWT_Widget_Style_Bits
- https://wiki.eclipse.org/SWT/Native_Builds_on_Foundation
- https://wiki.eclipse.org/SWT/Devel/Workflow (partially outdated due to bugzilla and gerrit sections)
- https://wiki.eclipse.org/SWT/Devel/Gtk/platformTests
- https://wiki.eclipse.org/SWT/Devel/Gtk/os_custom
- https://wiki.eclipse.org/SWT/Devel/Gtk
- https://wiki.eclipse.org/SWT/Devel
- https://wiki.eclipse.org/SWT/Devel/Gtk/Dev_guide
- https://wiki.eclipse.org/SWT/Devel/Gtk/pkg-config_compiled_GTK
- https://wiki.eclipse.org/SWT/Devel/Gtk/Wayland
- https://wiki.eclipse.org/SWT/Devel/Gtk/Atk (no idea if this is dead)
- https://wiki.eclipse.org/SWT/Devel/Gtk/Compiling_Gtk
- https://wiki.eclipse.org/SWT/Devel/Gtk/Version_specific_macro
- https://wiki.eclipse.org/SWT/Devel/Gtk/Sentinel_warning
- https://wiki.eclipse.org/SWT/Devel/Gtk/Useful_Eclipse_shortcuts
- https://wiki.eclipse.org/SWT/Devel/Gtk/NonAsciiCharacters
- https://wiki.eclipse.org/SWT/Devel/Gtk/PI
- https://wiki.eclipse.org/SWT/Devel/Gtk/Missing_so_file_errors
- https://wiki.eclipse.org/SWT/Devel/Gtk/GtkVersion
- https://wiki.eclipse.org/SWT/Devel/Gtk/GNOME_icons
- https://wiki.eclipse.org/SWT/Devel/Gtk/GtkPackageFedora
- https://wiki.eclipse.org/SWT/Devel/Gtk/JUnitTests
- https://wiki.eclipse.org/SWT/Devel/Gtk/Errors_after_repository_reset
- https://wiki.eclipse.org/SWT/Devel/Gtk/CSS_selector
- https://wiki.eclipse.org/SWT/Devel/Gtk/Patch_guidelines (mentions compiling against GTK2, will have to remove this)
- https://wiki.eclipse.org/SWT/Devel/Gtk/jhbuild

Those 2 might belong elsewhere, but we should port them too. The JFace snippets are too important to lose:

- https://wiki.eclipse.org/SWT/Devel/Gtk/jface
- https://wiki.eclipse.org/JFaceSnippets

Maybe the JFace page is already ported, since links have been updated to point to GitHub.

**Comment by trancexpress** [comment]
Some linked pages that I missed, which will have to be migrated as well:

- https://wiki.eclipse.org/SWT/Devel/Style
- https://wiki.eclipse.org/SWT/Committer_Handbook (very outdated, but linked)

**Comment by trancexpress** [comment]
Some linked pages that I missed, which will have to be migrated as well:

- https://wiki.eclipse.org/SWT/Devel/Style
- https://wiki.eclipse.org/SWT/Committer_Handbook (very outdated, but linked)
- https://wiki.eclipse.org/Equinox/dev/gtk

**Comment by akurtakov** [comment]
https://wiki.eclipse.org/Equinox/dev/gtk has nothing to do with SWT. It's equinox launcher.

**Comment by trancexpress** [comment]
We can move the migrated page to another wiki, once one is available (here I guess? https://github.com/eclipse-equinox/equinox).

For now the page looks useful so I'll migrate it here. Or is there an already existing wiki where I could "attach" it?

**Comment by akurtakov** [comment]
I'm not aware of other wiki. I just point that it's the wrong place to put launcher content in swt as even the way launcher uses native libraries is totally different compared to SWT (at least in the GTK case).

**Comment by trancexpress** [comment]
@iloveeclipse can you create the wiki page for SWT? I don't have the `settings` button for whatever reason. I think I'm done with the migration, possibly a few relevant pages (that I didn't find/notice) will be missing.

**Comment by iloveeclipse** [comment]
@akurtakov can.

**Comment by mickaelistria** [comment]
What about pushing the documentation together with the source in a documentation folder? That would be much better in term of traceablilty and quality, as reviews and PRs will be encouraged.

**Comment by trancexpress** [comment]
> What about pushing the documentation together with the source in a documentation folder? That would be much better in term of traceablilty and quality, as reviews and PRs will be encouraged.

I'm not sure if the wiki functionality of GitHub will work then (what little there is of it). We would also have to relink all images and pages in the migrated content, since the wiki pages need specific paths for those links (they are not just relative paths).

I'm also not sure if there will be anyone to review and maintain the wiki pages, both now and in future.

And of course the JDT core wiki is already a wiki. No idea if there are other Eclipse projects that have their wiki pages on GitHub or "embedded" wiki in the repository itself. But ideally what we do is consistent across projects.

**Comment by akurtakov** [comment]
My preferences are as follow:
* Markdown files next to code
* Platform global wiki https://github.com/eclipse-platform/.github/wiki/

As we are looking to reduce number of platform git repo putting things into some git repo wiki may raise the need to migrate again .

**Comment by iloveeclipse** [comment]
- One thing to consider regarding merge to the code repo is licensing - the **existing** wiki content is not under ECA, so strictly speaking one can't just merge it with the code.
- Beside this, just as stupid github user I would expect wiki to be under wiki, not under code. There must be a reason github provided dedicated "wiki"s.
- If contributing to the wiki would be problematic, one should ask github to improve that, not reinvent the wheel.

Regarding global wiki: yes, but probably better that one can **link** to the SWT one? Currently github renders all wiki pages flat in the navigation bar on the right side, so that will be overcrowded by default. 
See example https://github.com/trancexpress/eclipse.jdt.core/wiki/

**Comment by mickaelistria** [comment]
> One thing to consider regarding merge to the code repo is licensing - the existing wiki content is not under ECA, so strictly speaking one can't just merge it with the code.

That's a very valid concern! and could indeed be a blocker.
However, it's a grey area, just like wiki.eclipse.org: the GitHub wiki happens to be a hidden GitHub repo under the same repository owner, which means that it is easy to assume that the IP rules that regulates other GitHub repos of the same owner (eclipse-platform) do apply to the wiki...
See, the problem here is that the project does have a lot of documentation that was not provided under proper contribution process (because wiki doesn't easily allow some process) and thus we have to deal with IP troubles. Making documentation a first-class citizen, just like code. And going for more wiki is just making the problem bigger. So even if we can't move the existing content out of wiki, we should really avoid wiki for the future as it's a cause of problems when such migration or just when we want to just copy-paste code from wiki.

> Beside this, just as stupid github user I would expect wiki to be under wiki, not under code. There must be a reason github provided dedicated "wiki"s.

User don't look for wiki, they look for documentation. Whether this is a website, a markdown file, a wiki, or whatever else is a technical choice of the project. People in Platform are used to say "wiki" for documentation, but realistically it's not the wiki model (ie anyone edits, no review) which we're referring to when we say wiki, it's "documentation in the wiki". If the documentation moves someplace else, things will still work.

> If contributing to the wiki would be problematic, one should ask github to improve that, not reinvent the wheel.

I believe GitHub wiki is equally problematic as wiki.eclipse.org.
IMO, The model of the wiki is by nature problematic and much weaker than the plain "markdown files in a Git repo" model. Wikis do not match current domain standards for collaboration and quality (easy reviews, notifications, ability to add automated quality gates, including IP validation gates...); while documentation inside a GitHub repo provides the necessary features.

**Comment by laeubi** [comment]
I think it clearly depends on the type of content:

- Technical documentation and / or contributor guidance should go the the "code place"
- User / Demo should go to some kind of "Webpage" (wiki, gh-pages, ...) with an easy to reference URL

Beside that, if I edit a (eclipse) wiki page, I must acknowledge that I'm fine with anyone editing (authoring?) my text in any way **OR** that it already was copied from the public-domain. Details are at https://wiki.eclipse.org/Eclipsepedia:Copyrights (what actually do not include any details...), so one can assume, that any content is either public domain or something similar to CC-SA.

Neverless the gh wiki has the advantage that (like the old wiki) anyone can edit/enhance this with just a github account, no PR is required, and not polluting the git history and it has a clear link on the repository so people can easily find it.

**Comment by mickaelistria** [comment]
> Neverless the gh wiki has the advantage that (like the old wiki) anyone can edit/enhance this with just a github account, no PR is required, and not polluting the git history and it has a clear link on the repository so people can easily find it.

You usually don't want any random user to potentially break your documentation.
You usually want to track contributions of documentation as regular contributions to properly include their contributors to the "team" of active contributors.
You should usually not consider that documentation is pollution and not worth being part of the history.

I think all those arguments in favor of a wiki only stand if you do not consider documentation as a serious artifact nor documentation contributors as a serious contributors. Ie documentation is a 2nd-class citizen, something we do not want to care about as a project team. If there is a general agreement in the project that we do not want to care properly about documentation, wiki is the right technology; if we want better documentation and better inclusion of documentation contributors in the community, then wiki will be a disservice.
So it's not just a technical choice, the technology to choose depends on how we decide as a project to "own" the documentation.

**Comment by laeubi** [comment]
> You usually don't want any random user to potentially break your documentation.

This implies that the main intention of users is to break your documentation, I can't find any indication for this (the current wiki is also editable by "random" users...)

> You should usually not consider that documentation is pollution and not worth being part of the history.

Every wiki has a version history as well, you can even create PRs for wiki pages.

> You usually want to track contributions of documentation as regular contributions to properly include their contributors to the "team" of active contributors.

Why are contributions to a wiki not "regular contributions"?

> I think all those arguments in favor of a wiki only stand if you do not consider documentation as a serious artifact nor documentation contributors as a serious contributors. 

I can't find any evidence for this claim, e.g. currently javadoc is not "seriously taken" (e.g. we only deploy some kind of dummy javadoc to maven central) even though this is as close as possible to the code...

> So it's not just a technical choice, the technology to choose depends on how we decide as a project to "own" the documentation.

I can only observe that the reality is that no one really cares (see javadoc) or likes to dedicate work towards such approach right now, so for me its fair enough to "save" the current state in a (global) wiki and if anyone is eager to migrate it to several maintained build artifacts that's perfectly fine but I won't count on that.

I even started some initative to start with migrating the release notes to "where the code is" ... but beside some "interesting idea and contributions are welcome but please don't change anything" it has not gotten much spin ... even the smallest step, migrating to html5 and having basic validation is lingering around without any interest, instead we copy stuf around manually for each release, so for me it feels there is not much interest in improving this and therefore would assume there is not so much interest for some kind of major rework of the contents from the wiki.

SO one option would be to simply push all the wikistuff in whatever maschine/human readable text file format and see if/what people are missing and if anyone will then migrate parts of it to whatever place...

**Comment by iloveeclipse** [comment]
> Beside that, if I edit a (eclipse) wiki page, I must acknowledge that I'm fine with anyone editing (authoring?) my text in any way OR that it already was copied from the public-domain. Details are at https://wiki.eclipse.org/Eclipsepedia:Copyrights (what actually do not include any details...), so one can assume, that any content is either public domain or something similar to CC-SA.

CC-SA or public domain on some page on the wiki is not same as ECA, which you have **explicitly** sign off.

Beside legal question I count 3 opinions for putting into the *some* wiki and one for putting that into the code. 

Considering that we wouldn't change much to the "original" state where the wiki was separated from code, and that bringing it closer to github is already an improvement, remaining question for me would be if that should go to the "global one" or "SWT own".

I see it not written in stone where the final content will be at github, but it **has to be migrated** to github initially and we (Simeon and me) offer the project our **paid** time to do that work.

Could we please just enable SWT wiki, let people that actually **want** to do the job of wiki migration to do the migration job and looking on the results in SWT decide if we want do a simply copy/paste/move of migrated content to the global page?

**Comment by mickaelistria** [comment]
> Could we please just enable SWT wiki

Done.

**Comment by laeubi** [comment]
By the way just in case one wants that only contributors can commit to the wiki (I just think it will complicate things!) I remember there was an option to limit  access to only committer see https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis but one needs to ask infrateam fro this as far as I know.

> CC-SA or public domain on some page on the wiki is not same as ECA, which you have explicitly sign off.

I just wanted to note that the old wiki already has some "license" but its not very clear, and if its public domain or CC that *might* be compatible with EPL content (that do not mean it *becomes* ELP licensed!)

**Comment by trancexpress** [comment]
OK, migrated wiki pages are pushed now. There might be a few missing as indicated earlier and the pages with `Misc-` prefix likely belong to another wiki space / project repository.

We can keep discussing here if we want the pages in the SWT repository or as a separate wiki. Moving the pages to the SWT repository will be some work to redirect the links, but personally I don't have a preference. As long as the info from the pages is not lost when the Eclipse wiki is shutdown, its the same to me.

**Comment by trancexpress** [comment]
@iloveeclipse  do we want to migrate the SWT bot pages too? https://wiki.eclipse.org/Category:SWTBot

**Comment by akurtakov** [comment]
FYI https://projects.eclipse.org/projects/technology.swtbot

**Comment by trancexpress** [comment]
Closing this, if there is anything left to discuss please comment and re-open.
