### ISSUE TITLE
Consider to make use of project Panama

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#560]
Newer non-LTS-Java versions have a pure-Java foreign function interface (called project Panama) which should be up to 3-4x faster in calling Java code from native. Maybe this might be useful sooner or later to be used as base of SWT, also because then one SWT jar for all platforms would be sufficient.

**Comment by akurtakov** [comment]
I hope that this goes stable in Java 21 and next June swt can make use of it. Although I would start with places that use jna currently first.

**Comment by Phillipus** [comment]
How would a dependency on Java 21 be managed in SWT?

**Comment by akurtakov** [comment]
In my eyes SWT will require Java 21.

**Comment by laeubi** [comment]
There is already a discussion about this, I suggest to continue there: 
- https://github.com/eclipse-platform/eclipse.platform.swt/discussions/175

But why Java 21? Java 17 should have all the basics required already .... For differences between Java releases one can use so called [Multi-Release Jars](https://openjdk.org/jeps/238), and even if currently there is no first-class support it would be possible to add such to Tycho if required, I'm also trying to get better support for this in JDT see:
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/265
- https://github.com/eclipse-tycho/tycho/issues/322

so if your are interested in such topics just leave a note ad the mentioned issues/discussions.
