### ISSUE TITLE
Drawing transparent image fail on windows on 2022-09 or 2022-12

### ISSUE THREAD

**Issue by wzhonggo** [eclipse-platform/eclipse.platform.swt#561]
**Describe the bug**
Drawing transparent image fail on windows on 2022-09 or 2022-12. But it is ok on 2022-06. The releate change is https://github.com/eclipse-platform/eclipse.platform.swt/commit/36091a0a057565596b97242c6230ea08bf07fabd.
Is there another way to get transparent image.

https://stackoverflow.com/questions/52950289/drawing-a-dynamic-transparent-image-over-another-image-using-swt-graphics/52998727#52998727

**To Reproduce**
```java

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.eclipse.draw2d.ColorConstants;
import org.eclipse.draw2d.SWTGraphics;
import org.eclipse.swt.SWT;
import org.eclipse.swt.graphics.GC;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.graphics.ImageData;
import org.eclipse.swt.graphics.ImageLoader;


public class SWTGraphicsTest {

	public static void main(String[] args) throws Exception {

	
		testWithSWTGraphics();
	}

	private static void testWithSWTGraphics() throws IOException {

		final int width = 300;
		final int height = 300;

		final Image src = new Image(null, width, height);

		final GC gc = new GC(src);
		SWTGraphics imageGC = new SWTGraphics(gc);
		imageGC.setAdvanced(true);
		imageGC.setTextAntialias(SWT.ON);

		imageGC.setAntialias(SWT.ON);

		// This sets the alpha on the entire canvas to transparent
		imageGC.setAlpha(0);
		imageGC.fillRectangle(0, 0, width, height);

		// Reset our alpha and draw the ovals
		imageGC.setAlpha(255);
//		Font font = new Font(null, "Ubuntu", 20, SWT.BOLD);
//		imageGC.setFont(font);
//		imageGC.setForegroundColor(ColorConstants.green);
//		imageGC.setBackgroundColor(ColorConstants.green);
//		imageGC.drawText("Button", 0, 0);
//
		imageGC.setForegroundColor(ColorConstants.red);
		imageGC.setBackgroundColor(ColorConstants.red);
		imageGC.fillRectangle(50, 50, 25, 25);

		imageGC.dispose();

		ImageData imageData = src.getImageData();

		
		imageData.alphaData = new byte[width * height];

		// This is the hacky bit that is making assumptions about
		// the underlying ImageData. In my case it is 32 bit data
		// so every 4th byte in the data array is the alpha for that
		// pixel...
		for (int idx = 0; idx < (width * height); idx++) {
			final int coord = (idx * 4) + 3;
			String platform = SWT.getPlatform();
			if ("win32".equals(platform)) {
				//windows change painted area's alpha value
				imageData.alphaData[idx] =(byte) ( imageData.data[coord]);
			} else {
				//OSX leaves 0 alpha painted area in 0 alpha, unless it needs to be touched to change to a different alpha value, e.g. anti-alias
				imageData.alphaData[idx] =(byte) (255- imageData.data[coord]);
			}

		}



		ByteArrayOutputStream result = new ByteArrayOutputStream();
		ImageLoader imageLoader = new ImageLoader();
		imageLoader.data = new ImageData[] { imageData };
		imageLoader.save(result, SWT.IMAGE_PNG);
		SimpleDateFormat dateFormat = new SimpleDateFormat();
		dateFormat.applyPattern("yyyy.MM.dd.HH.mm.ss");
		String fileName = dateFormat.format(new Date())+"-image.png";
		String userHomeDir = System.getProperty("user.home");
		File file = new File(userHomeDir + File.separatorChar,
				fileName);

		FileOutputStream fos = new FileOutputStream(file);
		fos.write(result.toByteArray());
		fos.close();

	}
}

```

**Expected behavior**
The image should be transparent

**Screenshots**
![2023 02 27 15 22 30-image](https://user-images.githubusercontent.com/2763532/221500445-37c44f94-d080-467d-8caf-2ee35a6b3e02.png)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Windows 10

3. JRE/JDK version
 LibericaJDK 17.0.6 

**Version since**
 Eclipse 2022-09

**Comment by Phillipus** [comment]
I've been trying to do something similar and this might explain why it's not working. I reverted the change in https://github.com/eclipse-platform/eclipse.platform.swt/commit/36091a0a057565596b97242c6230ea08bf07fabd to test and it works OK.

@jonathan-meier is there a way to workaround this case?

**Comment by SyntevoAlex** [comment]
Poor @jonathan-meier , he's getting backfire from the entire history of SWT painting issues. Know that I root for you!

**Comment by laeubi** [comment]
> @jonathan-meier is there a way to workaround this case?

Have you tried simply init the alpha image data with all `0xFF` or `0x00` at laest the commit mentions that this should be used.

**Comment by Phillipus** [comment]
From what I can see the original alphaData is not set because this test evaluates to false whereas before it evaluated to true:

https://github.com/eclipse-platform/eclipse.platform.swt/blob/25f3026262dade54b9188e8e92f1d35dd7b28130/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/graphics/Image.java#L1619

**Comment by jonathan-meier** [comment]
The problem is that the `Image` constructor only taking width/height (`new Image(null, width, height)`) creates an RGB image, but you need an RGBA image. To create an RGBA image, you have to construct an `Image` from `ImageData` where either `ImageData.alpha` is set to something different than `-1` or `ImageData.alphaData` is an array containing an alpha value for each pixel.

**Comment by laeubi** [comment]
Yes ImageData -> imaga, but what the "problem"? So maybe one want another constructor (alphaChanel = true/false)?

**Comment by jonathan-meier** [comment]
Yeah, with "problem" I'm referring to the issue observed in the snippet provided by @wzhonggo that the output image does not have transparency.

To avoid having to create an `ImageData` instance for RGBA images, we could indeed introduce another constructor, but we'd have to do so for all platforms.

**Comment by jonathan-meier** [comment]
For completeness, this works (note that the `alphaData` hack is no longer necessary as the returned `ImageData` already has `alphaData` correctly populated):
```
	private static void testWithSWTGraphics() throws IOException {
		final int width = 300;
		final int height = 300;

		// create RGBA image data
		final ImageData initImageData = new ImageData(width, height, 32, new PaletteData(0xFF0000, 0xFF00, 0xFF));
		initImageData.alphaData = new byte[width * height];
		final Image src = new Image(null, initImageData);

		final GC gc = new GC(src);
		SWTGraphics imageGC = new SWTGraphics(gc);
		imageGC.setAdvanced(true);
		imageGC.setTextAntialias(SWT.ON);

		imageGC.setAntialias(SWT.ON);

		// This sets the alpha on the entire canvas to transparent
//		imageGC.setAlpha(0);
		imageGC.fillRectangle(0, 0, width, height);

		// Reset our alpha and draw the ovals
		imageGC.setAlpha(0);
//		Font font = new Font(null, "Ubuntu", 20, SWT.BOLD);
//		imageGC.setFont(font);
//		imageGC.setForegroundColor(ColorConstants.green);
//		imageGC.setBackgroundColor(ColorConstants.green);
//		imageGC.drawText("Button", 0, 0);
//
		imageGC.setForegroundColor(ColorConstants.red);
		imageGC.setBackgroundColor(ColorConstants.red);
		imageGC.fillRectangle(50, 50, 25, 25);

		imageGC.dispose();

		ImageData imageData = src.getImageData();

		ByteArrayOutputStream result = new ByteArrayOutputStream();
		ImageLoader imageLoader = new ImageLoader();
		imageLoader.data = new ImageData[] { imageData };
		imageLoader.save(result, SWT.IMAGE_PNG);
		SimpleDateFormat dateFormat = new SimpleDateFormat();
		dateFormat.applyPattern("yyyy.MM.dd.HH.mm.ss");
		String fileName = dateFormat.format(new Date())+"-image.png";
		String userHomeDir = System.getProperty("user.home");
		File file = new File(userHomeDir + File.separatorChar,
				fileName);

		FileOutputStream fos = new FileOutputStream(file);
		fos.write(result.toByteArray());
		fos.close();
	}
```

**Comment by Phillipus** [comment]
> For completeness, this works (note that the alphaData hack is no longer necessary as the returned ImageData already has alphaData correctly populated):

Thank-you for that, that's very helpful. :-)

**Comment by Phillipus** [comment]
Setting the image data and alpha data works on Windows, but not Mac.

Here's a simpler snippet:

```java
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.eclipse.swt.SWT;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.graphics.GC;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.graphics.ImageData;
import org.eclipse.swt.graphics.ImageLoader;
import org.eclipse.swt.graphics.PaletteData;

public class Snippet {

    public static void main(String[] args) throws Exception {
        final int width = 300;
        final int height = 300;

        // create RGBA image data
        ImageData initImageData = new ImageData(width, height, 32, new PaletteData(0xFF0000, 0xFF00, 0xFF));
        initImageData.alphaData = new byte[width * height];

        Image src = new Image(null, initImageData);
        GC gc = new GC(src);
        
        // This will give us a tansparent background
        gc.setAlpha(0);
        
        // strangely, we don't don't need to do this to have a transparent background
        //gc.fillRectangle(0, 0, width, height);

        gc.setAlpha(255);
        gc.setBackground(new Color(null, 255, 0, 0));
        gc.fillRectangle(50, 50, 200, 200);

        gc.dispose();

        ImageData imageData = src.getImageData();

        ByteArrayOutputStream result = new ByteArrayOutputStream();
        ImageLoader imageLoader = new ImageLoader();
        imageLoader.data = new ImageData[]{imageData};
        imageLoader.save(result, SWT.IMAGE_PNG);
        SimpleDateFormat dateFormat = new SimpleDateFormat();
        dateFormat.applyPattern("yyyy.MM.dd.HH.mm.ss");
        String fileName = dateFormat.format(new Date()) + "-image.png";
        String userHomeDir = System.getProperty("user.home");
        File file = new File(userHomeDir + File.separatorChar, fileName);

        FileOutputStream fos = new FileOutputStream(file);
        fos.write(result.toByteArray());
        fos.close();
    }
}
```

On Windows:

![2023 02 27 15 13 59-image](https://user-images.githubusercontent.com/600504/221602587-5277f0bd-1b1f-4f5c-80fd-4f528adb4116.png)

On Mac:

![2023 02 27 15 07 36-image](https://user-images.githubusercontent.com/600504/221602688-9a830a48-1f27-48bf-87b1-f6c8fcc10be5.png)

**Comment by wzhonggo** [comment]
@jonathan-meier The new code still not work.
![2023 02 28 08 43 40-image](https://user-images.githubusercontent.com/2763532/221722785-4559792c-6c97-4505-92a0-87f763442a73.png)

**Comment by Phillipus** [comment]
@wzhonggo Your original snippet is working on Mac and Linux, but not on Window since https://github.com/eclipse-platform/eclipse.platform.swt/commit/36091a0a057565596b97242c6230ea08bf07fabd The only thing I can suggest is to fork SWT and build your own SWT for Windows.

**Comment by wzhonggo** [comment]
@Phillipus  Ok.  I will try to use [Eclipse fragment](https://www.vogella.com/tutorials/EclipseFragmentProject/article.html) to revert change.

**Comment by kentxu** [comment]
> @wzhonggo Your original snippet is working on Mac and Linux, but not on Windows since [36091a0](https://github.com/eclipse-platform/eclipse.platform.swt/commit/36091a0a057565596b97242c6230ea08bf07fabd) The only thing I can suggest is to fork SWT and build your own SWT for Windows and revert the breaking change.

The example @wzhonggo  posted does not really work on Mac. The original intention is to paint text/shape onto a SWT image and produce a png with only the painted area in solid color while the rest of the "unpainted" pixels (the background) remain transparent. 

On Mac, the image data byte array sequences are different than windows. The logic in that snippet effectively sets the alpha to 255. That's because the byte array sequence is ARGB on Mac.  So that code is actually operating on "blue" byte. 255-0 (blue) =255.

As far as I know, there was no way to do what Gong needed on Mac using SWT, short of doing a bg color removal which does not produce a good result with anti-alias text.  But it used to work on Windows with the first snippet he posted. Until  https://github.com/eclipse-platform/eclipse.platform.swt/commit/36091a0a057565596b97242c6230ea08bf07fabd broke that.

**Comment by jonathan-meier** [comment]
@wzhonggo my bad, I messed up the two calls to `setAlpha`. I edited the snippet in my comment above, please try it again. Sorry for the confusion!

**Comment by wzhonggo** [comment]
> @wzhonggo my bad, I messed up the two calls to `setAlpha`. I edited the snippet in my comment above, please try it again. Sorry for the confusion!

This is work. Thank you very much.
