### ISSUE TITLE
SWT javadoc bash for 4.27

### ISSUE THREAD

**Issue by elsazac** [eclipse-platform/eclipse.platform.swt#562]
Describe the bug
Run Javadoc bash tool on SWT sources.

**To Reproduce**
A standalone SWT snippet to reproduce the behavior (preferable)

Expected behavior
Javadoc should be consistent in SWT code base for all platforms.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- [ ] All OS
- [ ] Windows
- [ ] Linux
- [x] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

3. JRE/JDK version
 
Version since
 Eclipse or SWT version since when the behavior is seen [e.g. 4.27]

Workaround (or) Additional context
Any known workarounds for the problem?

**Comment by deepika-u** [comment]
We have checked on 1/3/2023 on Mac, Windows. Dont see any changes needed to be checked in.
