### ISSUE TITLE
Copy formatted text adds extra line(s) and format

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.swt#593]
**Describe the bug**
STRG+C a text without linebreaks from an editor
STRG+V into microsoft word or Teams => pastes copied text + one or even two newlines (NOK!)
STRG+V  into notepad++ => pastes only the copied text (OK)
STRG+SHIFT+V into microsoft word or Teams => pastes only the copied text (OK)

It's also not helpfull that the whole format is copied at all since the format depends on the current selection -> the copied text is shown ontop of light blue background, only because it was the selected line. 

**To Reproduce**
copy "main" from "public static void main(String[] args)" and paste it with format:
![image](https://user-images.githubusercontent.com/51790620/225929008-5146d2a0-f2e1-401a-8a8b-7d1c41256a42.png)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [x] Windows
- - [x] Linux
- - [?] macOS 

**Version since**
first recognized with 2022-12

**Workaround**
paste without format (STRG+SHIFT+V)

**Comment by jukzi** [comment]
happens also when all CTRL+C in the key bindings are disabled.

**Comment by iloveeclipse** [comment]
I assume this is the effect of #292 ?

**Comment by jukzi** [comment]
Extra newline for multi-line copy was solved.  Copy a "line fragment" still has issue.

**Comment by drapichrust** [comment]
@jukzi  is it in anyway related to an issue that I see:

using simple text file on plain eclipse for java

I put some text to the clipboard via ctrl + c

I'm creating multi caret selection by using "multi selection down relative to anchor selection" (alt + j in my case) multiple times. Now depending on how many carets I have if I click ctrl + v the pasted text is multiplied by the amount of carets. 2 carets will give me double insertion per caret, 4 will give me 4 per caret (16).

What is weird is that if I make selection first via ctrl + j and then copy text and paste I only get one insertion per caret.
