### ISSUE TITLE
GitHub PR build results always report green

### ISSUE THREAD

**Issue by mbooth101** [eclipse-platform/eclipse.platform.swt#594]
In #591 it was reported that a new failing test was introduced.

However it was not spotted because the Github PR continuous integration always report green _even when a change introduces a new test failure!_

E.g. See this build result: https://github.com/eclipse-platform/eclipse.platform.swt/actions/runs/4366256928/jobs/7636013659?pr=555

You have to read the build logs very closely to spot there was a new MacOS test failure.

Is it possible to have such cases report a "failure" or "unstable" result as Jenkins might do? It would be great to catch these before merge.

**Comment by iloveeclipse** [comment]
Matt, can you push some dummy PR with a trivial change to see if SWT test in question is actually **executed** at all on Mac at github action?

**Comment by laeubi** [comment]
Usually there is a github action that publish the unit test results see:

https://github.com/eclipse-platform/eclipse.platform.swt/actions/workflows/junit.yml

I don't know why this currently do not kick in I can take a look the next days where I already planned to update the jobs for platform repositories.

**Comment by mbooth101** [comment]
You can see it in any recent PR, either the one I linked to above, or this from a couple days ago, for example:

https://github.com/eclipse-platform/eclipse.platform.swt/actions/runs/4414773547/jobs/7736908402?pr=588#step:7:1607

**Comment by iloveeclipse** [comment]
> I can take a look the next days where I already planned to update the jobs for platform repositories.

Thanks.

**Comment by mbooth101** [comment]
For a while the Win32 build was failing frequently, and there are no test results for any of these runs,:

https://github.com/eclipse-platform/eclipse.platform.swt/actions/runs/4368161788
https://github.com/eclipse-platform/eclipse.platform.swt/actions/runs/4369053751
https://github.com/eclipse-platform/eclipse.platform.swt/actions/runs/4368159636

@laeubi so it's maybe it's possible that if one platform fails to build, then it never bothers to collate the test results for the other successful platforms. It looks like this is why I missed the new test failure.

**Comment by laeubi** [comment]
The primary goal should be to fix the build (make test more robust, disable or delete them) otherwise the confidence in these tests will degrade and we will end up in such situation like this where it is only accidentally noticed that the test are not run/reported...

**Comment by laeubi** [comment]
@iloveeclipse @mbooth101 
At least here I see test results published:
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/596#issuecomment-1474809070

**Comment by iloveeclipse** [comment]
> At least here I see test results published:

But Mac build is green, which is not expected.

**Comment by laeubi** [comment]
Actually for current configuration it is expected, as compile + test execution is/was success, the test-results are published as a separate check and are marked as failure.

I'll update the checks to show a delta to master and to fail the coresponding builds if there is a failure, but this won't help if people just ignore failing checks :-\

![grafik](https://user-images.githubusercontent.com/1331477/226101058-fe8d5d5d-b808-4028-91fd-cb11fd20ab56.png)

**Comment by HannesWell** [comment]
I'm not sure if this is really related (I believe it is not), but at least for the Jenkins Pipeline, the github-ckecks-plugin is missing since we moved this repos build to the releng JIPP.
I requested to install it from the infra team, but it didn't get much attention yet:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2546

I can create a PR for JIRO so that the infra team just has to deploy the change, which hopefully does not take that long.

**Comment by mbooth101** [comment]
> Actually for current configuration it is expected, as compile + test execution is/was success, the test-results are published as a separate check and are marked as failure.
> 
> I'll update the checks to show a delta to master and to fail the coresponding builds if there is a failure, but this won't help if people just ignore failing checks :-\

My problem was that there are NO test results shown at all, if one of the platforms fails to build:

![image](https://user-images.githubusercontent.com/597661/226178159-7118c897-dd1a-4764-b004-675419adefac.png)

In this case I checked the build failure, but it was unrelated to my change. Have you changed it to publish the test results in this case?

**Comment by laeubi** [comment]
This should now be fixed as you can see here:
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/599

You get a +1 new passing test compared to master and red x for all builds with failing test, I hope this satisfies the requirements.

**Comment by mbooth101** [comment]
Thanks!
