### ISSUE TITLE
BrowserFunction fails if a string containing a backslash is returned in Webview2

### ISSUE THREAD

**Issue by ChristophKaser** [eclipse-platform/eclipse.platform.swt#605]
**Describe the bug**
A custom BrowserFunction fails on Webview2 if a string containing a backslash is returned

**To Reproduce**
```
import org.eclipse.swt.*;
import org.eclipse.swt.browser.*;
import org.eclipse.swt.layout.*;
import org.eclipse.swt.widgets.*;

public class JSONFail {

	public static void main(String[] args) {
		Display display = new Display();
		Shell shell = new Shell(display);
		shell.setText("JSONFail");
		shell.setLayout(new FillLayout());
		shell.setBounds(10, 10, 600, 400);

		final Browser browser;
		try {
			browser = new Browser(shell, SWT.EDGE);
		} catch (SWTError e) {
			System.out.println("Could not instantiate Browser: " + e.getMessage());
			display.dispose();
			return;
		}
		browser.setText(
				"<input type='button' onclick='try { alert(javaFun()); } catch(e) { alert(e); }' value='Click'>");
		new BrowserFunction(browser, "javaFun") {
			public Object function(Object[] arguments) {
				return "bad\\string";
			}
		};

		shell.open();
		while (!shell.isDisposed()) {
			if (!display.readAndDispatch())
				display.sleep();
		}
		display.dispose();
	}

}
```

**Expected behavior**
After clicking the button, the snippet should produce an alert with the text "bad\string". Instead an error is thrown.
If the Browser implementation is changed to SWT.NONE, it works as expected.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

3. JRE/JDK version
 
**Workaround (or) Additional context**
This is caused by a bug in JSON.stringify, see https://github.com/eclipse-platform/eclipse.platform.swt/pull/604

**Comment by deepika-u** [comment]
I have checked this in below build, it works fine. So it is verified.
Eclipse SDK
Version: 2023-06 (4.28)
Build id: I20230426-1800
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 20+36
Java version: 20
