### ISSUE TITLE
[Cocoa] java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.internal.cocoa.NSWindow.contentView()" because "window" is null

### ISSUE THREAD

**Issue by sratz** [eclipse-platform/eclipse.platform.swt#614]
**Describe the bug**
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=559198

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.internal.cocoa.NSWindow.contentView()" because "window" is null
 at org.eclipse.swt.widgets.Control.calculateVisibleRegion(Control.java:775)
 at org.eclipse.swt.widgets.Control.getVisibleRegion(Control.java:2060)
 at org.eclipse.swt.widgets.Control.isObscured(Control.java:2341)
 at org.eclipse.swt.widgets.Scrollable.scrollClipViewToPoint(Scrollable.java:347)
 at org.eclipse.swt.widgets.Display.windowProc(Display.java:6754)
```

**To Reproduce**
https://bugs.eclipse.org/bugs/show_bug.cgi?id=559198#c0

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [ ] Linux
- - [x] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Catalina/Ventura

4. JRE/JDK version
17
 
**Version since**
4.14

**Workaround (or) Additional context**
According to https://bugs.eclipse.org/bugs/show_bug.cgi?id=559198#c4 the whole `Control.calculateVisibleRegion` might be potentially obsolete.

As a first immediate solution, I propose to add a `null`-check. I will provide a pull request.

**Comment by SyntevoAlex** [comment]
Same as https://github.com/eclipse-platform/eclipse.platform.swt/issues/472 , please continue discussion there
