### ISSUE TITLE
SWT build still requires Java 11

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#626]
Nashorn JavaScript Engine was removed in Java 15, see https://openjdk.org/jeps/372

However, SWT build still uses it in ant file:
See 
- https://github.com/eclipse-platform/eclipse.platform.swt/blob/c26d1ff0248c9191a81e6cd5a94607bf77c4f740/bundles/org.eclipse.swt/buildSWT.xml#L371
- https://github.com/eclipse-platform/eclipse.platform.swt/blob/c26d1ff0248c9191a81e6cd5a94607bf77c4f740/bundles/org.eclipse.swt/buildSWT.xml#L385
- https://github.com/eclipse-platform/eclipse.platform.swt/blob/c26d1ff0248c9191a81e6cd5a94607bf77c4f740/bundles/org.eclipse.swt/buildSWT.xml#L415

This has to be solved if we want to get rid of Java 11 in SWT.

Once that is done, we also can change `Jenkinsfile`

Beside supporting ant execution on 11, Jenkinsfile uses different JDK 11 versions also in other places, see [this comment](https://github.com/eclipse-platform/eclipse.platform.swt/pull/627#issuecomment-1505780265).
and following places:
- https://github.com/eclipse-platform/eclipse.platform.swt/blob/04678a28607971268382a53f4b85c0b176b02add/Jenkinsfile#L143
- https://github.com/eclipse-platform/eclipse.platform.swt/blob/04678a28607971268382a53f4b85c0b176b02add/Jenkinsfile#L146
- https://github.com/eclipse-platform/eclipse.platform.swt/blob/04678a28607971268382a53f4b85c0b176b02add/Jenkinsfile#L148

**Comment by mickaelistria** [comment]
It's possible to use the `java` task instead; but we need to rework things a bit to avoid dereferencing the project in the code, but instead pass the properties we're willing to process. eg
```xml
<project default="blah">
	<target name="blah">
		<property name="tags"><![CDATA[
			a
			b
			c]]></property>
		<echo file="dummyTags.java">
			<![CDATA[
				public class lastTag { public static void main(String... args) {
					var tags = args[args.length - 1].split("\n");
					System.out.println(tags[tags.length - 1].strip());
				}}
			]]>
		</echo>
		<java fork="true" outputproperty="swt_tag" sourcefile="dummyTags.java">
			<arg value="${tags}"/>
		</java>
		<echo>${swt_tag}</echo>
	</target>
</project>
```
For the more complex one that sets multiple properties at once, the `java` block could output a `key=value` dictionary in a property and this property be loaded as properties in a `property` step.

**Comment by HannesWell** [comment]
My goal with #513 is to get rid of ANT as far as reasonable possible, which of course also includes to get rid of the java-script scripts in ANT tasks. For example with https://github.com/eclipse-platform/eclipse.platform.swt/pull/613 one stage was already made ANT and javascript free. But it is a larger task I carry out step by step.

> This has to be solved if we want to get rid of Java 11 in SWT.

Since these ANT/javascript script scripts are only used to perform the SWT natives build this is not correct. As described in https://github.com/eclipse-platform/eclipse.platform.swt/issues/625#issuecomment-1505756638 the `Build` and test stage of the SWT pipeline already uses Java-17 and we could leave the other parts at Java-11 for the moment.

**Comment by HannesWell** [comment]
I have analyzed in depth from which JDKs the headers are used:
- linux.x86_64: `/opt/tools/java/temurin/jdk-11/latest`
- linux.aarch64: `/usr/lib/jvm/java-11-openjdk/`
- linux.ppc64le: `/usr/lib/jvm/java-11-openjdk-11.0.15.0.10-3.el8.ppc64le`
- macosx.aarch64: `/Library/Java/JavaVirtualMachines/temurin-17.jdk`
- macosx.x86_64: `/Library/Java/JavaVirtualMachines/temurin-19.jdk`
- win32.x86_64: `C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot`

The mixture is coming from multiple discrepancies in the SWT-natives builds, which existed in the https://ci.eclipse.org/releng/view/SWT%20Natives jobs.

For Linux it is the expected mixture.

For Windows the environment variable from which the headers are included is name `SWT_JAVA_HOME` and without it defined the build.bat starts auto-searching.
https://github.com/eclipse-platform/eclipse.platform.swt/blob/6912a16abe78c905180908ea4d59218f6519c272/bundles/org.eclipse.swt/Eclipse%20SWT%20PI/win32/library/make_win32.mak#L41
https://github.com/eclipse-platform/eclipse.platform.swt/blob/6912a16abe78c905180908ea4d59218f6519c272/bundles/org.eclipse.swt/Eclipse%20SWT%20PI/win32/library/make_win32.mak#L53

For macos is it is more or less hard-coded to use JDK on the system path (as far as I understand the script):
https://github.com/eclipse-platform/eclipse.platform.swt/blob/6912a16abe78c905180908ea4d59218f6519c272/bundles/org.eclipse.swt/Eclipse%20SWT%20PI/cocoa/library/build.sh#L18-L22

I downloaded the Java-17 JDKs for all of the mentioned platforms from [Adoptium](https://adoptium.net/de/temurin/releases/?version=17) and compared their `include` folder (the one that contains the headers which are interesting for the SWT natives build. The comparison result was that for Java-17 the header files are equal per platform (linux, win, mac) regardless of the architecture. And the only difference between the OSs is a OS-specific subfolder containing the `jni_md.h` and `jawt_md.h` (and for Windows a bridge) with OS-specific content. The headers directly in the include folder are equal for all platforms.

![grafik](https://user-images.githubusercontent.com/44067969/231902015-effdbcd3-8e0e-4530-8f9e-a88ae3ff0b5f.png)


This leads me to the conclusion that we only need one JDK respectively one set of headers per OS.

**Comment by laeubi** [comment]
I have already prototypes a way that is compatible with PDE/Eclipse + Tycho without the use of ANT but it would require
- https://github.com/eclipse-platform/eclipse.platform.swt.binaries/issues/2

So if LFS is too complicated / no progress, one might probably reconsider the submodules as an intermediate solution... as soon as we have a combined repo (using whatever technique) I can try finish my prototype and open a PR... adding JDK headerfiles to the repo seems not a very good solution, even though the *visible* result of a headerfile should not differ between OS there is no guarantee.

**Comment by iloveeclipse** [comment]
> Can this issue be closed? 

No, see bug description / comments.

> AFAIK SWT now requires Java 17.

That's the point of the issue. We require Java 17 for runtime but still need Java 11 for build!

**Comment by HannesWell** [comment]
@iloveeclipse I would like to dedicate this issue only to building the SWT native binaries against JDK-17 headers and libs.
JDK-11 is only necessary for the ant runs to check if a native compilation is necessary and to prepare the resources, so it does not really affect the build. Nevertheless removing the need for a JDK-11 to run the ANT tasks will automatically happen once #513 is resolved and ANT is not necessary anymore to build SWT or at least only used much less in some maven-antrun-plugin executions (and hopefully only with Java-17).

This means that this this issue is completed once #633 is submitted.

Are you fine with that?

**Comment by iloveeclipse** [comment]
> I would like to dedicate this issue only to building the SWT native binaries against JDK-17 headers and libs.

Why? My point is to have one issue that is open as long as we have **any** dependency on Java 11.
You can fix as many aspects as you like (and it is really great that you are working on it), but as a whole build still depends on Java 11.

**Comment by HannesWell** [comment]
> > I would like to dedicate this issue only to building the SWT native binaries against JDK-17 headers and libs.
> 
> Why? My point is to have one issue that is open as long as we have **any** dependency on Java 11. You can fix as many aspects as you like (and it is really great that you are working on it), but as a whole build still depends on Java 11.

Understand. Thinking about it again, #513 probably takes longer to resolve than only getting rid of Java-11 in the build since it covers much more. So we don't have effectively duplicated issues. Lets keep it as it is.

**Comment by HannesWell** [comment]
The build of SWT now doesn't use ANT-scripts anymore, only very few executions of the maven-antrun-plugin are left, but those don't require JavaScript and there is not ANT script left in org.eclipse.swt.
All tasks encoded in the former scripts where either obsolete or have been migrated to Maven, the Jenkins pipeline (which uses Groovy) or to one [JEP 330](https://openjdk.org/jeps/330) single source Java script.
