### ISSUE TITLE
[Mac] GC text foreground color not updated if string length is 1 and transparent background set

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.swt#631]
**Describe the bug**
This bug originates from https://github.com/eclipse/gef-classic/issues/173

Due to a change in `GC#drawText` on Mac introduced in https://github.com/eclipse-platform/eclipse.platform.swt/commit/2a2325b0699615424fc557f8d6db2190dd304048 drawing a single character onto the same `GC` instance with different foreground colors is not drawn correctly.

This affects `Draw2d` figures that draw the same single character with different foreground colors because Draw2d uses the same `GC` instance for all figures in a canvas.

**To Reproduce**
Run  this snippet:

```java
import org.eclipse.swt.SWT;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class SWTSnippet {

    public static void main(String[] args) {
        Display display = new Display();
        Shell shell = new Shell(display);
        shell.setLayout(new FillLayout());
        shell.setSize(200, 180);

        String text = "A";
        Color red = new Color(255, 0, 0);
        Color blue = new Color(0, 0, 255); 

        Composite comp = new Composite(shell, SWT.None);
        
        comp.addPaintListener(e -> {
            e.gc.setForeground(red);
            e.gc.drawText(text, 0, 0, true);
            
            e.gc.setForeground(blue);
            e.gc.drawText(text, 20, 0, true);
        });
        
        shell.open();

        while(!shell.isDisposed()) {
            if(!display.readAndDispatch()) {
                display.sleep();
            }
        }
    }
}
```

**Expected behavior**
The first character should be red and the second one blue. Because of the caching in `GC` the foreground color is not updated.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [ ] Linux
- - [x] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Mac

3. JRE/JDK version
Java 17
 
**Version since**
Since https://github.com/eclipse-platform/eclipse.platform.swt/commit/2a2325b0699615424fc557f8d6db2190dd304048

**Comment by Phillipus** [comment]
Alternatively, the current foreground color could be used as part of the caching key string:

```java
private GCTextData getTextData(String string) {
	GCTextData data = (GCTextData) textDataCache.get(string + getForeground().toString());
	if (data == null) {
		NSAttributedString attribStr = createString(string, 0, true);
		data = new GCTextData(attribStr);
		attribStr.release();
		textDataCache.put(string + getForeground().toString(), data);
	}
	return data;
}
```

**Comment by Phillipus** [comment]
I suppose the question is whether this caching code does really add any optimisation? With reference to https://github.com/eclipse-platform/eclipse.platform.swt/commit/2a2325b0699615424fc557f8d6db2190dd304048 and https://bugs.eclipse.org/bugs/show_bug.cgi?id=366471 I can only see it being used to paint single character line numbers in a text editor. If it's not bringing anything to the party perhaps we should remove it? If it is optimising could someone say how? And if so, perhaps the foreground color of the text could be considered when caching it?

@SyntevoAlex What do you think?

**Comment by Phillipus** [comment]
So it might be something like this:

```java
private GCTextData getTextData(String string) {
    String key = string + data.alpha + data.fg + data.font;
	GCTextData gcTextData = (GCTextData) textDataCache.get(key);
	if (gcTextData == null) {
		NSAttributedString attribStr = createString(string, 0, true);
		gcTextData = new GCTextData(attribStr);
		attribStr.release();
		textDataCache.put(key, gcTextData);
	}
	return gcTextData;
}
```

**Comment by SyntevoAlex** [comment]
Sorry for being late to the discussion.

macOS is notorious for its terribly slow text painting, see Bug 574618.

I tested using this code:
```
Button button = new Button(shell, 0);
button.setText("Test");
button.addListener(SWT.Selection, event -> {
	final Image image = new Image(display, 200, 200);
	final GC gc = new GC(image);

	final int numIters = 1000;

	for (int iTest = 0; iTest < 100; iTest++) {
		{
			final long time1 = System.nanoTime();
			for (int i = 0; i < numIters; i++) {
				gc.drawText("0", 0, 0, SWT.DRAW_TRANSPARENT);
			}
			final long time2 = System.nanoTime();

			final double elapsedSec = (time2 - time1) / 1000000000.0;
			final double itersPerSec = numIters / elapsedSec;
			System.out.format("0:  Time=%.2fsec Iters/sec=%.2f%n", elapsedSec, itersPerSec);
		}

		{
			final long time1 = System.nanoTime();
			for (int i = 0; i < numIters; i++) {
				gc.drawText("00", 0, 0, SWT.DRAW_TRANSPARENT);
			}
			final long time2 = System.nanoTime();

			final double elapsedSec = (time2 - time1) / 1000000000.0;
			final double itersPerSec = numIters / elapsedSec;
			System.out.format("00: Time=%.2fsec Iters/sec=%.2f%n", elapsedSec, itersPerSec);
		}
	}

	gc.dispose();
	image.dispose();
});
```

Results:
```
Before patch - 0=31369/sec, 00=5137/sec
After  patch - 0= 5083/sec, 00=4712/sec
```

So it's 6x slower now.
The initial patch (now reverted) was talking about code that renders spaces.
We have such code too in or product - it renders non-printable characters in StyledText.

I think that removing the optimization isn't a very good idea.

**Comment by Phillipus** [comment]
@SyntevoAlex OK. How about reverting the revert and using a different cache as in https://github.com/eclipse-platform/eclipse.platform.swt/issues/631#issuecomment-1521876753 ?

**Comment by Phillipus** [comment]
PR #648

**Comment by elsazac** [comment]
Verified on Mac OS  Ventura 13.3.1 aarch 64.

Build Information is listed below:
Eclipse SDK
Version: 2023-06 (4.28)
Build id: I20230515-1800
OS: Mac OS X, v.13.3.1, aarch64 / cocoa
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.6+10
Java version: 17.0.6
