### ISSUE TITLE
Add Codeowners file

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.swt#66]
I just learned about this Github feature (https://tech.people-doc.com/using-github-codeowners-file.html). I think it would help a lot if we set it up for SWT per port. My proposal would be:
* GTK - **/gtk/* - @sravanlakkimsetti @akurtakov 
* Cocoa - **/cocoa/* - @lshanmug someoneelse?
* Win32 - **/win32/* - @niraj-modi someoneelse?
What do you think?

**Comment by niraj-modi** [comment]
+1 Sounds good to me, and if the changes are in common files:
- */common - all of us gets added.

**Comment by akurtakov** [comment]
I think we need 2 persons per WS as one can be on vacation, very bussy right now and etc. So please propose second persons for mac/win.

**Comment by akurtakov** [comment]
So no second person for mac/win?

**Comment by iloveeclipse** [comment]
I could be backup for Windows/GTK. No one in my team has a Mac.

**Comment by akurtakov** [comment]
Thanks @iloveeclipse so I'll act accordingly and let Mac person be added later.

**Comment by akurtakov** [comment]
Would someone not listed in codeowners open a PR so we can verify it works?

**Comment by trancexpress** [comment]
> @trancexpress : could you please? Just some garbage change.

https://github.com/eclipse-platform/eclipse.platform.swt/pull/124

**Comment by iloveeclipse** [comment]
I don't see any reviewer added.

**Comment by akurtakov** [comment]
Neither do I. Thanks for trying I'll keep experimenting in my fork.

**Comment by akurtakov** [comment]
I was auto added as reviewer in https://github.com/akurtakov/eclipse.platform.swt/pull/10 so I consider this one done.
