### ISSUE TITLE
make highlighting of CTabFolder configurable for RCP products

### ISSUE THREAD

**Issue by phermsdorf** [eclipse-platform/eclipse.platform.swt#664]
**Is your feature request related to a problem? Please describe.**
With #183 a highlighting of the active Tab Folder was introduced.
In our RCP product we use a global toolbar with a custom(configurable) background color used for branding the product for customers. 
With that change in place the blue highlight color of the active Editor now looks a bit odd with some color configurations as toolbar and highlight color are very close to each other.

**Describe the solution you'd like**
Please introduce a kind of product configuration to 
- disable this feature at all and (optionally)
- define the color used for highlighting at runtime (then it could be part of the branding)

Maybe via System Properties? 

**Describe alternatives you've considered**
since the Editor/CTabFolder creation happens in platform i've found no way to disable or customize it via setSelectionBarThickness or other means

Thanks for looking at the issue.
Bye Peter

**Comment by mickaelistria** [comment]
You can already configure a CTabFolderRenderer in your RCP product, either with `CTabFolder.setRenderer()` or defining/using a different CSS style for your application, where you can IIRC configure the color and thickness of the highlight, among many others (or even also setting a particular tabRenderer).
I believe the themes cover your needs very well and don't think we plan to offer lower level of granularity for customization here.

**Comment by mickaelistria** [comment]
I think there is already some property available for that. So my proposal would be that you write a CSS file that configures the renderer as you wish.
