### ISSUE TITLE
Shell.test_Issue450_NoShellActivateOnSetFocus fails on Mac

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#727]
`Test_org_eclipse_swt_widgets_Shell.test_Issue450_NoShellActivateOnSetFocus` fails on Mac after merge of https://github.com/eclipse-platform/eclipse.platform.swt/pull/553

- https://download.eclipse.org/eclipse/downloads/drops4/I20230704-1800/testResults.php
- https://download.eclipse.org/eclipse/downloads/drops4/I20230704-1800/testresults/html/org.eclipse.swt.tests_ep429I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
- https://download.eclipse.org/eclipse/downloads/drops4/I20230704-1800/testresults/html/org.eclipse.swt.tests_ep429I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

```
Shell did not become active

java.lang.AssertionError: Shell did not become active
at org.junit.Assert.fail(Assert.java:89)
at org.eclipse.swt.tests.junit.SwtTestUtil.waitShellActivate(SwtTestUtil.java:418)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_widgets_Shell.test_Issue450_NoShellActivateOnSetFocus(Test_org_eclipse_swt_widgets_Shell.java:961)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by SyntevoAlex** [comment]
I added another workaround, let's wait and see how it works.

**Comment by SyntevoAlex** [comment]
Since this PR was merged, the problem seems to be fixed: no more `test_Issue450_NoShellActivateOnSetFocus` failures were seen.
