### ISSUE TITLE
Enable AuthenticationListener for Browser-Widget under Windows/Edge

### ISSUE THREAD

**Issue by Rainer7000** [eclipse-platform/eclipse.platform.swt#730]
As long as the Default-Browser for Windows was IE the AuthenticationListener of the Browser-Widget received the BasicAuthentication-Requests of a Website and could enter Username and Password in the background of an embedded Browser.

According to the Limitation-List of Eclipse (https://www.eclipse.org/swt/faq.php#edgelimitations) the Feature is not working
for Microsoft Edge because of missing upstream API.
It seams the Microsoft has implemented the API for quite some time now, according to these Articles:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/120
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/basic-authentication?tabs=csharp

Would it be possible make the AuthenticationListener work for Edge-Browser-Widgets by implementing the Basic-Authentication 
process of the current WebView2 ?

**Comment by HeikoKlare** [comment]
Probably the extension 10 of the `ICoreWebView2` is the right thing to look at for this:
https://learn.microsoft.com/de-de/microsoft-edge/webview2/reference/win32/icorewebview2_10

**Comment by sratz** [comment]
> Probably the extension 10 of the `ICoreWebView2` is the right thing to look at for this:
> https://learn.microsoft.com/de-de/microsoft-edge/webview2/reference/win32/icorewebview2_10

This looks compatible and fairly easy to implement.

I can take this one on.
