### ISSUE TITLE
Hebrew Text are not properly displayed on UI

### ISSUE THREAD

**Issue by rushi1698** [eclipse-platform/eclipse.platform.swt#753]
While opening a file that contains valid Hebrew text on the Eclipse UI from local storage, I noticed it was not viewing the Hebrew text properly; it was flipping the words.

See the attached screenshot. First, I tried opening the same file in Notepad, and it displayed the Hebrew text correctly, but in Eclipse, it was showing in reverse. It is only happens with Hebrew in my case.

Currently, I'm using Eclipse Committers

**Version**: 2022-03 (4.23.0)
**Build id**: 20220310-1457

Bydefault encoding is set to UTF-8.

**see attached sample file**: HebrewSample.txt
**Attached Screenshot** : how text display on notepad and eclipse IDE.

[HebrewSample.txt](https://github.com/eclipse-platform/eclipse.platform.ui/files/12122912/HebrewSample.txt)
<img width="475" alt="Hebrew_Text_Diplay_On_Notepad" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/84301692/4c584dd7-6fec-4438-955c-7efc3e97eb1b">
<img width="460" alt="Hebrew_Text_Display_on_EclipseIDE" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/84301692/ca6a1c23-b536-41f8-9252-e24ffde05ea6">

**Comment by BeckerWdf** [comment]
<img width="472" alt="image" src="https://github.com/eclipse-platform/eclipse.platform.swt/assets/28338612/b38a0720-0773-4e37-a461-8a0348d28d66">


This is on macOS

**Comment by Phillipus** [comment]
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/37 and try latest Eclipse.

**Comment by merks** [comment]
It looks correct for me on Windows 10, Eclipse SDK 4.29:

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/208716/a25aa55e-3d75-45df-82ed-a0511c7d4458)

**Comment by Phillipus** [comment]
Yeah, it was fixed in 4.24.

**Comment by rushi1698** [comment]
Thanks for the help :)
