### ISSUE TITLE
[macOS aarch64] Running SWT Snippets - "java.lang.UnsatisfiedLinkError: Could not load SWT library"

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.swt#774]
macOS 12, 13 or 14 aarch64
Mac Mini M1
Eclipse 4.28 or 4.29

This happens when debugging SWT Snippets in the Eclipse workbench only on macOS aarch64 (macOS Intel is OK).

1. Ensure that your `<userhome>/.swt` directory is empty or deleted in order to start fresh
2. Import the `org.eclipse.swt` and `org.eclipse.swt.cocoa.macosx.aarch64` projects into your workspace so that the latest SWT code and binaries are used
3. Launch an SWT Snippet

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-cocoa-4962r3 in java.library.path: /Users/phillipus/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt-cocoa in java.library.path: /Users/phillipus/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt in java.library.path: /Users/phillipus/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	Can't load library: /Users/phillipus/.swt/lib/macosx/aarch64/libswt-cocoa-4962r3.jnilib
	Can't load library: /Users/phillipus/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib
	Can't load library: /Users/phillipus/.swt/lib/macosx/aarch64/libswt.jnilib

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:110)
	at ImageTestWithPattern.main(ImageTestWithPattern.java:10)
```

Note that an empty `<userhome>/.swt/lib/macosx/aarch64` directory is created.

**Workaround:**

Manually copy all `*.jnilib` files from the `org.eclipse.swt.cocoa.macosx.aarch64` project to the `<userhome>/.swt/lib/macosx/aarch64` directory and start again.

**Comment by jukzi** [comment]
can you provide a fix?

**Comment by Phillipus** [comment]
> can you provide a fix?

Can anyone help to identify where the problem lies?

**Comment by akurtakov** [comment]
Problem most likely comes from https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/.classpath_cocoa#L13 . Does it work if you change it to aarch64 one?

**Comment by Phillipus** [comment]
> Does it work if you change it to aarch64 one?

Bingo! Thank-you.

I can submit a PR to rename current `.classpath_cocoa` to `.classpath_cocoa_x86_64` and a new one named `.classpath_cocoa_aarch64` and update `Readme.macOS.md` to mention this. Would that be OK?

**Comment by Phillipus** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/pull/776

**Comment by merks** [comment]
I'll have to have a look at the Oomph setup too then, because this renaming is also done there automatically...

Doesn't Linux suffer the same problem where x86_64 is assumed in /org.eclipse.swt/.classpath_gtk?
```
	<classpathentry kind="src" path="Eclipse SWT PI/gtk">
		<attributes>
			<attribute name="org.eclipse.jdt.launching.CLASSPATH_ATTR_LIBRARY_PATH_ENTRY" value="org.eclipse.swt.gtk.linux.x86_64"/>
		</attributes>
	</classpathentry>
```
And if we ever supported aarch64 for win32, it would also have that problem, I suppose.

**Comment by akurtakov** [comment]
Linux suffers from same problem but so far no one seems to develop on aarch64 or ppc64le thus there is no need for the .classpatch_gtk_[ppc64le|aarch64].

**Comment by Phillipus** [comment]
I suppose another way to do it would be to edit the existing `.classpath_cocoa` file like this:

```xml
    <classpathentry kind="src" path="Eclipse SWT PI/cocoa">
        <attributes>
            <!-- Use following line on macOS Silicon -->
            <!-- attribute value="org.eclipse.swt.cocoa.macosx.aarch64" name="org.eclipse.jdt.launching.CLASSPATH_ATTR_LIBRARY_PATH_ENTRY"/ -->
            <attribute value="org.eclipse.swt.cocoa.macosx.x86_64" name="org.eclipse.jdt.launching.CLASSPATH_ATTR_LIBRARY_PATH_ENTRY"/>
        </attributes>
    </classpathentry>
```

**Comment by merks** [comment]
I’m okay with your original proposal. It can be automated without much extra effort.

**Comment by cdietrich** [comment]
@merks is there already an oomph fix for this?

**Comment by merks** [comment]
No, I've been swamped with getting updates into Orbit, especially a new version of Ant, and then getting the Platform updated to those updates.  But I have some time today to follow up on this issue.

I wonder though if we need more copies of the files.  One could have instructions for editing the attribute value.  If we going to have  more copies, I would expect one copy for each supported platform combination...

**Comment by merks** [comment]
The task currently specifies this as the source URL
```
${github.clone.platform.swt.location|uri}/bundles/org.eclipse.swt/.classpath_${osgi.ws}
```
It would need to be this, but only for mac:
```
${github.clone.platform.swt.location|uri}/bundles/org.eclipse.swt/.classpath_${osgi.ws}_${osgi.arch}
```
Anyway, it's probably less work to "just do it like this", even if that doesn't feel quite properly general to me....

**Comment by merks** [comment]
@cdietrich 

All the changes should be available now.

**Comment by cdietrich** [comment]
will test once this in available in 2023-12

**Comment by cdietrich** [comment]
testing with current i-build and launch as junit plugin test still gives

```
java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	/Users/dietrich/xtext-main/runtime-EclipseXtextx/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/org.eclipse.osgi/335/0/.cp/libswt-cocoa-4963r3.jnilib: dlopen(/Users/dietrich/xtext-main/runtime-EclipseXtextx/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/org.eclipse.osgi/335/0/.cp/libswt-cocoa-4963r3.jnilib, 0x0001): tried: '/Users/dietrich/xtext-main/runtime-EclipseXtextx/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/org.eclipse.osgi/335/0/.cp/libswt-cocoa-4963r3.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/dietrich/xtext-main/runtime-EclipseXtextx/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/org.eclipse.osgi/335/0/.cp/libswt-cocoa-4963r3.jnilib' (no such file), '/Users/dietrich/xtext-main/runtime-EclipseXtextx/.metadata/.plugins/org.eclipse.pde.core/Eclipse Application/org.eclipse.osgi/335/0/.cp/libswt-cocoa-4963r3.jnilib' (mach-o file, but is an incompatible archit
	no swt-cocoa in java.library.path: /Users/dietrich/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	no swt in java.library.path: /Users/dietrich/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
	/Users/dietrich/.swt/lib/macosx/aarch64/libswt-cocoa-4963r3.jnilib: dlopen(/Users/dietrich/.swt/lib/macosx/aarch64/libswt-cocoa-4963r3.jnilib, 0x0001): tried: '/Users/dietrich/.swt/lib/macosx/aarch64/libswt-cocoa-4963r3.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/dietrich/.swt/lib/macosx/aarch64/libswt-cocoa-4963r3.jnilib' (no such file), '/Users/dietrich/.swt/lib/macosx/aarch64/libswt-cocoa-4963r3.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
	Can't load library: /Users/dietrich/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib
	Can't load library: /Users/dietrich/.swt/lib/macosx/aarch64/libswt.jnilib
	/Users/dietrich/.swt/lib/macosx/aarch64/libswt-cocoa-4963r3.jnilib: dlopen(/Users/dietrich/.swt/lib/macosx/aarch64/libswt-cocoa-4963r3.jnilib, 0x0001): tried: '/Users/dietrich/.swt/lib/macosx/aarch64/libswt-cocoa-4963r3.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/dietrich/.swt/lib/macosx/aarch64/libswt-cocoa-4963r3.jnilib' (no such file), '/Users/dietrich/.swt/lib/macosx/aarch64/libswt-cocoa-4963r3.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:110)
	at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:727)
	at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:183)
	at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:182)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:125)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
```
is this a separate issue?

**Comment by merks** [comment]
All the changes look to me to be purely development time source changes.   So I don't really know what you are testing exactly...

**Comment by Phillipus** [comment]
The error message there says "have 'x86_64', need 'arm64'" Is it because the classpath file is named `.classpath_cocoa_aarch64` instead of `.classpath_cocoa_arm64`?

**Comment by cdietrich** [comment]
the question is: where is this coming from? where do i need to look?

**Comment by cdietrich** [comment]
seems to be related to the jvm used. when i use the justj one it seems to work.

**Comment by bharathkalyans** [comment]
* Small doubt, we cant run the Windows built JAR on macOS right? Because I am unable to do so! 🥲

**Comment by merks** [comment]
Have you used the Oomph setup?  There have been significant changes in the past days where the SWT binaries are located, so I don't know what state you are in...

**Comment by bharathkalyans** [comment]
nope

**Comment by merks** [comment]
So then we'd need to know what you've manually done.  Have you done pull to update to the lastest?  Probably you need to copy the .classpath file again manually...

**Comment by bharathkalyans** [comment]
sure, will definitely try it.

**Comment by BigGeF** [comment]
Here’s the code I attempted, aiming to modify the title of the window by adding the word "test" and to print "--------------------Test" in the console:

its for quickSearchUi
public QuickSearchDialog(IWorkbenchWindow window) {
    super(window.getShell());
    this.window = window;
    setShellStyle(SWT.CLOSE | SWT.MODELESS | SWT.BORDER | SWT.TITLE | SWT.RESIZE);
    setBlockOnOpen(false);
    this.setTitle(Messages.QuickSearchDialog_title + "test"); //$NON-NLS-1$
    System.out.println("--------------------Test"); //$NON-NLS-1$
。。。。
Unfortunately, this attempt failed. The TA suggested that I try debugging to locate the issue, but we encountered another problem related to running SWT on macOS aarch64:

"[macOS aarch64] Running SWT Snippets - java.lang.UnsatisfiedLinkError: Could not load SWT library #774"

GitHub issue link: Issue #774

We attempted the solutions suggested in this issue but were unable to find the .classpath_cocoa file for modification. The TA recommended that I run tests and then pass the code to teammates on Windows for further testing.@HannesWell and @opcoach

**Comment by grissinibread** [comment]
Hello!

I'm still currently having this issue. I have tried the workarounds suggested in this post with no luck. To be more specific, I have:
- Attempted to reinstall eclipse and SWT from scratch
- Manually copied all ```*.jnilib``` files from the ```org.eclipse.swt.cocoa.macosx.aarch64``` project to the ```<userhome>/.swt/lib/macosx/aarch64 directory```.
- Changed the value in ```.classpath_cocoa```.
```
<classpathentry kind="src" path="Eclipse SWT PI/cocoa">
     <attributes>
          <!-- On macOS Silicon change value to "org.eclipse.swt.cocoa.macosx.aarch64" -->
          <attribute value="org.eclipse.swt.cocoa.macosx.x86_64" name="org.eclipse.jdt.launching.CLASSPATH_ATTR_LIBRARY_PATH_ENTRY"/>
      </attributes>
</classpathentry>
```

Neither of these methods have seemed to fix the problem, they have at times broken it further :)

This is my current error message, I'm not sure if it's identical or different in any way:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
/Users/alejandronavarro/eclipse-swt/git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/libswt-cocoa-4970r2.jnilib: dlopen(/Users/alejandronavarro/eclipse-swt/git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/libswt-cocoa-4970r2.jnilib, 0x0001): tried: '/Users/alejandronavarro/eclipse-swt/git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/libswt-cocoa-4970r2.jnilib' (slice is not valid mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/alejandronavarro/eclipse-swt/git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/libswt-cocoa-4970r2.jnilib' (no such file), '/Users/alejandronavarro/eclipse-swt/git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/libswt-cocoa-4970r2.jnilib' (slice is not valid mach-o file)
no swt-cocoa in java.library.path: /Users/alejandronavarro/eclipse-swt/git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64
no swt in java.library.path: /Users/alejandronavarro/eclipse-swt/git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64
/Users/alejandronavarro/.swt/lib/macosx/aarch64/libswt-cocoa-4970r2.jnilib: dlopen(/Users/alejandronavarro/.swt/lib/macosx/aarch64/libswt-cocoa-4970r2.jnilib, 0x0001): tried: '/Users/alejandronavarro/.swt/lib/macosx/aarch64/libswt-cocoa-4970r2.jnilib' (slice is not valid mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/alejandronavarro/.swt/lib/macosx/aarch64/libswt-cocoa-4970r2.jnilib' (no such file), '/Users/alejandronavarro/.swt/lib/macosx/aarch64/libswt-cocoa-4970r2.jnilib' (slice is not valid mach-o file)
Can't load library: /Users/alejandronavarro/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib	Can't load library: /Users/alejandronavarro/.swt/lib/macosx/aarch64/libswt.jnilib
/Users/alejandronavarro/.swt/lib/macosx/aarch64/libswt-cocoa-4970r2.jnilib: dlopen(/Users/alejandronavarro/.swt/lib/macosx/aarch64/libswt-cocoa-4970r2.jnilib, 0x0001): tried: '/Users/alejandronavarro/.swt/lib/macosx/aarch64/libswt-cocoa-4970r2.jnilib' (slice is not valid mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/alejandronavarro/.swt/lib/macosx/aarch64/libswt-cocoa-4970r2.jnilib' (no such file), '/Users/alejandronavarro/.swt/lib/macosx/aarch64/libswt-cocoa-4970r2.jnilib' (slice is not valid mach-o file)

at org.eclipse.swt.internal.Library.loadLibrary(Library.java:345)
at org.eclipse.swt.internal.Library.loadLibrary(Library.java:254)
at org.eclipse.swt.internal.C.<clinit>(C.java:20)
at org.eclipse.swt.widgets.Display.<clinit>(Display.java:110)
at org.eclipse.swt.examples.helloworld.HelloWorld1.main(HelloWorld1.java:26)
```

I'm not sure if this extra info is of any help but I am attempting to run this on a laptop with an M4 chip. Any and all help would be appreciated, thank you!

**Comment by merks** [comment]
Have you tried to use the setup?

https://github.com/eclipse-platform/eclipse.platform.swt?tab=readme-ov-file#contributing-to-swt

**Comment by grissinibread** [comment]
I see now, I did use that setup, but I realized I didn't download the correct version of the eclipse installer through that link. Thank you very much @merks , fixed my issue immediately!
