### ISSUE TITLE
Horizontal scroll bars are getting added unnecessarily.

### ISSUE THREAD

**Issue by elsazac** [eclipse-platform/eclipse.platform.swt#777]
**Describe the bug**

Unnecessary horizontal scroll bars are getting added for default spacing.width value.
See the comment https://github.com/eclipse-platform/eclipse.platform.swt/issues/662#issuecomment-1684887859

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [ ] Linux
- - [x] macOS

**Comment by lshanmug** [comment]
Caused by https://github.com/eclipse-platform/eclipse.platform.swt/pull/760

**Comment by lshanmug** [comment]
Fixed by https://github.com/eclipse-platform/eclipse.platform.swt/pull/775
