### ISSUE TITLE
[macOS Sonoma] Eclipse, SWT and RCP apps main menu app name is "NewApplication"

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.swt#779]
**Describe the bug**
Instead of displaying the app's name in the main menu bar such as "Eclipse", "SmartGit" or "Archi" the name "NewApplication" is displayed instead.

**To Reproduce**
Launch Eclipse or an RCP/SWT application and look at the main menu bar.

**Expected behavior**
Should show the application's name.

**Screenshots**
<img width="333" alt="Screenshot 2023-08-22 at 20 35 31" src="https://github.com/eclipse-platform/eclipse.platform.swt/assets/600504/dd3649ea-fc79-4362-ac9d-3da63c38f7a0">

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [ ] Linux
- - [x] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
macOS Sonoma 14
Mac Mini M1
 
3. JRE/JDK version
Temurin 17

**Comment by Phillipus** [comment]
I still can't figure this one out. Eclipse and RCP/SWT apps (SmartGit, Archi, XMind 8) all display "NewApplication" in the main menu bar, but launching a child Eclipse or an RCP app from Eclipse displays the correct app name.

**Comment by Phillipus** [comment]
As an experiment I changed the language on my Mac to French from English (UK). The application menus then showed correctly. Perhaps there is something going on in `Display#applicationWillFinishLaunching`:

https://github.com/eclipse-platform/eclipse.platform.swt/blob/c370479f46b20fb18b8708a0e6e7a4a7607720a1/bundles/org.eclipse.swt/Eclipse%20SWT/cocoa/org/eclipse/swt/widgets/Display.java#L5704-L5742

**Comment by Phillipus** [comment]
It turns out that we also need to set the submenu name to the application name just after line 5750. See PR https://github.com/eclipse-platform/eclipse.platform.swt/pull/807

**Comment by tmssngr** [comment]
This bug is also valid with the latest release version of macOS 14. :(

**Comment by Phillipus** [comment]
Closed with fix in https://github.com/eclipse-platform/eclipse.platform.swt/pull/807

**Comment by Phillipus** [comment]
It turns out that macOS Sonoma 14.1 (23B73) fixes the underlying issue. The patch is not needed, but there are no side-effects to keeping it and, who knows, the issue might re-appear in a future version of macOS.
