### ISSUE TITLE
GC draws at faulty positions when applying a rotating transformation

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform.swt#788]
### Describe the bug
The `GC` class provides functionality to apply a transformation (translation, scaling, rotation) to the graphics canvas.
This functionality is broken when applying rotations to the GC, leading to
- completely lost draw operations (e.g. with 45° rotation)
- off-by-one errors in positions
- off-by-one errors in lines widths

It particularly occurs when drawing lines of od line width (including the default width of 0), which also includes lines that are supposed to have an off line width but are considered as even because of rounding errors during calculation.

There are also minor issues with applying a line width even if no transformation is applied in case non-horizontal/-vertical lines are drawn: they are drawn longer than they should be.

### To Reproduce
I have provided a PR containing `Snippet381` that allows to simulate the behavior of different transformations applied to a GC: #787
It allows to simulate different transformations of a GC to which the following pattern of lines is drawn. It also marks the "anchor point", i.e., the pixel representing (0,0), as a reference point in red.
![Default](https://github.com/eclipse-platform/eclipse.platform.swt/assets/755472/a25043c3-205b-4f90-b9f4-0fead7509202)

A large amount of issues with the functionality can occur. Some examples are as follows and can be reproduced with the given settings in the snippet:
1. Applying a transformation with a rotation of 45° to lines with line width 0 results in nothing being drawn (Line Width: 0, Rotation: 45).
![45](https://github.com/eclipse-platform/eclipse.platform.swt/assets/755472/0363df97-2cb0-44af-b90a-d8fb3bc5b3fe)
2. Applying a transformation with a rotation of 90° to lines with line width 1 results in off-by-one errors (Line Width: 1, Rotation: 90).
![90](https://github.com/eclipse-platform/eclipse.platform.swt/assets/755472/35f466db-a70b-4e0d-afda-44223952ba72)
3. Applying a transformation with a rotation of 360° to lines with line width 1 results in off-by-one errors (Line Width: 1, Rotation: 360).
![360](https://github.com/eclipse-platform/eclipse.platform.swt/assets/755472/4618d1cc-ef6a-453a-95ee-cbfd04ce8897)
4. Applying a transformation with a rotation of 90° to lines with line width 4 and 5 results in diagonal lines of faulty width (Line Width: 4/5, Rotation: 90)
![Width 4 + 90](https://github.com/eclipse-platform/eclipse.platform.swt/assets/755472/c70c2657-f330-4af1-8307-42640ce68f32)
![Width 5 + 90](https://github.com/eclipse-platform/eclipse.platform.swt/assets/755472/e3103493-9991-451d-b650-5498e809d352)
5. Applying no transformation to lines with line width 5 results in diagonal lines being printed too long (Line Width: 5)
![diagonal_too_long](https://github.com/eclipse-platform/eclipse.platform.swt/assets/755472/c872636a-8b4a-4350-8fcb-3f21f2f5b3d3)

### Expected behavior
When applying rotations to a GC, draw operations shall lead to proper results. This particularly means that:
1. 45° rotations of the GC are handled properly
2. Other rotations do not lead to off-by-one errors in positions and line widths. E.g., drawing something with 90° rotation should lead to the same result as without rotation but only rotated by 90°.

### Bug cause
The cause of the issue is rooted in the way SWT handles coordinates. My interpretation of what I have seen so far is as follows. SWT uses a continuous coordinate system and applies it to the discrete pixel raster. I.e., the coordinate (0,0) represents the upper left edge of the "first" pixel. The "real" coordinate of that pixel is (0.5,0.5). SWT applies different interpretations of coordinates depending on the current line width. With an even line width, such as 2, coordinates are taken as they are. For example, a horizontal line starting at (1,1) will stretch the pixel row above and below y-coordinate 1. With an odd line width, such as 1, coordinates are virtually moved by (0.5, 0.5), so that a horizontal line starting at (1,1) will "virtually" start at (1.5, 1.5), such that it stretched the row below y-coordinate 1.
![Line Widths](https://github.com/eclipse-platform/eclipse.platform.swt/assets/755472/9ef1119e-2960-4666-ae70-adae788387a3)

This offset of 0.5 applies to the space to which the user applies draw operations. However, it is realized by applying an offset to the GC's drawing pane before applying some draw operations, such as drawing a line (see, e.g., [here](https://github.com/eclipse-platform/eclipse.platform.swt/blob/4daf005a457fb50b929719cb5b3616e55cc2e5c4/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/graphics/GC.java#L1655)). When a transformation is applied to the GC, the offset has to be transformed from the "user space" to the "GC drawing space". This is done by an according offset calculation in `checkGC`:
https://github.com/eclipse-platform/eclipse.platform.swt/blob/4daf005a457fb50b929719cb5b3616e55cc2e5c4/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/graphics/GC.java#L326-L345
The current offset calculation only works properly when applied to translate and scale operations, but not when applied to rotate operation. For example, a 45° rotation results in a calculated scaling value of 0, which results in an offset of `infinity`, so that nothing is drawn anymore.

### Additional Data

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [x] All OS
- - [ ] Windows
- - [ ] Linux
- - [ ] macOS 

I have seens the behavior on Windows, but since the GC implementation for the offset calculation is the same on all system, I expect the issue to exist on all systems. However, it would be interesting if someone using MacOS or Linux could use the provided snippet to see if the same issues exist.

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Windows 11

3. JRE/JDK version
JDK 17
 
**Version since**
At least since 4.15, but the code exists in its current state for more than 15 years.

**Comment by iloveeclipse** [comment]
Caused regression on Mac, see https://github.com/eclipse-platform/eclipse.platform.swt/issues/1067

**Comment by iloveeclipse** [comment]
Fix was reverted with https://github.com/eclipse-platform/eclipse.platform.swt/pull/1068, reopening.

**Comment by HeikoKlare** [comment]
Short note: I will improve the fix and re-propose it. As mentioned by @Phillipus [in this comment](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1067#issuecomment-1967068675), [this issue](https://github.com/eclipse-platform/eclipse.platform.swt/issues/304) may be related.
Thanks everyone for finding the regression in the original fix and for reverting it.
