### ISSUE TITLE
SWT cocoa NSImage error

### ISSUE THREAD

**Issue by mogilka** [eclipse-platform/eclipse.platform.swt#794]
**Describe the bug**
I have a Java project when I use pure SWT and Jface (no PDE). I work with the project under MacOS and Ubuntu, synchronizing it via Git. I have no error under Linux while running my project. But it occures under MacOS Catalina in 2 places related to TabFolder:

1. The TabFolder code:

```
folder = new TabFolder(grCosmogram, SWT.BORDER);
..
folder.pack(); //error occures
```

The TabFolder error:

`java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.internal.cocoa.NSImage.size()" because "this.image.handle" is null at org.eclipse.swt.widgets.Button.cellSizeForBounds(Button.java:153) at org.eclipse.swt.widgets.Display.windowProc(Display.java:6580) at org.eclipse.swt.internal.cocoa.OS.objc_msgSend_stret(Native Method) at org.eclipse.swt.internal.cocoa.NSCell.cellSize(NSCell.java:37) at org.eclipse.swt.widgets.Button.computeSize(Button.java:224) at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493) at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225) at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:168) at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:232) at org.eclipse.swt.widgets.TabFolder.minimumSize(TabFolder.java:447) at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:238) at org.eclipse.swt.widgets.TabFolder.computeSize(TabFolder.java:143) at org.eclipse.swt.widgets.Control.pack(Control.java:2799) at org.eclipse.swt.widgets.Control.pack(Control.java:2773) `

2. The CTabFolder code:

```
ToolBar toolbar = dirView.getToolbar(folder, window);
folder.setTopRight(toolbar, SWT.RIGHT);
folder.setSelection(tabcnt); //error occures 
```

The CTabFolder error:

`java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.internal.cocoa.NSImage.size()" because "this.image.handle" is null at org.eclipse.swt.widgets.Button.cellSizeForBounds(Button.java:153) at org.eclipse.swt.widgets.Display.windowProc(Display.java:6580) at org.eclipse.swt.internal.cocoa.OS.objc_msgSend_stret(Native Method) at org.eclipse.swt.internal.cocoa.NSCell.cellSize(NSCell.java:37) at org.eclipse.swt.widgets.Button.computeSize(Button.java:224) at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493) at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225) at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:168) at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:232) at org.eclipse.swt.widgets.TabFolder.minimumSize(TabFolder.java:447) at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:238) at org.eclipse.swt.widgets.TabFolder.computeSize(TabFolder.java:143) at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493) at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225) at org.eclipse.swt.layout.GridLayout.computeSize(GridLayout.java:168) at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:232) at org.eclipse.swt.custom.SashFormLayout.computeSize(SashFormLayout.java:50) at org.eclipse.swt.widgets.Composite.computeSize(Composite.java:232) at org.eclipse.swt.layout.GridData.computeSize(GridData.java:493) at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:225) at org.eclipse.swt.layout.GridLayout.layout(GridLayout.java:201) at org.eclipse.swt.widgets.Composite.updateLayout(Composite.java:1308) at org.eclipse.swt.widgets.Composite.resized(Composite.java:1030) at org.eclipse.swt.widgets.Group.resized(Group.java:231) at org.eclipse.swt.widgets.Control.setFrameSize(Control.java:3989) at org.eclipse.swt.widgets.Display.windowProc(Display.java:6308) at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method) at org.eclipse.swt.internal.cocoa.NSView.setFrame(NSView.java:252) at org.eclipse.swt.widgets.Control.setBounds(Control.java:3711) at org.eclipse.swt.widgets.Control.setBounds(Control.java:3752) at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3237) `

**Screenshots**
![264709965-c8f089f1-8c3f-46c8-bd35-47d1935f5e93](https://github.com/eclipse-platform/eclipse.platform.swt/assets/36766/b73d22e7-e039-45ab-8fa3-22bfd01b2781)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [] All OS
- - [ ] Linux
- - [x ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
MacOS Catalina 10.15.7

3. JRE/JDK version
 java 20.0.1 2023-04-18
Java(TM) SE Runtime Environment (build 20.0.1+9-29)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)

**Version since**
I use the latest Standard Widget Toolkit For Mac OS X (Cocoa) 3.124.0

How to fix it?

**Comment by Phillipus** [comment]
I tried to reproduce the error with `CTabFoler` but could not. Could you supply a self-contained SWT Snippet to reproduce the problem?

**Comment by mogilka** [comment]
> Could you supply a self-contained SWT Snippet to reproduce the problem?

Sorry, it's my fault. I found my error while preparing a snippet for you: for some reason I dispose an image located in a tab item before Tabfolder.pack(). You can see the code in my Tab class, line 71 (the archive attached):

`image.dispose();`

I was confused because Linux SWT library version compiled my code without error, but MacOS SWT throws a NullPointerException. Sorry for wasting your time. It's because of Mercury retrograde ☺

[Snippets.zip](https://github.com/eclipse-platform/eclipse.platform.swt/files/12505164/Snippets.zip)

**Comment by Phillipus** [comment]
Glad you figured it out. I suspected it was because of disposing an image.

> It's because of Mercury retrograde ☺

I had to discover the cause, because I'm Scorpio. 🦂
