### ISSUE TITLE
Synchronizer does not need to notify if nobody is waiting

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.swt#81]
The "lock.notifyAll()" in org.eclipse.swt.widgets.Synchronizer.runAsyncMessages
causes a little overhead of further ~50ms in BenchmarkSwtMultithreading.
When messages have been enqueued for async execution there is no thread waiting anyway.

**Comment by mickaelistria** [comment]
I assume this is fixed with #82.

**Comment by mickaelistria** [comment]
@jukzi Please tell us if you feel like you can fix it promptly or it it's safer to revert for the moment.

**Comment by jukzi** [comment]
please revert, if i find time i will take a look later what went wrong. sounds reproducible.
