### ISSUE TITLE
Highlighting problem when using the dark theme on Windows.

### ISSUE THREAD

**Issue by marioja** [eclipse-platform/eclipse.platform.swt#811]
**Describe the bug**
Highlighting problem when clicking between the left tree view and the right page in the Eclipse preference pages when using the dark theme.

**To Reproduce**
When using the Eclipse preferences dialog with the dark theme, the current preference in the left tree selection pane is not visible as soon as an item is selected in the right hand side preferences pane (problem-1). If I click back on the left tree selection item for the current preference page, then the selection of the current setting in the right hand window is no longer visible(problem-2). I will attach a screen shot of both problems. This does not happen with the Eclipse Classic theme and you can use that theme to see how things should work.

**Expected behavior**
I expect the left tree to always highlight the node when working on the right hand pane.  I expect the current item in the right hand pane to remain highlighted when I click back on the node in the left tree.

**Screenshots**
Problem-1: You cannot notice that the current item in the tree is 'Keys'
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/49068/7918665f-d7bb-4f3e-8970-c2872b0cd51f)
Problem-2: You cannot notice that the current key settings in the right is Add Attribute to XML (or it is barely noticeable)
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/49068/1bd148d9-599d-4bde-b39f-8bc83a433d4b)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

Windows 10

4. JRE/JDK version
 JDK 17
**Version since**
 Eclipse 2023-09 (noticed in Eclipse 2023-03)

**Workaround (or) Additional context**
This problem also happens between the Enterprise Explorer and the editor tabs in the Java EE Perspective.

**Comment by Phillipus** [comment]
If this is theme related you might want to report or transfer the issue here - https://github.com/eclipse-platform/eclipse.platform.ui/issues

**Comment by marioja** [comment]
Hi @Phillipus I opened it because another issue which was fixed by a [commit](https://github.com/eclipse-platform/eclipse.platform.swt/commit/fbd70cd1cce60500699938e8525a3f345bd4dc70) that you pointed out to me was fixed by correcting some code in this repository.  I suspect that this might be the same problem again but I am not the expert here by any stretch.  What should I do, create one also in eclipse-platform, transfer it to eclipse-platform or leave it here?  BTW I presume that by "transfer" you mean recreate in other repo and close in this one?

**Comment by Phillipus** [comment]
@marioja It might be an issue with one of the dark theme CSS files [here](https://github.com/eclipse-platform/eclipse.platform.ui/tree/master/bundles/org.eclipse.ui.themes/css). I suspect that might be the case rather than being SWT. Let's see if anyone else knows.

**Comment by marioja** [comment]
@Christopher-Hermann if you have time could you have a look at this problem. I apologize if I am breaking etiquette by tagging you.

**Comment by marioja** [comment]
Should I create a similar issue in eclipse.platform.ui repo also?

**Comment by marioja** [comment]
@Phillipus I tried to test this myself by modifying the same in my .p2 folder: C:\Users\Public\.p2\pool\plugins\org.eclipse.ui.themes_1.2.2200.v20230220-0932\css\e4-dark_win.css
I restarted eclipse and I did not see any change.  Am I missing something?

**Comment by Christopher-Hermann** [comment]
Unfortunately, I'm not able to reproduce the error. I'm running on MacOS where everything works like expected. When I install eclipse on my VM, the preferences looks like this:
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/79514265/9b63234a-6644-4174-9f2a-42b610eb5d66)
Do you have any special settings? For example, your scrollbar is painted a dark color while my scrollbar is gray.

**Comment by marioja** [comment]
@Christopher-Hermann Good day, thank you for chiming in.  This problem is on Windows 10 as indicated in the original post on this issue.  Do you have access to Windows 10?  Windows 11 may work differently, I have not tested.  As I said before, if someone can help me I could help work/test/fix this problem.

**Comment by marioja** [comment]
Sorry guys, Eclipse 2023-12 is out and this is still not fixed.  Can anyone look into this?  I always use dark them and it makes it really hard for my eyes to relate trees to selections.  If someone could help me troubleshoot this on windows I am willing to help.  I have no knowledge of the code base and I cannot do anything on my own.  Send me a PM and we can connect.

**Comment by marioja** [comment]
I will do the test and report back.  It would be nice if eclipse could respect the os current color scheme.  I am running windows in dark mode and eclipse will use the white mode unless I switch to using the dark theme.  On to testing...

**Comment by marioja** [comment]
ok, testing result.  Unfortunately, with Windows 10 it is never simple.  When you set windows to use dark mode so go to settings/colors and you select the Dark under choose your color.  Unfortunately, this does not provide you with an option to select different colors for different components such as Selected text.  This is only available when using the high contrast mode and when I select that, indeed Eclipse will use the Selected text color in the tree portion.  But that is not an option since this problem is related to use case when one is not using high contrast mode.  I will try to use your commit.  How do I do this?

**Comment by marioja** [comment]
I personally think that your solution for respecting the eclipse dark theme colors in Windows by overriding how the selected text is written is perfectly acceptable.  The current implementation of dark theme in Windows at least is totally based independent of the Windows dark mode settings and it should be.  A developer should be able to use eclipse dark mode without having to switch to Windows dark mode or even if they switched.

One feature in the future could be that if you are running eclipse in a Windows using Light color then eclipse switches to Light theme and if you are using Windows in Dark color then eclipse switches to Dark theme.  This again does not mean it would have to use the windows selected text color, it could still override it but just switches the theme based on the windows color.

There is still the possibility to have Eclipse use the windows theme colors to set the eclipse theme but that is something else and if we have control over eclipse themes and it works in either windows colors then there is no incentive IMHO.

**Comment by Christopher-Hermann** [comment]
The problem with my commit is that the selection color is overwritten for all TreeViewers. I assume that this will also overwrite the color in viewers with custom coloring which is not acceptable. We could also change the coloring in the eclipse tree viewer for the preferences, but then we will end up with different colors in different trees which is also a really strange behavior. 
I need to test how my change affects the custom coloring in other tree viewers.

**Comment by marioja** [comment]
I tried finally your branch, it took me long time to do step 1 and I think if I check out your commit in any eclipse and run an eclipse application it should work without all the rest of the 4G in the platform-sdk folder, but then again, this is all black magic so I am not sure if that is true.

When I navigate and the package explorer is active I am not sure I like that blue color.  Should be selectable in preference maybe?

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/49068/53df5c05-2136-40a7-8c5e-18f4f9d972b1)

When I click on the editor tabs, the dark grey highlight in package explorer is quite good:

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/49068/f7c769b2-da16-48ac-89fe-32bf6a59c449)

The same color apply in preferences, which is ok.

If the bright blue when the tree is active cannot be changed, it is still acceptable.  Better if it could be user settable.

As for your comment about cusom coloring in other tree viewers maybe there could be a way for other tree viewers to no use these colors.  What would those be using currently without your branch.  If they behave as the rest of eclipse it is probably as bad.  If they do not, well I guess they do not use the theme.   Maybe an option is available to other tree viewers to use the theme or use the custom coloring.  Or maybe using custom coloring could disable the behaviour you have introduced in your branch.  I would love to have your branch in eclipse 2023-12 as soon as possible.

**Comment by marioja** [comment]
I just noticed the two preferences in Colors and Fonts (after looking at the branch and the code change).  Cool.  Personally, I prever Tree selection color focused to be RGB 81.155.255.

When can this code be added to an update for 2023-12?

**Comment by Christopher-Hermann** [comment]
I uploaded a new version of my commit with color support on tree viewer and table viewer. Furthermore you can change the colors in the preferences via Colors and Fonts > Basic > Selection ...

Here is a code snipped to test the different settings/styles. Could you import this project into your workspace and try it out under Windows? It would also be nice to have some screenshots. To open the test dialog you must: CTRL+3 and search for command "Open Viewer Demo Dialog"
[viewerDemo.zip](https://github.com/eclipse-platform/eclipse.platform.swt/files/13794036/viewerDemo.zip)

I took the same colors as it is done in MacOS. So maybe they are not perfect, but at least the coding looks promising now. Here is a screenshot how it looks on MacOS:
<img width="1381" alt="JfaceViewers" src="https://github.com/eclipse-platform/eclipse.platform.swt/assets/79514265/895164d1-93ec-44cd-bb93-27b2a374662e">

My change was only possible for Table and Tree viewer, so most probably you will still have issues on the list viewer

**Comment by marioja** [comment]
I will look at your change.  As for 2023-12, please note that I work for a large public sector organization.  They are just in the process to move to 2023-12 which includes long awaited enterprise fixes in some IBM plugins.  It would be extremely useful to have a back port of this fix in 2023-12 since upgrading follow long release cycles.
In the past I have had very low success doing this as the plugin repo is signed and it makes it difficult to introduce those changes myself.  You help would be greatly appreciated.

**Comment by marioja** [comment]
Here is a screen shot of the Test viewer with selection on windows:
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/49068/56d43a1d-4706-4fb4-8dad-8ad58936427d)
I tried clicking on the last row in each section. Unfortunately I was unable to get anything highlighted in the second columns

**Comment by marioja** [comment]
As for the Eclipse IDE, I could see the effect of the Colors and Fonts> Basic> Selection...
However, I noticed that there is no highlighting for the Enterprise Explorer view and the source code tabs.  This is very important as we spend more time in that use case than in the preference dialog box.  I know that this use case might fall into the "list viewer" category (although the Enterprise Explorer looks like a tree viewer to me) but regardless of what category it falls, this feature is very important and is a must IMHO.  This is the use case that made me create the issue in the first place.  Do you think you will be able to do something about it and do you think you will be able to do something about eclipse 2023-12?

**Comment by Christopher-Hermann** [comment]
I'm not aware of the Enterprise Explorer view, how can I install this view?

**Comment by Christopher-Hermann** [comment]
Can you share a screenshot? I don't find a "Enterprise Explorer" view in the Eclipse IDE for Enterprise Java and Web Developers. I assume that this view is appiling a custom coloring in the Table/Tree. And as already discussed, it's highly incompatible to overwrite custom coloring.
In my first change, the coloring in the Table/Tree didn't pay attention to any custom coloring that is done from other plugins.

**Comment by marioja** [comment]
Will provide a screen shot later but it will show no highlighting.  You need to open the java ee perspective.  You can email me at mfj (at) earthling.net and we could chat and discuss if you want.

**Comment by marioja** [comment]
This is a screen shot using the Enterprise Explorer view.  As you can see the Java source DCInitializer.java is not highlighted in the tree view on the left when my cursor is inside the java editor view on the right:
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/49068/7da1e2d8-84da-4b24-813d-048e0b421f7f)
If I click on the Enterprise Explorer view title then you see the file highlighted in the tree view but this disappears as soon as I click in the java editor view.
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/49068/1e00d99d-4fd1-4044-8129-9a65ffc916f7)

**Comment by akurtakov** [comment]
Just to be sure - does it happen when using "Project Explorer" ? We have to be 100% sure that it's not a problem in particular view.

**Comment by BeckerWdf** [comment]
> [marioja](/marioja)

@marioja: Can you answer this question?

**Comment by marioja** [comment]
> > Just to be sure - does it happen when using "Project Explorer" ? We have to be 100% sure that it's not a problem in particular view.
> 
> 
> 
> @marioja: Can you answer this question?

Sorry, I forgot. Will report back today

**Comment by marioja** [comment]
I don't know what the Project Explorer is.  I switched to the Java perspective and the same problem occurs in the package explorer.

**Comment by chirontt** [comment]
Thanks a lot to @Christopher-Hermann for your PR to fix this highlighting problem in Windows including the Windows on Arm64. I've built my own Eclipse SDK (for 2024-06) for Windows on Arm64 with your fix, and it works nicely.

@marioja have you gotten the fix to work with your Eclipse 2023-12 installation? I think you can rebuild the `org.eclipse.jface` and `org.eclipse.ui` plugins with the fix and substitute them in your own installation, without the need to rebuild/reinstall the complete Eclipse 2023-12 release.
