### ISSUE TITLE
Splash screen image is reversed in I20231011-1800

### ISSUE THREAD

**Issue by noopur2507** [eclipse-platform/eclipse.platform.swt#837]
macOS 14.0 Sonoma
I20231011-1800

The splash screen image is reversed. See attached image.
<img width="492" alt="Splash screen" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/8749449/ca447317-9fb5-49b9-98eb-86e81851696f">

I don't have access to other OS/Platforms so I'm not sure if this is a platform specific issue.

**Comment by elsazac** [comment]
This issue seems to be the same that is reported in #772

**Comment by noopur2507** [comment]
> This issue seems to be the same that is reported in #772

Yes, closing this one as a duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/772.
