### ISSUE TITLE
The internal browser is outdated

### ISSUE THREAD

**Issue by wimjongman** [eclipse-platform/eclipse.platform.swt#840]
We cannot receive youtube anymore in the internal browser.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/180969/97db8923-4ecd-444d-8df9-a8b0836dc26f)

**Comment by vogella** [comment]
Most likely Windows. I have seem that too. I think SWT still uses IE on Windows.

**Comment by Phillipus** [comment]
Assuming you're on Windows you could use Edge by adding this to eclipse.ini (and make sure Edge Runtime is installed):

`-Dorg.eclipse.swt.browser.DefaultType=edge`

But you'll find other issues using Edge:

https://github.com/eclipse-platform/eclipse.platform.swt/issues?q=edge+browser

**Comment by vogella** [comment]
@Phillipus can Eclipse use the internal Edge browser? I though that was not possible and requires an extra installation of Edge.

**Comment by vogella** [comment]
@Phillipus awesome to hear that Windows 11 provides Edge. I think if SWT runs on Windows 11 we should in this case default to Edge instead of the unmaintained IE API

**Comment by HeikoKlare** [comment]
The premature state of the Edge browser can also be seen in #672. I tried to enable the browser tests for Edge with that PR, but did not yet get it running properly. Still you can see in the PR how many tests have to be disabled for the Edge browser because either there is no API for the functionality or because it has not been implemented in SWT yet.

**Comment by eliasbalasis** [comment]
I understand the problem and even though there is still a temporary workaround using `Dorg.eclipse.swt.browser.DefaultType=edge` at eclipse/lsp4e#820 it is not permanent and may start breaking going forward.

Unfortunately, I don't have enough familiarity to contribute, but I do need to stress the importance.

**Comment by Phillipus** [comment]
Even if Edge-related bugs are fixed a major issue to address is https://github.com/eclipse-platform/eclipse.platform.swt/issues/213, and see [this comment](https://github.com/eclipse-platform/eclipse.platform.swt/issues/213#issuecomment-1773736860).

**Comment by eliasbalasis** [comment]
It starts sounding like the tip of the iceberg.

**Comment by eliasbalasis** [comment]
In relation to eclipse/lsp4e#820

On Eclipse 2023-09 with m2e 2.4.0
`-Dorg.eclipse.swt.browser.DefaultType=edge` is not needed anymore on Windows OS.

**Comment by wimjongman** [comment]
Thank you all. I will try out if the web view templates in PDM still work.
