### ISSUE TITLE
MacOS Sonoma menu says "NewApplication" instead of "Eclipse"

### ISSUE THREAD

**Issue by guw** [eclipse-platform/eclipse.platform.swt#844]
See the attached screenshot:
<img width="254" alt="image" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/191472/4046d9c8-2c40-417a-bf15-4b6bc34a9211">

The top level menu no longer says "Eclipse" on Sonoma 14.0

**Comment by iloveeclipse** [comment]
The bug is known, please check bug tracker.

**Comment by guw** [comment]
Thanks! I just discovered #831 in SWT issue tracker.
