### ISSUE TITLE
Cannot copy from KDE Applications to Eclipse in Wayland session

### ISSUE THREAD

**Issue by the-snowwhite** [eclipse-platform/eclipse.platform.swt#851]
Closing as this has been fixed in latest gtk3 and changing swt gtk3 clipboard implementation has to potential to destabilize things and gtk4 port has it working with the new approach already.

_Originally posted by @akurtakov in https://github.com/eclipse-platform/eclipse.platform.swt/issues/421#issuecomment-1369523287_

**Comment by akurtakov** [comment]
Interesting. I have tried coping from Eclipse to Kate  (both running under wayland) and it worked but kate to eclipse didn't.

**Comment by the-snowwhite** [comment]
@akurtakov  Yes thanks that is exactly my point.
I'm running kde neon where it is not possible to copy either way between kate and eclipse in a wayland session.
So I recompiled the newest gtk version: 3.24.38 (from mantic) and installed.
That made it possible to copy from eclipse to kate, but not the other way.

**Comment by the-snowwhite** [comment]
I have also just tested Kubuntu 22.10 and Fedora KDE Plasma Desktop 38, same issue.

**Comment by akurtakov** [comment]
I would not have time to look into this one any time soon so we need someone to step up and work on a fix.

**Comment by the-snowwhite** [comment]
OK ... I'm not experienced with eclipse code so I do not know what more I can do right now.
Thanks for acknowledging the Issue :-)

**Comment by the-snowwhite** [comment]
Inspired by a [comment in this thread](https://bugs.kde.org/show_bug.cgi?id=431100#c11) I figured out a small workaround:
install the wl-clipboard package and the run this command before pasting to eclipse:

    wl-paste -n -t text/plain | wl-copy -t STRING

**Comment by the-snowwhite** [comment]
In hope of the KDE-Team being able to provide a wayland lecgacy solution like Gnome-gtk I have opened a bug repport there:
https://bugs.kde.org/show_bug.cgi?id=476522

**Comment by mickaelistria** [comment]
Thanks for the report, this comment helps "the issue essentially boils down to Eclipse not supporting Wayland clipboard content types (RFC-1341 types).". Do you think you can help with that?

**Comment by the-snowwhite** [comment]
@mickaelistria Testing out my bugfix is now completed with success 
https://github.com/eclipse-platform/eclipse.platform.swt/discussions/858 
The initial test commit is currently residing in this branch: (dont know if It would be possible to backport the fix)

https://github.com/eclipse-platform/eclipse.platform.swt/compare/master...the-snowwhite:eclipse.platform.swt:wayland_qt_paste_fix_R4.29

The initial commit for master is here:

https://github.com/eclipse-platform/eclipse.platform.swt/compare/master...the-snowwhite:eclipse.platform.swt:wayland_qt_paste_fix?expand=1

What I found out in all my testing is that It does exactly what promised:
running in both gtk v3.24.33 and gtk v3.24.38 it is possible to paste into eclipse from all applications that only present 
RFC-1341 types (so far only text/plain;charset=utf-8) in the clipboard under a wayland session.
I have also just tested pasting the danish special characters åæø and that went fine also.
...
Lastly I looked into if I would be able to get the copy to wayland clipboard functionality to work under gtk v3.24.33.
So far no luck.
That seems like a much more complicated issue...
So I would like this bugfix to stand alone as a paste from wayland only fix.
(the copy to wayand to eclipse issue is anyhow fixed upstream)

**Comment by mickaelistria** [comment]
OK. Can you please create a PR for master?
We usually don't backport much in Eclipse Platform because we don't build older branches, so backporting shows no strong benefit.

**Comment by the-snowwhite** [comment]
@mickaelistria 
OK --> https://github.com/eclipse-platform/eclipse.platform.swt/pull/861

**Comment by the-snowwhite** [comment]
@mickaelistria 
I have just opened https://github.com/eclipse-platform/eclipse.platform.swt/pull/863
It needs a thorough review as: 
It's somewhat a more complex complement to https://github.com/eclipse-platform/eclipse.platform.swt/pull/861
Which I also included since It relies on that code.
 Please feel welcome to specify any changes needed.

**Comment by the-snowwhite** [comment]
@mickaelistria
@iloveeclipse
sorry for the delay but I had chores to do, seems like you came up with the correct actions meanwhile :1st_place_medal: 
I can now 99.7% confirm that https://github.com/eclipse-platform/eclipse.platform.swt/commit/a90888b23f95a78b32795054e86e8ab0cb756399
Fully fixes the complications introduced in 666b7fd8fff95d286d4bf4cabd10649c36a7bbb7
reducing it to the same nice simplicity as my first commit fixing the 1 issue that the original title of this issue described: bbd763b8a644c0af3af41ff553092c0e87d41bdd

I have now verified that commit bbd763b8a644c0af3af41ff553092c0e87d41bdd together with the a90888b23f95a78b32795054e86e8ab0cb756399 combination of 666b7fd8fff95d286d4bf4cabd10649c36a7bbb7
Was apply-able to R_29_Maintenance.

After the 2  mvn compilations I was the possible to confirm that full wayland clipboard functionality worked in all my 2023-09 installs running on ubuntu-LTS base without the gtk wayland fix (gtk 3.24.22).

Via copying the 3 renamed swt jar binaries in the plugin folder.

A great thanks to all involved in expanding this issue from 1 to 2 and resolving all the interesting mishaps that came up.

**Comment by the-snowwhite** [comment]
For the record
The clean and reworded versions of the 3 commits involved in providing wayland full QT-clipboard functionality.
and finally solving #421 in Eclipse swt.
https://github.com/eclipse-platform/eclipse.platform.swt/compare/master...the-snowwhite:eclipse.platform.swt:wayland_qt_paste_copy_fix_R4.29

**Comment by the-snowwhite** [comment]
A commit ima
![issue_851_final_commit_PR image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/11050908/e163e2ef-52a3-4694-be8d-c7acdfd94e45)
ge Just for the record:
https://github.com/the-snowwhite/eclipse.platform.swt/tree/wayland_qt_paste_copy_fix_R4.29
