### ISSUE TITLE
Ubuntu 23.04 - strange artifacts in certain resolutions

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.swt#859]
If I use Ubuntu 23.04 with 200% resolution, I see back artifacts in the product, MANIFEST.MF and plugin.xml editor. 

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/139910/3e975439-4156-4c58-95a1-a2dcc00fdae2)

**Comment by Phillipus** [comment]
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/577

**Comment by iloveeclipse** [comment]
Closing as duplicate of #577
