### ISSUE TITLE
How can I make it possible to always be able to make a pull request to any branch and only fetch the build artifacts without any merge ?

### ISSUE THREAD

**Issue by the-snowwhite** [eclipse-platform/eclipse.platform.swt#888]
How can I make it possible to always be able to make a pull request to any branch and only fetch the build artifacts without any need to merge (and then close the PR after a build success)?

Based upon coming up with [a better answer for this question](https://github.com/eclipse-platform/eclipse.platform.swt/discussions/858)
[Than the fallback solution here:](https://github.com/eclipse-platform/eclipse.platform.swt/discussions/858#discussioncomment-7538739)

[The new answer is here:](https://github.com/eclipse-platform/eclipse.platform.swt/discussions/858#discussioncomment-7542214)

The current implementation of this new feature is is currently stuck in [this issue](https://github.com/eclipse-platform/eclipse.platform.swt/issues/885) by [this blocked pull request:](https://github.com/eclipse-platform/eclipse.platform.swt/pull/886/files#diff-6485b884863fd4f54a20976acef942fe0dd257eb4e72ca25533fd84b7b6fe2e6)
here:
https://github.com/eclipse-platform/eclipse.platform.swt/pull/886#pullrequestreview-1726125380

Is it possible to update [this book](https://wiki.eclipse.org/Version_Numbering) to cover an always successful build where only the build artifacts are required and no merge is performed ?
 
Or is some sort of alternative needed ?

**Comment by the-snowwhite** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/pull/886#issuecomment-1806947866

**Comment by the-snowwhite** [comment]
All I need is for the builder to skip the mvn -check command that requires an update of the.
`Bundle-Version: 3.124.100.qualifier`

only the last 2 mvn commands are required to generate build artifacts without a merge:

In the swt.binaries folder

    mvn --batch-mode -Pbuild-individual-bundles -DforceContextQualifier=zzz -Dcompare-version-with-baselines.skip=true -Dmaven.compiler.failOnWarning=true install

In the main swt folder:

    mvn --batch-mode -V -U -DforkCount=1 -Dcompare-version-with-baselines.skip=false -Dmaven.compiler.failOnWarning=true --fail-at-end -DskipNativeTests=false -DfailIfNoTests=false clean install

**Comment by mickaelistria** [comment]
you should build SWT locally to get what you want. Looking in the Jenkinsfile will show you concrete commands to build SWT.
Once you're happy with your local build (you successfully tested it) and think it's worth adding it into the project directly, you can create a PR and then see the output in https://ci.eclipse.org/releng/job/eclipse.platform.swt/view/change-requests/job/PR-883/lastSuccessfulBuild/artifact/eclipse.platform.swt.binaries/bundles/org.eclipse.swt.gtk.linux.x86_64/target/ (which you can also test).
If the PR succeeds without error nor broken tests, then it can be considered for a review and a merge.
