### ISSUE TITLE
Inconsistent minor version change in SWT 4.30

### ISSUE THREAD

**Issue by GregorQFS** [eclipse-platform/eclipse.platform.swt#896]
**Describe the bug**

This is a minor issue but easy to fix and it requires a decision before the final SWT 4.30 release.

By convention MINOR_VERSION in org.eclipse.swt.internal.Library is increased by 2 for each quarterly release. In SWT 4.29 it was 962, so the expected value in 4.30 is 964. However, in SWT 4.30RC1 it is 963.

As a result, all code that tries to map old-style version numbers to Library *_VERSION constants will break and need to be updated to 
handle this new special case.

**To Reproduce**
Code only.

**Expected behavior**
MINOR_VERSION in SWT 4.30 should be 964

**Screenshots**
N/A

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [x] All OS
- - [ ] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)

3. JRE/JDK version
 
**Version since**
 SWT 4.30

**Workaround (or) Additional context**

I know that the numbering scheme for MINOR_VERSION is not fixed in any way, but just convention. But maintaining the convention makes it easier for code that maps version numbers to releases.

There was an inadvertent break of the scheme in SWT 4.18 where MINOR_VERSION increased by 4 and we had a discussion on the platform-dev mailing list then. It was too difficult to fix and kept as is.

I don't know if this new case in SWT 4.30 is a mistake or an intended change of the convention. If it is a mistake, I hope it can be fixed before releasing SWT 4.30. Increasing the MINOR_VERSION number at this point should not have any negative impact.

On the other hand it might be a good time to take a step back and think about changing the current scheme to increase MINOR_VERSION by 1 instead of 2 from SWT 4.30 on. With four releases per year this would result in nine more years of three-digit minor version numbers. Otherwise MINOR_VERSION will switch to four ditgits in ~2028.

**Comment by deepika-u** [comment]
@GregorQFS 
Sorry if i got late in replying on this thread.
https://github.com/eclipse-platform/eclipse.platform.swt/pull/796#discussion_r1315762719

The above is the link and reference to the original issue where the increment is done as per Lakshmi's suggestion as part of 4.29 so that we have more 3digit numbers available for the future releases.

**Comment by GregorQFS** [comment]
Ahh, sorry @deepika-u  I should have been more thorough in my search. Until recently my focus was solely on the mailing list. I'm going to extend it to github.
As mentioned I fully agree with this approach so I'll try to close this issue.
