### ISSUE TITLE
[win] slow org.eclipse.swt.internal.BidiUtil.resolveTextDirection()

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.swt#90]
When i open my eclipse commiter workspace it takes some seconds till everything is shown and i can finally search for a type (ctrl shift T).
I sampled a bit and (beside that the files are refreshed - i understand that need) the longest time (6sec) is spend in 
org.eclipse.swt.internal.win32.OS.GetCharacterPlacement[native] ()
inside BidiUtil.resolveTextDirection().

I don't even need any Bidi support so that feels just bad. Is there a way to turn bidi support of or a chance of less costly detection of bidi characters (without native calls **for every single character**)?
![image](https://user-images.githubusercontent.com/51790620/166631467-67674fd2-230f-47d9-9d12-c2d9693cb27d.png)

according to the source that bidi feature was added in 2015 https://bugs.eclipse.org/bugs/show_bug.cgi?id=467463
but is only recently used in this context since 2022-04  https://bugs.eclipse.org/bugs/show_bug.cgi?id=579626
@niraj-modi

**Comment by jukzi** [comment]
@niraj-modi could for example java.lang.Character.getDirectionality(char) used instead of systemcall?

**Comment by akurtakov** [comment]
Considering that even the fix done is for win32 only and not implemented on other archs, what @jukzi proposes makes a lot of sense and being implemented for Mac/Linux too.

**Comment by SyntevoAlex** [comment]
I suspect that a better fix is to test one character per run instead of testing all characters. It's likely that Windows already splits LTR /  RTL into different runs.

**Comment by jukzi** [comment]
> I suspect that a better fix is to test one character per run instead of testing all characters. It's likely that Windows already splits LTR / RTL into different runs.

would you mind to propose a fix for that?

**Comment by SyntevoAlex** [comment]
> would you mind to propose a fix for that?

I would rather hope that @niraj-modi can fix it. I have no experience with RTL/LTR, and he seems to have it.
