### ISSUE TITLE
HiDPI and Ubuntu 22.04

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-platform/eclipse.platform.swt#93]
Hi folks, I am transferring this issue from EPP where it was reported (https://bugs.eclipse.org/bugs/show_bug.cgi?id=579816):

There appears to be an issue with HiDPI on Ubuntu 22.04 where (perhaps) there is some bad interaction with built-in scaling and Eclipse's scaling, quoting from the bug:

> when I increase resolution and scale on "ubuntu's Displays settings", the application goes blinking and does not work as expected. otherwise, the font is too small to be read.

![image](https://user-images.githubusercontent.com/679236/166736931-ff5ff0e5-35e2-4519-a84d-9da34bf7d52e.png)

**Comment by sravanlakkimsetti** [comment]
I tried the following combinations on Ubuntu 22.04

1. Gnome with Wayland
2. Gnome with Xorg(X11)
3. Ubuntu with Wayland
4. Ubuntu with Xorg(X11)

I did not get any problems.

![VirtualBox_Ubuntu 22_05_05_2022_15_52_39](https://user-images.githubusercontent.com/77106773/166905268-e769f4a1-13d1-4158-8678-9218ade41210.png)
I hope you are using the same settings window. In my case I am using FullHD resolution. and use the scale as either 100% or 200%. 

Please set the resolution to maximum supported by the display. This will not have any impact on the running of eclipse.
The HiDpi scaling gets triggered by the "scale factor from Di. Please try to set it to 100%/200%. That should work.

**Comment by jonahgraham** [comment]
Thanks @sravanlakkimsetti for the investigation. I hope the OP from bugzilla can provide more info. For now I'll close this until more info is provided.

**Comment by sravanlakkimsetti** [comment]
Can you try adding the following line at the end of the eclipse.ini and give a try?
```
-Dswt.autoScale=integer 
```

**Comment by sravanlakkimsetti** [comment]
If there are no objections I would like increase the scaling limit to 400%. Currently it is 200%

**Comment by vogella** [comment]
+1

**Comment by lshanmug** [comment]
> If there are no objections I would like increase the scaling limit to 400%. Currently it is 200%

Do we need to have an upper limit or is it possible to remove it?

From Eclipse POV, we have images only for 100 & 200%, so images will be scaled and blurry for higher zoom values.

**Comment by sravanlakkimsetti** [comment]
Lets remove the upper limit.

**Comment by vogella** [comment]
> > If there are no objections I would like increase the scaling limit to 400%. Currently it is 200%
> 
> Do we need to have an upper limit or is it possible to remove it?
> 
> From Eclipse POV, we have images only for 100 & 200%, so images will be scaled and blurry for higher zoom values.

We have svg files and a generator to generate new files with higher resolution.  If you think we should add higher resolution images, please open an issue and cc @MatthiasBecker and myself.
