### ISSUE TITLE
Windows 11: Selection is not visible in MenuItem with image of type "check" 

### ISSUE THREAD

**Issue by cody2013** [eclipse-platform/eclipse.platform.swt#946]
The selection of the menu item is not visible if an image is set. This behavior occurs only in Windows 11. In Windows 10 the image is marked as selected:

![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/5145406/72d4a3a9-8e54-4fb0-95eb-f90ede8e1759)

libraries used: org.eclipse.swt.win32.win32.x86_64_3.124.100.v20230825-1346.jar, org.eclipse.e4.ui.model.workbench_2.4.100.v20230801-1255.jar

code snippet:
Menu menu = new Menu(control);

MenuItem menuItem = new MenuItem(menu, SWT.RADIO);
menuItem.setSelection(true); // activate the selection
menuItem.setImage(image);

...
menu.setLocation(...);
menu.setVisible(true);

**Comment by merks** [comment]
This is a duplicate of the following issue:

https://github.com/eclipse-platform/eclipse.platform.swt/issues/501
