### ISSUE TITLE
Including a font registry into SWT

### ISSUE THREAD

**Issue by akoch-yatta** [eclipse-platform/eclipse.platform.swt#967]
Hello everyone,
we are currently working on improving on the HiDPI support in Windows. There, we need to take of font scaling programmatically on zoom level changes and must keep track of those fonts to be able to reuse them later on. This requires us to maintain a record of these fonts for future reuse. To address this, we are utilizing a font registry and are curious about the absence of a general version in SWT, noting that it is only available through JFace.

We are considering whether there are compelling reasons for not integrating a font registry directly into SWT. To address our HiDPI font challenges, we could implement an internal, non-public font registry. However, we propose developing and offering a basic font registry applicable across all operating systems.

We have developed the following interface for this purpose:

```
public interface SWTFontRegistry {
  /**
   * Returns a system font optimally suited for the specified shell.
   *
   * @param shell the shell context used to determine the appropriate system font
   * @return the system font best suited for the specified shell
   */
   Font getSystemFont(Shell shell);

  /**
   * Provides a font optimally suited for the specified shell. Fonts created in this manner
   * are managed by the font registry and should not be disposed of externally.
   *
   * @param fontData the data used to create the font
   * @param shell the shell context used to determine the appropriate font
   * @return the font best suited for the specified shell
   */
   Font getFont(FontData fontData, Shell shell);

  /**
   * Disposes of all fonts managed by the font registry.
   */
   void dispose();
}
```

Key points regarding the proposed interface:

- The inclusion of a `Shell` parameter in `getSystemFont` and `getFont` is essential for determining the correct font size in HiDPI scenarios on Windows. Ideally, only the zoom level is needed, but using the Shell provides a more universally applicable parameter.
- We suggest making the font registry accessible through the Device class via Device::getFontRegistry.
- Due to including `getSystemFont` each operating system will need a simple basic implementation
- Importantly, the use of this font registry will be optional for users of SWT

Any input regarding this proposal would be appreciated; especially, if there are strong argument against adding a font registry to the SWT API.

**Comment by laeubi** [comment]
@akoch-yatta if shell is important, why not having a `Shell#getFontfactory()` and omit the shell parameter? It could then still delegate to a global object but I think the user should not fiddle around with shell parameter.

**Comment by merks** [comment]
The Font constructor only needs a Device and a Display is a Device.  I see no immediate reason why a Shell rather than a Display or a Device would be used here.  JFace's font registry just does things like this:

>	boldFont = new Font(Display.getCurrent(), boldData);

I suppose that one issue here is that different monitors can have different resolution, so the shell would help pinpoint the monitor and hence that monitors resolution.  But that's something I need to read between the lines to guess at.

**Comment by laeubi** [comment]
@merks there is usually only one `Display` but multiple shells on different monitors (even though windows _can_ have multiple Displays). So I assume @akoch-yatta has a good reason for it, but maybe you are right that the the Monitor should have such methods and not the Shell, but the main point seems caching here ... so even a static thing like DPIUtil will be sufficient as well.

**Comment by merks** [comment]
@HeikoKlare 

FYI, I wonder if you guys have issues with with Font scaling as well and might want to coordinate on an effort like this?   I don't know the current state of SWT in terms of understanding that different monitors have different scaling...

**Comment by HeikoKlare** [comment]
Thanks, Ed. We work together with @akoch-yatta and his collegues at Yatta on HiDPI support for multi-monitor setups on Windows. That's where the discussion on a font registry came up, so I am already involved in the topic.

**Comment by akoch-yatta** [comment]
> I suppose that one issue here is that different monitors can have different resolution, so the shell would help pinpoint the monitor and hence that monitors resolution. But that's something I need to read between the lines to guess at.

@merks thank you for the remark. You read correctly between the lines this issue relates back to the monitor. The idea to use the shell stems from #131, but I see, why it seems unnecessary for this general purpose API, especially when the necessity is primarily linked to HiDPI concerns. Using `Shell#getFontRegistry()` would help getting rid of the Shell parameter in the interface.

> @merks there is usually only one `Display` but multiple shells on different monitors (even though windows _can_ have multiple Displays). So I assume @akoch-yatta has a good reason for it, but maybe you are right that the the Monitor should have such methods and not the Shell, but the main point seems caching here ... so even a static thing like DPIUtil will be sufficient as well.

@laeubi thank you for the remark. Transferring this functionality to the Monitor class would introduce complexities or issues, if I'm understanding your point correctly. For example, if a Shell is moved to a different monitor, the Shell would use a different font registry. Taking our current WIP implementation into consideration using the Shell as the reference point works quite well. So, providing `Shell#getFontRegistry()` as API to delegate to the factory instead of `Device::getFontRegistry()` sounds good to me.

**Comment by merks** [comment]
I think the argument is fine if it has a good purpose, which I think it does.  That purpose should be explained in the Javadoc.  I just don't know the current state of where the knowledge about zoom is all available, so take any comment I have with a large grain of salt.  I'm only trying to be helpful and I'm sure others have deeper knowledge.

**Comment by tmssngr** [comment]
Do I understand it correctly, that a shell now should not hold a `Font` reference any more but a (cloned) `FontData`, so it can somehow update the `Font` if moved to a different monitor? What about child controls and their set fonts?

**Comment by akoch-yatta** [comment]
> Do I understand it correctly, that a shell now should not hold a `Font` reference any more but a (cloned) `FontData`, so it can somehow update the `Font` if moved to a different monitor? What about child controls and their set fonts?

@tmssngr no, the Font class usage remains the same. The font registry's main goal is to simplify the handling and reusability of fonts in SWT. The challenge of font size changes due to monitor zoom level adjustments is not part of this issue, but a font registry is part of the solution. So we had the idea to extract some kind of base font registry as a feature of the SWT API, rather than working with it as an internal-only tool.

**Comment by tmssngr** [comment]
Then I would suggest to first introduce it as internal API to solve the problem. Otherwise it might be possible that this registry is not needed for fixing the dpi-problem (though it looks so now), but the font registry remains without a good reason.
