### ISSUE TITLE
[Edge] Browser with SWT.EDGE freezes as all black or white on some urls

### ISSUE THREAD

**Issue by codegoddesskh** [eclipse-platform/eclipse.platform.swt#968]
**Describe the bug**
Navigating an Edge browser to some URLs (so far ```https://twitter.com``` and ```https://facebook.com```) freeze the Edge widget. The rest of the SWT Shell is sometimes slow but responsive to be able to close the app, but often also appears frozen.

**To Reproduce**
I've modified Snippet270 to change it to use Edge and set the url to ```https://twitter.com``` which produces a stuck white or black window instead of any browser content.

```
package org.eclipse.swt.snippets;

/*
 * Browser snippet: bring up a browser with pop-up window support
 *
 * For a list of all SWT example snippets see
 * http://www.eclipse.org/swt/snippets/
 *
 * @since 3.1
 */
import org.eclipse.swt.*;
import org.eclipse.swt.browser.*;
import org.eclipse.swt.graphics.*;
import org.eclipse.swt.layout.*;
import org.eclipse.swt.widgets.*;

public class Snippet270 {

    static final int BROWSER_STYLE = SWT.EDGE;  //EDITED: previously SWT.NONE

    public static void main(String[] args) {
	Display display = new Display();
	Shell shell = new Shell(display);
	shell.setText("Main Window");
	shell.setLayout(new FillLayout());
	final Browser browser;
	try {
		browser = new Browser(shell, BROWSER_STYLE);
	} catch (SWTError e) {
		System.out.println("Could not instantiate Browser: " + e.getMessage());
		display.dispose();
		return;
	}
	initialize(display, browser);
	shell.open();

	//EDITED: previously "https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_win_open"
	browser.setUrl("https://twitter.com");

	while (!shell.isDisposed()) {
	    if (!display.readAndDispatch())
		display.sleep();
	}
	display.dispose();
    }

    /* register WindowEvent listeners */
    static void initialize(final Display display, Browser browser) {
	browser.addOpenWindowListener(event -> {
		if (!event.required) return;	/* only do it if necessary */
		Shell shell = new Shell(display);
		shell.setText("New Window");
		shell.setLayout(new FillLayout());
		Browser browser1 = new Browser(shell, BROWSER_STYLE);
		initialize(display, browser1);
		event.browser = browser1;
	});
	browser.addVisibilityWindowListener(new VisibilityWindowListener() {
		@Override
		public void hide(WindowEvent event) {
			Browser browser = (Browser)event.widget;
			Shell shell = browser.getShell();
			shell.setVisible(false);
		}
		@Override
		public void show(WindowEvent event) {
			Browser browser = (Browser)event.widget;
			final Shell shell = browser.getShell();
			if (event.location != null) shell.setLocation(event.location);
			if (event.size != null) {
				Point size = event.size;
				shell.setSize(shell.computeSize(size.x, size.y));
			}
			shell.open();
		}
	});
	browser.addCloseWindowListener(event -> {
		Browser browser1 = (Browser)event.widget;
		Shell shell = browser1.getShell();
		shell.close();
	});

	// EDIT: added more listeners below
	browser.addLocationListener(new LocationListener() {
		@Override
		public void changing(LocationEvent event) {
		    System.out.println("Location changing: " + event);
		}

		@Override
		public void changed(LocationEvent event) {
		    System.out.println("Location changed: " + event);
		}
	    });

	browser.addProgressListener(new ProgressListener() {
		@Override
		public void changed(ProgressEvent event) {
		    System.out.println("Progress changed: " + event);
		}

		@Override
		public void completed(ProgressEvent event) {
		    System.out.println("Progress completed: " + event);
		}
	    });
    }
}
```

**Environment:**

Windows 11
Microsoft Edge WebView2 Runtime 120.0.2210.121
Eclipse Adoptium jdk-17.0.2.8
SWT 4.30.0

**Workaround (or) Additional context**
I'm guessing that this is a WebView2 deadlock issue, and I will to try to figure out what I can. Thoughts/ideas very much welcome.

**Comment by deepika-u** [comment]
@codegoddesskh 
I have tried the shared snippet with both urls with SWT.EDGE but not able to reproduce the reported problem. Able to see the respective urls load fine.

First time -> 1. browser.setUrl("https://twitter.com"); 
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/46807064/612e8c9d-27ee-4772-93b8-92bce2426ab7)

Second time -> 2. browser.setUrl("https://facebook.com");
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/46807064/d65f1b65-e55d-42b4-9aad-c1cd2ecae08b)

I have tried on both the below environments. 
Eclipse SDK
Version: 2024-03 (4.31)
Build id: I20240117-1800
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.6+10
Java version: 17.0.6

Eclipse SDK
Version: 2024-03 (4.31)
Build id: I20240117-1800
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Oracle Corporation
Java runtime version: 21.0.1+12-29
Java version: 21.0.1

I have tried with below setting
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/46807064/23a890c0-d3e6-41a2-856a-da53c1318067)

Do you have any other (settings)preferences with which you are seeing the problem?

**Comment by codegoddesskh** [comment]
I re-tried it myself again this morning with the exact same setup as before and those URLs are working now for me. I will check in with my user who brought the issue to my attention to confirm it is working again for them as well and then close the issue.

**Comment by Phillipus** [comment]
I tried your Snippet on Windows 11 last week and I also experienced the same freezing with those URLs. I tried again just now and it's working OK. Perhaps an update to Windows fixed it?

Windows 11 Pro, Build: 22631.3007
Microsoft Edge WebView2 Runtime 120.0.2210.133

**Comment by codegoddesskh** [comment]
Thank you @deepika-u for alerting me that the issue was resolved. And thank you @Phillipus for confirming you saw the issue as well, and that you see it resolved now too.

It's indeed a mystery of what was wrong and what fixed it, but I'll happily accept a mystery in my favor for now! :)
