### ISSUE TITLE
Windows Compile fails due to missing Display#isXMouseActive

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.swt#98]
See https://github.com/eclipse-platform/eclipse.platform.swt/runs/6323264272?check_suite_focus=true

```
Error:  Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.0-SNAPSHOT:compile (default-compile) on project org.eclipse.swt.tests.win32: Compilation failure: Compilation failure: 
Error:  D:\a\eclipse.platform.swt\eclipse.platform.swt\eclipse.platform.swt\tests\org.eclipse.swt.tests.win32\JUnit Tests\org\eclipse\swt\widgets\Test_org_eclipse_swt_widgets_Display.java:[24] 
Error:  	boolean xMouseActive = display.isXMouseActive();
Error:  	                               ^^^^^^^^^^^^^^
Error:  The method isXMouseActive() is undefined for the type Display
Error:  1 problem (1 error)
Error:  -> [Help 1]
```

**Comment by niraj-modi** [comment]
> @niraj-modi can you help here?
> 
> Actually the method is there but only for the Win32 Display so it seems, event though the compile runs on Windows, it does not uses the right classes to compile.

Yes, this is one odd test that's specific to windows only, for now disabling it to test the remaining "Build with maven" workflow.

**Comment by laeubi** [comment]
> Yes, this is one odd test that's specific to windows only, for now disabling it to test the remaining "Build with maven" workflow.

Sure but I actually *want* compile for windows so should not the test compile as well?

**Comment by niraj-modi** [comment]
> > Yes, this is one odd test that's specific to windows only, for now disabling it to test the remaining "Build with maven" workflow.
> 
> Sure but I actually _want_ compile for windows so should not the test compile as well?

For now I could work-around this compilation failure using reflection using #99
We can continue to investigate on the root cause here.

**Comment by laeubi** [comment]
That would be good, as I think this is just an indication of a more deeper issue I have seen that @jukzi has added the test, @jukzi do you run the maven build under windows? do it succeed there to compile the class? Did you use any special commandline or runtime configuration?

**Comment by jukzi** [comment]
I only use eclipse. never building on command line.
Feels like this error is a duplicate of https://github.com/eclipse/tycho/issues/512

**Comment by laeubi** [comment]
I don't think this is related, there a type can't be resolved but here the type is resolved but a method is not found (thus it is resolved to some other "Display" ...

**Comment by jukzi** [comment]
both is tycho, both does not find something which does exist.

**Comment by laeubi** [comment]
> both is tycho, both does not find something which does exist.

Yeah both is Eclipse, so maybe its "Eclipse" ;-)

**Comment by laeubi** [comment]
This is fixed now and was due to an configuration error.
