### ISSUE TITLE
Test_org_eclipse_swt_SWT.isLocal() fails all builds without a change in project org.eclipse.swt 

### ISSUE THREAD

**Issue by HannesWell** [eclipse-platform/eclipse.platform.swt#983]
In order to fix https://github.com/eclipse-platform/eclipse.platform.swt/issues/251 PR https://github.com/eclipse-platform/eclipse.platform.swt/pull/252 introduced the case `Test_org_eclipse_swt_SWT.test_isLocal()`

I'm not sure I have completely understood that test in full detail, but I have the impression that it fails in all builds if no changes where made within the `org.eclipse.swt` project and consequently `o.e.swt` and it's native fragments are baseline-replaced.
Recently there have been some changes in the build of SWT. After the binaries move into this repo, I have reworkd the qualifier computation in https://github.com/eclipse-platform/eclipse.platform.swt/pull/963 to assign the native fragments the qualifier of the host at build-time which makes the qualifier change commits obsolete.
And I have even prepared a PR to build the native binaries from scratch even in GH workflows: https://github.com/eclipse-platform/eclipse.platform.swt/pull/972

@SyntevoAlex with that I think that test case is not necessary anymore, is it?

**Comment by laeubi** [comment]
I assume it will fail when the binaries are signed as it assumes they are not. So if baseline replace takes place it will always fail:
https://github.com/eclipse-platform/eclipse.platform.swt/blob/3e43811d941f326e6a5eec9bec4a4688af61309c/tests/org.eclipse.swt.tests/JUnit%20Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_SWT.java#L177-L182

**Comment by SyntevoAlex** [comment]
Can you clarify why are tests being run on SWT without any changes in SWT?

**Comment by SyntevoAlex** [comment]
It was implemented in #251 where I found that wrong SWT was being tested by GitHub.

**Comment by HannesWell** [comment]
> Can you clarify why are tests being run on SWT without any changes in SWT?

Tests are executed on each verification build, even if for example only the build config changes like in #972 or if for example the SWT tools change.

> It was implemented in #251 where I found that GitHub tested baseline SWT instead of SWT from the PR.

Yes. With the recent changes I have the impression that the problem cannot happen anymore and the test could be removed. We could also disable baseline replacement, at least for the GH workflows, but then the test is also obsolete.

**Comment by SyntevoAlex** [comment]
It makes sense to me to disable baseline replacement for GH tests, because it's more resilient to unexpected problems. The test will not be obsolete, it's like with any other test that currently succeeds - it's there to catch problems in the future.

**Comment by HannesWell** [comment]
> The test will not be obsolete, it's like with any other test that currently succeeds - it's there to catch problems in the future.

In general I would fully agree, but in this case one could also argue that it is basically testing the tycho-p2-baseline-plugin.
Anyway, I just created https://github.com/eclipse-platform/eclipse.platform.swt/pull/986 to disable baseline-replacement for GH workflows and disabled the test for Jenkins (where we should keep it enabled to not detect comparator differences only in I-builds).
