### ISSUE TITLE
[Win32] wrong event type for horizontal mouse wheel events

### ISSUE THREAD

**Issue by mabuerki** [eclipse-platform/eclipse.platform.swt#994]
**Describe the bug**
org.eclipse.swt.widgets.Scrollable does emit events of type SWT.MouseVerticalWheel when the horizontal mouse wheel is used.

**To Reproduce**
```
import org.eclipse.swt.SWT;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Event;
import org.eclipse.swt.widgets.Listener;
import org.eclipse.swt.widgets.Shell;

public class Test {

	public static void main(String[] args) {
		Display display = new Display();
	    Shell shell = new Shell(display);
		shell.open();
		
		shell.addListener(SWT.MouseVerticalWheel, new Listener() {
			
			@Override
			public void handleEvent(Event event) {
				System.out.println("vertical wheel event received");
			}
		});
		shell.addListener(SWT.MouseHorizontalWheel, new Listener() {
			
			@Override
			public void handleEvent(Event event) {
				System.out.println("horizontal wheel event received");
			}
		});
		
		while (!shell.isDisposed()) {
			if (!display.readAndDispatch()) {
				display.sleep();
			}
		}
	}
}
```
**Expected behavior**
Horizontal mouse wheel events should have type SWT.MouseHorizontalWheel

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

**Workaround (or) Additional context**
The cause is probably here, if horzWheel is true it should call super.WM_MOUSEHWHEEL instead of super.WM_MOUSEWHEEL: 
https://github.com/eclipse-platform/eclipse.platform.swt/blob/dd0447cadaa4073dc2c3b2560e1e0e33b6979c23/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/widgets/Scrollable.java#L376-L377

**Comment by deepika-u** [comment]
@mabuerki 
Sorry but asking a very basic question how do i generate an event with horzWheel is true or a horizontal mouse wheel event. Can you give me some more details on the recreate of the issue please? Does any other prior settings also to be set? on windows 11 for this to be enabled?

I have tried all the below but always events are getting generated with horzWheel as false.
- tried to use the mouse wheel up and down (which is action to generate vertical mouse wheel event, horzWheel is seen as false)
- tried to hold the shift key on keyboard and use the mouse wheel up and down(in this case also horzWheel is seen as false)
- tried to hold the control key followed by shift key on the keyboard and use the mouse wheel up and down(in this case also horzWheel is seen as false)

**Comment by mabuerki** [comment]
You will probably need a mouse with horizontal wheel support, then pushing the wheel to the left or right will generate such events.
Even though it is possible in some applications to scroll horizontally by holding the shift key and turning the wheel up and down this seems not to generate WM_MOUSEHWHEEL events (at least in SWT).

**Comment by deepika-u** [comment]
Is there any way to simulate this horizontal mouse wheel event with touchpad and keyboard key combination as such? I dint understand you completely.

**Comment by mabuerki** [comment]
On a touchpad it is possible to get horizontal mouse wheel events by placing two fingers on the touchpad and moving them horizontally.

**Comment by deepika-u** [comment]
@mabuerki 
Thanks, i am able to recreate the scenario where horzWheel is showing true with your last update.

So providing a pr for the same, can you test with the patch and confirm if both kind of events are now working fine please?
pr -> https://github.com/eclipse-platform/eclipse.platform.swt/pull/1056

**Comment by mabuerki** [comment]
Yes, I can confirm that with your fix the mouse wheel events work fine now.
Thanks for fixing this.
